window.wordPool = [
  // 生成済
    {"word": "grinning face", "emoji": "😀"},
    {"word": "grinning face with big eyes", "emoji": "😃"},
    {"word": "grinning face with smiling eyes", "emoji": "😄"},
    {"word": "beaming face with smiling eyes", "emoji": "😁"},
    {"word": "grinning squinting face", "emoji": "😆"},
    {"word": "grinning face with sweat", "emoji": "😅"},
    {"word": "rolling on the floor laughing", "emoji": "🤣"},
    {"word": "face with tears of joy", "emoji": "😂"},
    {"word": "slightly smiling face", "emoji": "🙂"},
    {"word": "upside-down face", "emoji": "🙃"},
    {"word": "melting face", "emoji": "🫠"},
    {"word": "winking face", "emoji": "😉"},
    {"word": "smiling face with smiling eyes", "emoji": "😊"},
    {"word": "smiling face with halo", "emoji": "😇"},
    {"word": "smiling face with hearts", "emoji": "🥰"},
    {"word": "smiling face with heart-eyes", "emoji": "😍"},
    {"word": "star-struck", "emoji": "🤩"},
    {"word": "face blowing a kiss", "emoji": "😘"},
    {"word": "kissing face", "emoji": "😗"},
    {"word": "smiling face", "emoji": "☺️"},
    {"word": "kissing face with closed eyes", "emoji": "😚"},
    {"word": "kissing face with smiling eyes", "emoji": "😙"},
    {"word": "smiling face with tear", "emoji": "🥲"},
    {"word": "face savoring food", "emoji": "😋"},
    {"word": "face with tongue", "emoji": "😛"},
    {"word": "winking face with tongue", "emoji": "😜"},
    {"word": "zany face", "emoji": "🤪"},
    {"word": "squinting face with tongue", "emoji": "😝"},
    {"word": "money-mouth face", "emoji": "🤑"},
    {"word": "smiling face with open hands", "emoji": "🤗"},
    {"word": "face with hand over mouth", "emoji": "🤭"},
    {"word": "face with open eyes and hand over mouth", "emoji": "🫢"},
    {"word": "face with peeking eye", "emoji": "🫣"},
    {"word": "shushing face", "emoji": "🤫"},
    {"word": "thinking face", "emoji": "🤔"},
    {"word": "saluting face", "emoji": "🫡"},
    {"word": "zipper-mouth face", "emoji": "🤐"},
    {"word": "face with raised eyebrow", "emoji": "🤨"},
    {"word": "neutral face", "emoji": "😐"},
    {"word": "expressionless face", "emoji": "😑"},
    {"word": "face without mouth", "emoji": "😶"},
    {"word": "dotted line face", "emoji": "🫥"},
    {"word": "face in clouds", "emoji": "😶‍🌫️"},
    {"word": "smirking face", "emoji": "😏"},
    {"word": "unamused face", "emoji": "😒"},
    {"word": "face with rolling eyes", "emoji": "🙄"},
    {"word": "grimacing face", "emoji": "😬"},
    {"word": "face exhaling", "emoji": "😮‍💨"},
    {"word": "lying face", "emoji": "🤥"},
    {"word": "shaking face", "emoji": "🫨"},
    {"word": "head shaking horizontally", "emoji": "🙂‍↔️"},
    {"word": "head shaking vertically", "emoji": "🙂‍↕️"},
    {"word": "relieved face", "emoji": "😌"},
    {"word": "pensive face", "emoji": "😔"},
    {"word": "sleepy face", "emoji": "😪"},
    {"word": "drooling face", "emoji": "🤤"},
    {"word": "sleeping face", "emoji": "😴"},
    {"word": "face with bags under eyes", "emoji": "🫩"},
    {"word": "face with medical mask", "emoji": "😷"},
    {"word": "face with thermometer", "emoji": "🤒"},
    {"word": "face with head-bandage", "emoji": "🤕"},
    {"word": "nauseated face", "emoji": "🤢"},
    {"word": "face vomiting", "emoji": "🤮"},
    {"word": "sneezing face", "emoji": "🤧"},
    {"word": "hot face", "emoji": "🥵"},
    {"word": "cold face", "emoji": "🥶"},
    {"word": "woozy face", "emoji": "🥴"},
    {"word": "face with crossed-out eyes", "emoji": "😵"},
    {"word": "face with spiral eyes", "emoji": "😵‍💫"},
    {"word": "exploding head", "emoji": "🤯"},
    {"word": "cowboy hat face", "emoji": "🤠"},
    {"word": "partying face", "emoji": "🥳"},
    {"word": "disguised face", "emoji": "🥸"},
    {"word": "smiling face with sunglasses", "emoji": "😎"},
    {"word": "nerd face", "emoji": "🤓"},
    {"word": "face with monocle", "emoji": "🧐"},
    {"word": "confused face", "emoji": "😕"},
    {"word": "face with diagonal mouth", "emoji": "🫤"},
    {"word": "worried face", "emoji": "😟"},
    {"word": "slightly frowning face", "emoji": "🙁"},
    {"word": "frowning face", "emoji": "☹️"},
    {"word": "face with open mouth", "emoji": "😮"},
    {"word": "hushed face", "emoji": "😯"},
    {"word": "astonished face", "emoji": "😲"},
    {"word": "flushed face", "emoji": "😳"},
    {"word": "pleading face", "emoji": "🥺"},
    {"word": "face holding back tears", "emoji": "🥹"},
    {"word": "frowning face with open mouth", "emoji": "😦"},
    {"word": "anguished face", "emoji": "😧"},
    {"word": "fearful face", "emoji": "😨"},
    {"word": "anxious face with sweat", "emoji": "😰"},
    {"word": "sad but relieved face", "emoji": "😥"},
    {"word": "crying face", "emoji": "😢"},
    {"word": "loudly crying face", "emoji": "😭"},
    {"word": "face screaming in fear", "emoji": "😱"},
    {"word": "confounded face", "emoji": "😖"},
    {"word": "persevering face", "emoji": "😣"},
    {"word": "disappointed face", "emoji": "😞"},
    {"word": "downcast face with sweat", "emoji": "😓"},
    {"word": "weary face", "emoji": "😩"},
    {"word": "tired face", "emoji": "😫"},
    {"word": "yawning face", "emoji": "🥱"},
    {"word": "face with steam from nose", "emoji": "😤"},
    {"word": "enraged face", "emoji": "😡"},
    {"word": "angry face", "emoji": "😠"},
    {"word": "face with symbols on mouth", "emoji": "🤬"},
    {"word": "grinning cat", "emoji": "😺"},
    {"word": "grinning cat with smiling eyes", "emoji": "😸"},
    {"word": "cat with tears of joy", "emoji": "😹"},
    {"word": "smiling cat with heart-eyes", "emoji": "😻"},
    {"word": "cat with wry smile", "emoji": "😼"},
    {"word": "kissing cat", "emoji": "😽"},
    {"word": "weary cat", "emoji": "🙀"},
    {"word": "crying cat", "emoji": "😿"},
    {"word": "pouting cat", "emoji": "😾"},


    // 未生成
    // ここから？
    {"word": "left speech bubble", "emoji": "🗨️"},
    {"word": "right anger bubble", "emoji": "🗯️"},
    {"word": "thought balloon", "emoji": "💭"},
    {"word": "zzz", "emoji": "💤"},
    {"word": "waving hand", "emoji": "👋"},
    {"word": "raised back of hand", "emoji": "🤚"},
    {"word": "hand with fingers splayed", "emoji": "🖐️"},
    {"word": "raised hand", "emoji": "✋"},
    {"word": "vulcan salute", "emoji": "🖖"},
    {"word": "rightwards hand", "emoji": "🫱"},
    {"word": "leftwards hand", "emoji": "🫲"},
    {"word": "palm down hand", "emoji": "🫳"},
    {"word": "palm up hand", "emoji": "🫴"},
    {"word": "leftwards pushing hand", "emoji": "🫷"},
    {"word": "rightwards pushing hand", "emoji": "🫸"},
    {"word": "ok hand", "emoji": "👌"},
    {"word": "pinched fingers", "emoji": "🤌"},
    {"word": "pinching hand", "emoji": "🤏"},
    {"word": "victory hand", "emoji": "✌️"},
    {"word": "crossed fingers", "emoji": "🤞"},
    {"word": "hand with index finger and thumb crossed", "emoji": "🫰"},
    {"word": "love-you gesture", "emoji": "🤟"},
    {"word": "sign of the horns", "emoji": "🤘"},
    {"word": "call me hand", "emoji": "🤙"},
    {"word": "backhand index pointing left", "emoji": "👈"},
    {"word": "backhand index pointing right", "emoji": "👉"},
    {"word": "backhand index pointing up", "emoji": "👆"},
    {"word": "middle finger", "emoji": "🖕"},
    {"word": "backhand index pointing down", "emoji": "👇"},
    {"word": "index pointing up", "emoji": "☝️"},
    {"word": "index pointing at the viewer", "emoji": "🫵"},
    {"word": "thumbs up", "emoji": "👍"},
    {"word": "thumbs down", "emoji": "👎"},
    {"word": "raised fist", "emoji": "✊"},
    {"word": "oncoming fist", "emoji": "👊"},
    {"word": "left-facing fist", "emoji": "🤛"},
    {"word": "right-facing fist", "emoji": "🤜"},
    {"word": "clapping hands", "emoji": "👏"},
    {"word": "raising hands", "emoji": "🙌"},
    {"word": "heart hands", "emoji": "🫶"},
    {"word": "open hands", "emoji": "👐"},
    {"word": "palms up together", "emoji": "🤲"},
    {"word": "handshake", "emoji": "🤝"},
    {"word": "folded hands", "emoji": "🙏"},
    {"word": "writing hand", "emoji": "✍️"},
    {"word": "nail polish", "emoji": "💅"},
    {"word": "selfie", "emoji": "🤳"},
    {"word": "flexed biceps", "emoji": "💪"},
    {"word": "mechanical arm", "emoji": "🦾"},
    {"word": "mechanical leg", "emoji": "🦿"},
    {"word": "leg", "emoji": "🦵"},
    {"word": "foot", "emoji": "🦶"},
    {"word": "ear", "emoji": "👂"},
    {"word": "ear with hearing aid", "emoji": "🦻"},
    {"word": "nose", "emoji": "👃"},
    {"word": "brain", "emoji": "🧠"},
    {"word": "anatomical heart", "emoji": "🫀"},
    {"word": "lungs", "emoji": "🫁"},
    {"word": "tooth", "emoji": "🦷"},
    {"word": "bone", "emoji": "🦴"},
    {"word": "eyes", "emoji": "👀"},
    {"word": "eye", "emoji": "👁️"},
    {"word": "tongue", "emoji": "👅"},
    {"word": "mouth", "emoji": "👄"},
    {"word": "biting lip", "emoji": "🫦"},
    {"word": "baby", "emoji": "👶"},
    {"word": "child", "emoji": "🧒"},
    {"word": "boy", "emoji": "👦"},
    {"word": "girl", "emoji": "👧"},
    {"word": "person", "emoji": "🧑"},
    {"word": "person blond hair", "emoji": "👱"},
    {"word": "man", "emoji": "👨"},
    {"word": "person beard", "emoji": "🧔"},
    {"word": "man beard", "emoji": "🧔‍♂️"},
    {"word": "woman beard", "emoji": "🧔‍♀️"},
    {"word": "man red hair", "emoji": "👨‍🦰"},
    {"word": "man curly hair", "emoji": "👨‍🦱"},
    {"word": "man white hair", "emoji": "👨‍🦳"},
    {"word": "man bald", "emoji": "👨‍🦲"},
    {"word": "woman", "emoji": "👩"},
    {"word": "woman red hair", "emoji": "👩‍🦰"},
    {"word": "person red hair", "emoji": "🧑‍🦰"},
    {"word": "woman curly hair", "emoji": "👩‍🦱"},
    {"word": "person curly hair", "emoji": "🧑‍🦱"},
    {"word": "woman white hair", "emoji": "👩‍🦳"},
    {"word": "person white hair", "emoji": "🧑‍🦳"},
    {"word": "woman bald", "emoji": "👩‍🦲"},
    {"word": "person bald", "emoji": "🧑‍🦲"},
    {"word": "woman blond hair", "emoji": "👱‍♀️"},
    {"word": "man blond hair", "emoji": "👱‍♂️"},
    {"word": "older person", "emoji": "🧓"},
    {"word": "old man", "emoji": "👴"},
    {"word": "old woman", "emoji": "👵"},
    {"word": "person frowning", "emoji": "🙍"},
    {"word": "man frowning", "emoji": "🙍‍♂️"},
    {"word": "woman frowning", "emoji": "🙍‍♀️"},
    {"word": "person pouting", "emoji": "🙎"},
    {"word": "man pouting", "emoji": "🙎‍♂️"},
    {"word": "woman pouting", "emoji": "🙎‍♀️"},
    {"word": "person gesturing no", "emoji": "🙅"},
    {"word": "man gesturing no", "emoji": "🙅‍♂️"},
    {"word": "woman gesturing no", "emoji": "🙅‍♀️"},
    {"word": "person gesturing ok", "emoji": "🙆"},
    {"word": "man gesturing ok", "emoji": "🙆‍♂️"},
    {"word": "woman gesturing ok", "emoji": "🙆‍♀️"},
    {"word": "person tipping hand", "emoji": "💁"},
    {"word": "man tipping hand", "emoji": "💁‍♂️"},
    {"word": "woman tipping hand", "emoji": "💁‍♀️"},
    {"word": "person raising hand", "emoji": "🙋"},
    {"word": "man raising hand", "emoji": "🙋‍♂️"},
    {"word": "woman raising hand", "emoji": "🙋‍♀️"},
    {"word": "deaf person", "emoji": "🧏"},
    {"word": "deaf man", "emoji": "🧏‍♂️"},
    {"word": "deaf woman", "emoji": "🧏‍♀️"},
    {"word": "person bowing", "emoji": "🙇"},
    {"word": "man bowing", "emoji": "🙇‍♂️"},
    {"word": "woman bowing", "emoji": "🙇‍♀️"},
    {"word": "person facepalming", "emoji": "🤦"},
    {"word": "man facepalming", "emoji": "🤦‍♂️"},
    {"word": "woman facepalming", "emoji": "🤦‍♀️"},
    {"word": "person shrugging", "emoji": "🤷"},
    {"word": "man shrugging", "emoji": "🤷‍♂️"},
    {"word": "woman shrugging", "emoji": "🤷‍♀️"},
    {"word": "health worker", "emoji": "🧑‍⚕️"},
    {"word": "man health worker", "emoji": "👨‍⚕️"},
    {"word": "woman health worker", "emoji": "👩‍⚕️"},
    {"word": "student", "emoji": "🧑‍🎓"},
    {"word": "man student", "emoji": "👨‍🎓"},
    {"word": "woman student", "emoji": "👩‍🎓"},
    {"word": "teacher", "emoji": "🧑‍🏫"},
    {"word": "man teacher", "emoji": "👨‍🏫"},
    {"word": "woman teacher", "emoji": "👩‍🏫"},
    {"word": "judge", "emoji": "🧑‍⚖️"},
    {"word": "man judge", "emoji": "👨‍⚖️"},
    {"word": "woman judge", "emoji": "👩‍⚖️"},
    {"word": "farmer", "emoji": "🧑‍🌾"},
    {"word": "man farmer", "emoji": "👨‍🌾"},
    {"word": "woman farmer", "emoji": "👩‍🌾"},
    {"word": "cook", "emoji": "🧑‍🍳"},
    {"word": "man cook", "emoji": "👨‍🍳"},
    {"word": "woman cook", "emoji": "👩‍🍳"},
    {"word": "mechanic", "emoji": "🧑‍🔧"},
    {"word": "man mechanic", "emoji": "👨‍🔧"},
    {"word": "woman mechanic", "emoji": "👩‍🔧"},
    {"word": "factory worker", "emoji": "🧑‍🏭"},
    {"word": "man factory worker", "emoji": "👨‍🏭"},
    {"word": "woman factory worker", "emoji": "👩‍🏭"},
    {"word": "office worker", "emoji": "🧑‍💼"},
    {"word": "man office worker", "emoji": "👨‍💼"},
    {"word": "woman office worker", "emoji": "👩‍💼"},
    {"word": "scientist", "emoji": "🧑‍🔬"},
    {"word": "man scientist", "emoji": "👨‍🔬"},
    {"word": "woman scientist", "emoji": "👩‍🔬"},
    {"word": "technologist", "emoji": "🧑‍💻"},
    {"word": "man technologist", "emoji": "👨‍💻"},
    {"word": "woman technologist", "emoji": "👩‍💻"},
    {"word": "singer", "emoji": "🧑‍🎤"},
    {"word": "man singer", "emoji": "👨‍🎤"},
    {"word": "woman singer", "emoji": "👩‍🎤"},
    {"word": "artist", "emoji": "🧑‍🎨"},
    {"word": "man artist", "emoji": "👨‍🎨"},
    {"word": "woman artist", "emoji": "👩‍🎨"},
    {"word": "pilot", "emoji": "🧑‍✈️"},
    {"word": "man pilot", "emoji": "👨‍✈️"},
    {"word": "woman pilot", "emoji": "👩‍✈️"},
    {"word": "astronaut", "emoji": "🧑‍🚀"},
    {"word": "man astronaut", "emoji": "👨‍🚀"},
    {"word": "woman astronaut", "emoji": "👩‍🚀"},
    {"word": "firefighter", "emoji": "🧑‍🚒"},
    {"word": "man firefighter", "emoji": "👨‍🚒"},
    {"word": "woman firefighter", "emoji": "👩‍🚒"},
    {"word": "police officer", "emoji": "👮"},
    {"word": "man police officer", "emoji": "👮‍♂️"},
    {"word": "woman police officer", "emoji": "👮‍♀️"},
    {"word": "detective", "emoji": "🕵️"},
    {"word": "man detective", "emoji": "🕵️‍♂️"},
    {"word": "woman detective", "emoji": "🕵️‍♀️"},
    {"word": "guard", "emoji": "💂"},
    {"word": "man guard", "emoji": "💂‍♂️"},
    {"word": "woman guard", "emoji": "💂‍♀️"},
    {"word": "ninja", "emoji": "🥷"},
    {"word": "construction worker", "emoji": "👷"},
    {"word": "man construction worker", "emoji": "👷‍♂️"},
    {"word": "woman construction worker", "emoji": "👷‍♀️"},
    {"word": "person with crown", "emoji": "🫅"},
    {"word": "prince", "emoji": "🤴"},
    {"word": "princess", "emoji": "👸"},
    {"word": "person wearing turban", "emoji": "👳"},
    {"word": "man wearing turban", "emoji": "👳‍♂️"},
    {"word": "woman wearing turban", "emoji": "👳‍♀️"},
    {"word": "person with skullcap", "emoji": "👲"},
    {"word": "woman with headscarf", "emoji": "🧕"},
    {"word": "person in tuxedo", "emoji": "🤵"},
    {"word": "man in tuxedo", "emoji": "🤵‍♂️"},
    {"word": "woman in tuxedo", "emoji": "🤵‍♀️"},
    {"word": "person with veil", "emoji": "👰"},
    {"word": "man with veil", "emoji": "👰‍♂️"},
    {"word": "woman with veil", "emoji": "👰‍♀️"},
    {"word": "pregnant woman", "emoji": "🤰"},
    {"word": "pregnant man", "emoji": "🫃"},
    {"word": "pregnant person", "emoji": "🫄"},
    {"word": "breast-feeding", "emoji": "🤱"},
    {"word": "woman feeding baby", "emoji": "👩‍🍼"},
    {"word": "man feeding baby", "emoji": "👨‍🍼"},
    {"word": "person feeding baby", "emoji": "🧑‍🍼"},
    {"word": "baby angel", "emoji": "👼"},
    {"word": "santa claus", "emoji": "🎅"},
    {"word": "mrs. claus", "emoji": "🤶"},
    {"word": "mx claus", "emoji": "🧑‍🎄"},
    {"word": "superhero", "emoji": "🦸"},
    {"word": "man superhero", "emoji": "🦸‍♂️"},
    {"word": "woman superhero", "emoji": "🦸‍♀️"},
    {"word": "supervillain", "emoji": "🦹"},
    {"word": "man supervillain", "emoji": "🦹‍♂️"},
    {"word": "woman supervillain", "emoji": "🦹‍♀️"},
    {"word": "mage", "emoji": "🧙"},
    {"word": "man mage", "emoji": "🧙‍♂️"},
    {"word": "woman mage", "emoji": "🧙‍♀️"},
    {"word": "fairy", "emoji": "🧚"},
    {"word": "man fairy", "emoji": "🧚‍♂️"},
    {"word": "woman fairy", "emoji": "🧚‍♀️"},
    {"word": "vampire", "emoji": "🧛"},
    {"word": "man vampire", "emoji": "🧛‍♂️"},
    {"word": "woman vampire", "emoji": "🧛‍♀️"},
    {"word": "merperson", "emoji": "🧜"},
    {"word": "merman", "emoji": "🧜‍♂️"},
    {"word": "mermaid", "emoji": "🧜‍♀️"},
    {"word": "elf", "emoji": "🧝"},
    {"word": "man elf", "emoji": "🧝‍♂️"},
    {"word": "woman elf", "emoji": "🧝‍♀️"},
    {"word": "genie", "emoji": "🧞"},
    {"word": "man genie", "emoji": "🧞‍♂️"},
    {"word": "woman genie", "emoji": "🧞‍♀️"},
    {"word": "zombie", "emoji": "🧟"},
    {"word": "man zombie", "emoji": "🧟‍♂️"},
    {"word": "woman zombie", "emoji": "🧟‍♀️"},
    {"word": "troll", "emoji": "🧌"},
    {"word": "hairy creature", "emoji": "🫈"},
    {"word": "person getting massage", "emoji": "💆"},
    {"word": "man getting massage", "emoji": "💆‍♂️"},
    {"word": "woman getting massage", "emoji": "💆‍♀️"},
    {"word": "person getting haircut", "emoji": "💇"},
    {"word": "man getting haircut", "emoji": "💇‍♂️"},
    {"word": "woman getting haircut", "emoji": "💇‍♀️"},
    {"word": "person walking", "emoji": "🚶"},
    {"word": "man walking", "emoji": "🚶‍♂️"},
    {"word": "woman walking", "emoji": "🚶‍♀️"},
    {"word": "person walking facing right", "emoji": "🚶‍➡️"},
    {"word": "woman walking facing right", "emoji": "🚶‍♀️‍➡️"},
    {"word": "man walking facing right", "emoji": "🚶‍♂️‍➡️"},
    {"word": "person standing", "emoji": "🧍"},
    {"word": "man standing", "emoji": "🧍‍♂️"},
    {"word": "woman standing", "emoji": "🧍‍♀️"},
    {"word": "person kneeling", "emoji": "🧎"},
    {"word": "man kneeling", "emoji": "🧎‍♂️"},
    {"word": "woman kneeling", "emoji": "🧎‍♀️"},
    {"word": "person kneeling facing right", "emoji": "🧎‍➡️"},
    {"word": "woman kneeling facing right", "emoji": "🧎‍♀️‍➡️"},
    {"word": "man kneeling facing right", "emoji": "🧎‍♂️‍➡️"},
    {"word": "person with white cane", "emoji": "🧑‍🦯"},
    {"word": "person with white cane facing right", "emoji": "🧑‍🦯‍➡️"},
    {"word": "man with white cane", "emoji": "👨‍🦯"},
    {"word": "man with white cane facing right", "emoji": "👨‍🦯‍➡️"},
    {"word": "woman with white cane", "emoji": "👩‍🦯"},
    {"word": "woman with white cane facing right", "emoji": "👩‍🦯‍➡️"},
    {"word": "person in motorized wheelchair", "emoji": "🧑‍🦼"},
    {"word": "person in motorized wheelchair facing right", "emoji": "🧑‍🦼‍➡️"},
    {"word": "man in motorized wheelchair", "emoji": "👨‍🦼"},
    {"word": "man in motorized wheelchair facing right", "emoji": "👨‍🦼‍➡️"},
    {"word": "woman in motorized wheelchair", "emoji": "👩‍🦼"},
    {"word": "woman in motorized wheelchair facing right", "emoji": "👩‍🦼‍➡️"},
    {"word": "person in manual wheelchair", "emoji": "🧑‍🦽"},
    {"word": "person in manual wheelchair facing right", "emoji": "🧑‍🦽‍➡️"},
    {"word": "man in manual wheelchair", "emoji": "👨‍🦽"},
    {"word": "man in manual wheelchair facing right", "emoji": "👨‍🦽‍➡️"},
    {"word": "woman in manual wheelchair", "emoji": "👩‍🦽"},
    {"word": "woman in manual wheelchair facing right", "emoji": "👩‍🦽‍➡️"},
    {"word": "person running", "emoji": "🏃"},
    {"word": "man running", "emoji": "🏃‍♂️"},
    {"word": "woman running", "emoji": "🏃‍♀️"},
    {"word": "person running facing right", "emoji": "🏃‍➡️"},
    {"word": "woman running facing right", "emoji": "🏃‍♀️‍➡️"},
    {"word": "man running facing right", "emoji": "🏃‍♂️‍➡️"},

    // この辺でスレッド移行

    {"word": "ballet dancer", "emoji": "🧑‍🩰"},
    {"word": "woman dancing", "emoji": "💃"},
    {"word": "man dancing", "emoji": "🕺"},
    {"word": "person in suit levitating", "emoji": "🕴️"},
    {"word": "people with bunny ears", "emoji": "👯"},
    {"word": "men with bunny ears", "emoji": "👯‍♂️"},
    {"word": "women with bunny ears", "emoji": "👯‍♀️"},
    {"word": "person in steamy room", "emoji": "🧖"},
    {"word": "man in steamy room", "emoji": "🧖‍♂️"},
    {"word": "woman in steamy room", "emoji": "🧖‍♀️"},
    {"word": "person climbing", "emoji": "🧗"},
    {"word": "man climbing", "emoji": "🧗‍♂️"},
    {"word": "woman climbing", "emoji": "🧗‍♀️"},
    {"word": "person fencing", "emoji": "🤺"},
    {"word": "horse racing", "emoji": "🏇"},
    {"word": "skier", "emoji": "⛷️"},
    {"word": "snowboarder", "emoji": "🏂"},
    {"word": "person golfing", "emoji": "🏌️"},
    {"word": "man golfing", "emoji": "🏌️‍♂️"},
    {"word": "woman golfing", "emoji": "🏌️‍♀️"},
    {"word": "person surfing", "emoji": "🏄"},
    {"word": "man surfing", "emoji": "🏄‍♂️"},
    {"word": "woman surfing", "emoji": "🏄‍♀️"},
    {"word": "person rowing boat", "emoji": "🚣"},
    {"word": "man rowing boat", "emoji": "🚣‍♂️"},
    {"word": "woman rowing boat", "emoji": "🚣‍♀️"},
    {"word": "person swimming", "emoji": "🏊"},
    {"word": "man swimming", "emoji": "🏊‍♂️"},
    {"word": "woman swimming", "emoji": "🏊‍♀️"},
    {"word": "person bouncing ball", "emoji": "⛹️"},
    {"word": "man bouncing ball", "emoji": "⛹️‍♂️"},
    {"word": "woman bouncing ball", "emoji": "⛹️‍♀️"},
    {"word": "person lifting weights", "emoji": "🏋️"},
    {"word": "man lifting weights", "emoji": "🏋️‍♂️"},
    {"word": "woman lifting weights", "emoji": "🏋️‍♀️"},
    {"word": "person biking", "emoji": "🚴"},
    {"word": "man biking", "emoji": "🚴‍♂️"},
    {"word": "woman biking", "emoji": "🚴‍♀️"},
    {"word": "person mountain biking", "emoji": "🚵"},
    {"word": "man mountain biking", "emoji": "🚵‍♂️"},
    {"word": "woman mountain biking", "emoji": "🚵‍♀️"},
    {"word": "person cartwheeling", "emoji": "🤸"},
    {"word": "man cartwheeling", "emoji": "🤸‍♂️"},
    {"word": "woman cartwheeling", "emoji": "🤸‍♀️"},
    {"word": "people wrestling", "emoji": "🤼"},
    {"word": "men wrestling", "emoji": "🤼‍♂️"},
    {"word": "women wrestling", "emoji": "🤼‍♀️"},
    {"word": "person playing water polo", "emoji": "🤽"},
    {"word": "man playing water polo", "emoji": "🤽‍♂️"},
    {"word": "woman playing water polo", "emoji": "🤽‍♀️"},
    {"word": "person playing handball", "emoji": "🤾"},
    {"word": "man playing handball", "emoji": "🤾‍♂️"},
    {"word": "woman playing handball", "emoji": "🤾‍♀️"},
    {"word": "person juggling", "emoji": "🤹"},
    {"word": "man juggling", "emoji": "🤹‍♂️"},
    {"word": "woman juggling", "emoji": "🤹‍♀️"},
    {"word": "person in lotus position", "emoji": "🧘"},
    {"word": "man in lotus position", "emoji": "🧘‍♂️"},
    {"word": "woman in lotus position", "emoji": "🧘‍♀️"},
    {"word": "person taking bath", "emoji": "🛀"},
    {"word": "person in bed", "emoji": "🛌"},
    {"word": "people holding hands", "emoji": "🧑‍🤝‍🧑"},
    {"word": "women holding hands", "emoji": "👭"},
    {"word": "woman and man holding hands", "emoji": "👫"},
    {"word": "men holding hands", "emoji": "👬"},
    {"word": "kiss", "emoji": "💏"},
    {"word": "kiss woman, man", "emoji": "👩‍❤️‍💋‍👨"},
    {"word": "kiss man, man", "emoji": "👨‍❤️‍💋‍👨"},
    {"word": "kiss woman, woman", "emoji": "👩‍❤️‍💋‍👩"},
    {"word": "couple with heart", "emoji": "💑"},
    {"word": "couple with heart woman, man", "emoji": "👩‍❤️‍👨"},
    {"word": "couple with heart man, man", "emoji": "👨‍❤️‍👨"},
    {"word": "couple with heart woman, woman", "emoji": "👩‍❤️‍👩"},
    {"word": "family man, woman, boy", "emoji": "👨‍👩‍👦"},
    {"word": "family man, woman, girl", "emoji": "👨‍👩‍👧"},
    {"word": "family man, woman, girl, boy", "emoji": "👨‍👩‍👧‍👦"},
    {"word": "family man, woman, boy, boy", "emoji": "👨‍👩‍👦‍👦"},
    {"word": "family man, woman, girl, girl", "emoji": "👨‍👩‍👧‍👧"},
    {"word": "family man, man, boy", "emoji": "👨‍👨‍👦"},
    {"word": "family man, man, girl", "emoji": "👨‍👨‍👧"},
    {"word": "family man, man, girl, boy", "emoji": "👨‍👨‍👧‍👦"},
    {"word": "family man, man, boy, boy", "emoji": "👨‍👨‍👦‍👦"},
    {"word": "family man, man, girl, girl", "emoji": "👨‍👨‍👧‍👧"},
    {"word": "family woman, woman, boy", "emoji": "👩‍👩‍👦"},
    {"word": "family woman, woman, girl", "emoji": "👩‍👩‍👧"},
    {"word": "family woman, woman, girl, boy", "emoji": "👩‍👩‍👧‍👦"},
    {"word": "family woman, woman, boy, boy", "emoji": "👩‍👩‍👦‍👦"},
    {"word": "family woman, woman, girl, girl", "emoji": "👩‍👩‍👧‍👧"},
    {"word": "family man, boy", "emoji": "👨‍👦"},
    {"word": "family man, boy, boy", "emoji": "👨‍👦‍👦"},
    {"word": "family man, girl", "emoji": "👨‍👧"},
    {"word": "family man, girl, boy", "emoji": "👨‍👧‍👦"},
    {"word": "family man, girl, girl", "emoji": "👨‍👧‍👧"},
    {"word": "family woman, boy", "emoji": "👩‍👦"},
    {"word": "family woman, boy, boy", "emoji": "👩‍👦‍👦"},
    {"word": "family woman, girl", "emoji": "👩‍👧"},
    {"word": "family woman, girl, boy", "emoji": "👩‍👧‍👦"},
    {"word": "family woman, girl, girl", "emoji": "👩‍👧‍👧"},
    {"word": "speaking head", "emoji": "🗣️"},
    {"word": "bust in silhouette", "emoji": "👤"},
    {"word": "busts in silhouette", "emoji": "👥"},
    {"word": "people hugging", "emoji": "🫂"},
    {"word": "family", "emoji": "👪"},
    {"word": "family adult, adult, child", "emoji": "🧑‍🧑‍🧒"},
    {"word": "family adult, adult, child, child", "emoji": "🧑‍🧑‍🧒‍🧒"},
    {"word": "family adult, child", "emoji": "🧑‍🧒"},
    {"word": "family adult, child, child", "emoji": "🧑‍🧒‍🧒"},
    {"word": "footprints", "emoji": "👣"},
    {"word": "fingerprint", "emoji": "🫆"},
    {"word": "monkey face", "emoji": "🐵"},
    {"word": "monkey", "emoji": "🐒"},
    {"word": "gorilla", "emoji": "🦍"},
    {"word": "orangutan", "emoji": "🦧"},
    {"word": "dog face", "emoji": "🐶"},
    {"word": "dog", "emoji": "🐕"},
    {"word": "guide dog", "emoji": "🦮"},
    {"word": "service dog", "emoji": "🐕‍🦺"},
    {"word": "poodle", "emoji": "🐩"},
    {"word": "wolf", "emoji": "🐺"},
    {"word": "fox", "emoji": "🦊"},
    {"word": "raccoon", "emoji": "🦝"},
    {"word": "cat face", "emoji": "🐱"},
    {"word": "cat", "emoji": "🐈"},
    {"word": "black cat", "emoji": "🐈‍⬛"},
    {"word": "lion", "emoji": "🦁"},
    {"word": "tiger face", "emoji": "🐯"},
    {"word": "tiger", "emoji": "🐅"},
    {"word": "leopard", "emoji": "🐆"},
    {"word": "horse face", "emoji": "🐴"},
    {"word": "moose", "emoji": "🫎"},
    {"word": "donkey", "emoji": "🫏"},
    {"word": "horse", "emoji": "🐎"},
    {"word": "unicorn", "emoji": "🦄"},
    {"word": "zebra", "emoji": "🦓"},
    {"word": "deer", "emoji": "🦌"},
    {"word": "bison", "emoji": "🦬"},
    {"word": "cow face", "emoji": "🐮"},
    {"word": "ox", "emoji": "🐂"},
    {"word": "water buffalo", "emoji": "🐃"},
    {"word": "cow", "emoji": "🐄"},
    {"word": "pig face", "emoji": "🐷"},
    {"word": "pig", "emoji": "🐖"},
    {"word": "boar", "emoji": "🐗"},
    {"word": "pig nose", "emoji": "🐽"},
    {"word": "ram", "emoji": "🐏"},
    {"word": "ewe", "emoji": "🐑"},
    {"word": "goat", "emoji": "🐐"},
    {"word": "camel", "emoji": "🐪"},
    {"word": "two-hump camel", "emoji": "🐫"},
    {"word": "llama", "emoji": "🦙"},
    {"word": "giraffe", "emoji": "🦒"},
    {"word": "elephant", "emoji": "🐘"},
    {"word": "mammoth", "emoji": "🦣"},
    {"word": "rhinoceros", "emoji": "🦏"},
    {"word": "hippopotamus", "emoji": "🦛"},
    {"word": "mouse face", "emoji": "🐭"},
    {"word": "mouse", "emoji": "🐁"},
    {"word": "rat", "emoji": "🐀"},
    {"word": "hamster", "emoji": "🐹"},
    {"word": "rabbit face", "emoji": "🐰"},
    {"word": "rabbit", "emoji": "🐇"},
    {"word": "chipmunk", "emoji": "🐿️"},
    {"word": "beaver", "emoji": "🦫"},
    {"word": "hedgehog", "emoji": "🦔"},
    {"word": "bat", "emoji": "🦇"},
    {"word": "bear", "emoji": "🐻"},
    {"word": "polar bear", "emoji": "🐻‍❄️"},
    {"word": "koala", "emoji": "🐨"},
    {"word": "panda", "emoji": "🐼"},
    {"word": "sloth", "emoji": "🦥"},
    {"word": "otter", "emoji": "🦦"},
    {"word": "skunk", "emoji": "🦨"},
    {"word": "kangaroo", "emoji": "🦘"},
    {"word": "badger", "emoji": "🦡"},
    {"word": "paw prints", "emoji": "🐾"},
    {"word": "turkey", "emoji": "🦃"},
    {"word": "chicken", "emoji": "🐔"},
    {"word": "rooster", "emoji": "🐓"},
    {"word": "hatching chick", "emoji": "🐣"},
    {"word": "baby chick", "emoji": "🐤"},
    {"word": "front-facing baby chick", "emoji": "🐥"},
    {"word": "bird", "emoji": "🐦"},
    {"word": "penguin", "emoji": "🐧"},
    {"word": "dove", "emoji": "🕊️"},
    {"word": "eagle", "emoji": "🦅"},
    {"word": "duck", "emoji": "🦆"},
    {"word": "swan", "emoji": "🦢"},
    {"word": "owl", "emoji": "🦉"},
    {"word": "dodo", "emoji": "🦤"},
    {"word": "feather", "emoji": "🪶"},
    {"word": "flamingo", "emoji": "🦩"},
    {"word": "peacock", "emoji": "🦚"},
    {"word": "parrot", "emoji": "🦜"},
    {"word": "wing", "emoji": "🪽"},
    {"word": "black bird", "emoji": "🐦‍⬛"},
    {"word": "goose", "emoji": "🪿"},
    {"word": "phoenix", "emoji": "🐦‍🔥"},
    {"word": "frog", "emoji": "🐸"},
    {"word": "crocodile", "emoji": "🐊"},
    {"word": "turtle", "emoji": "🐢"},
    {"word": "lizard", "emoji": "🦎"},
    {"word": "snake", "emoji": "🐍"},
    {"word": "dragon face", "emoji": "🐲"},
    {"word": "dragon", "emoji": "🐉"},
    {"word": "sauropod", "emoji": "🦕"},
    {"word": "t-rex", "emoji": "🦖"},
    {"word": "spouting whale", "emoji": "🐳"},
    {"word": "whale", "emoji": "🐋"},
    {"word": "dolphin", "emoji": "🐬"},
    {"word": "orca", "emoji": "🫍"},
    {"word": "seal", "emoji": "🦭"},
    {"word": "fish", "emoji": "🐟"},
    {"word": "tropical fish", "emoji": "🐠"},
    {"word": "blowfish", "emoji": "🐡"},
    {"word": "shark", "emoji": "🦈"},
    {"word": "octopus", "emoji": "🐙"},
    {"word": "spiral shell", "emoji": "🐚"},
    {"word": "coral", "emoji": "🪸"},
    {"word": "jellyfish", "emoji": "🪼"},
    {"word": "crab", "emoji": "🦀"},
    {"word": "lobster", "emoji": "🦞"},
    {"word": "shrimp", "emoji": "🦐"},
    {"word": "squid", "emoji": "🦑"},
    {"word": "oyster", "emoji": "🦪"},
    {"word": "snail", "emoji": "🐌"},
    {"word": "butterfly", "emoji": "🦋"},
    {"word": "bug", "emoji": "🐛"},
    {"word": "ant", "emoji": "🐜"},
    {"word": "honeybee", "emoji": "🐝"},
    {"word": "beetle", "emoji": "🪲"},
    {"word": "lady beetle", "emoji": "🐞"},
    {"word": "cricket", "emoji": "🦗"},
    {"word": "cockroach", "emoji": "🪳"},
    {"word": "spider", "emoji": "🕷️"},
    {"word": "spider web", "emoji": "🕸️"},
    {"word": "scorpion", "emoji": "🦂"},
    {"word": "mosquito", "emoji": "🦟"},
    {"word": "fly", "emoji": "🪰"},
    {"word": "worm", "emoji": "🪱"},
    {"word": "microbe", "emoji": "🦠"},
    {"word": "bouquet", "emoji": "💐"},
    {"word": "cherry blossom", "emoji": "🌸"},
    {"word": "white flower", "emoji": "💮"},
    {"word": "lotus", "emoji": "🪷"},
    {"word": "rosette", "emoji": "🏵️"},
    {"word": "rose", "emoji": "🌹"},
    {"word": "wilted flower", "emoji": "🥀"},
    {"word": "hibiscus", "emoji": "🌺"},
    {"word": "sunflower", "emoji": "🌻"},
    {"word": "blossom", "emoji": "🌼"},
    {"word": "tulip", "emoji": "🌷"},
    {"word": "hyacinth", "emoji": "🪻"},
    {"word": "seedling", "emoji": "🌱"},
    {"word": "potted plant", "emoji": "🪴"},
    {"word": "evergreen tree", "emoji": "🌲"},
    {"word": "deciduous tree", "emoji": "🌳"},
    {"word": "palm tree", "emoji": "🌴"},
    {"word": "cactus", "emoji": "🌵"},
    {"word": "sheaf of rice", "emoji": "🌾"},
    {"word": "herb", "emoji": "🌿"},
    {"word": "shamrock", "emoji": "☘️"},
    {"word": "four leaf clover", "emoji": "🍀"},
    {"word": "maple leaf", "emoji": "🍁"},
    {"word": "fallen leaf", "emoji": "🍂"},
    {"word": "leaf fluttering in wind", "emoji": "🍃"},
    {"word": "empty nest", "emoji": "🪹"},
    {"word": "nest with eggs", "emoji": "🪺"},
    {"word": "mushroom", "emoji": "🍄"},
    {"word": "leafless tree", "emoji": "🪾"},
    {"word": "grapes", "emoji": "🍇"},
    {"word": "melon", "emoji": "🍈"},
    {"word": "watermelon", "emoji": "🍉"},
    {"word": "tangerine", "emoji": "🍊"},
    {"word": "lemon", "emoji": "🍋"},
    {"word": "lime", "emoji": "🍋‍🟩"},
    {"word": "banana", "emoji": "🍌"},
    {"word": "pineapple", "emoji": "🍍"},
    {"word": "mango", "emoji": "🥭"},
    {"word": "red apple", "emoji": "🍎"},
    {"word": "green apple", "emoji": "🍏"},
    {"word": "pear", "emoji": "🍐"},
    {"word": "peach", "emoji": "🍑"},
    {"word": "cherries", "emoji": "🍒"},
    {"word": "strawberry", "emoji": "🍓"},
    {"word": "blueberries", "emoji": "🫐"},
    {"word": "kiwi fruit", "emoji": "🥝"},
    {"word": "tomato", "emoji": "🍅"},
    {"word": "olive", "emoji": "🫒"},
    {"word": "coconut", "emoji": "🥥"},
    {"word": "avocado", "emoji": "🥑"},
    {"word": "eggplant", "emoji": "🍆"},
    {"word": "potato", "emoji": "🥔"},
    {"word": "carrot", "emoji": "🥕"},
    {"word": "ear of corn", "emoji": "🌽"},
    {"word": "hot pepper", "emoji": "🌶️"},
    {"word": "bell pepper", "emoji": "🫑"},
    {"word": "cucumber", "emoji": "🥒"},
    {"word": "leafy green", "emoji": "🥬"},
    {"word": "broccoli", "emoji": "🥦"},
    {"word": "garlic", "emoji": "🧄"},
    {"word": "onion", "emoji": "🧅"},
    {"word": "peanuts", "emoji": "🥜"},
    {"word": "beans", "emoji": "🫘"},
    {"word": "chestnut", "emoji": "🌰"},
    {"word": "ginger root", "emoji": "🫚"},
    {"word": "pea pod", "emoji": "🫛"},
    {"word": "brown mushroom", "emoji": "🍄‍🟫"},
    {"word": "root vegetable", "emoji": "🫜"},
    {"word": "bread", "emoji": "🍞"},
    {"word": "croissant", "emoji": "🥐"},
    {"word": "baguette bread", "emoji": "🥖"},
    {"word": "flatbread", "emoji": "🫓"},
    {"word": "pretzel", "emoji": "🥨"},
    {"word": "bagel", "emoji": "🥯"},
    {"word": "pancakes", "emoji": "🥞"},
    {"word": "waffle", "emoji": "🧇"},
    {"word": "cheese wedge", "emoji": "🧀"},
    {"word": "meat on bone", "emoji": "🍖"},
    {"word": "poultry leg", "emoji": "🍗"},
    {"word": "cut of meat", "emoji": "🥩"},
    {"word": "bacon", "emoji": "🥓"},
    {"word": "hamburger", "emoji": "🍔"},
    {"word": "french fries", "emoji": "🍟"},
    {"word": "pizza", "emoji": "🍕"},
    {"word": "hot dog", "emoji": "🌭"},
    {"word": "sandwich", "emoji": "🥪"},
    {"word": "taco", "emoji": "🌮"},
    {"word": "burrito", "emoji": "🌯"},
    {"word": "tamale", "emoji": "🫔"},
    {"word": "stuffed flatbread", "emoji": "🥙"},
    {"word": "falafel", "emoji": "🧆"},
    {"word": "egg", "emoji": "🥚"},
    {"word": "cooking", "emoji": "🍳"},
    {"word": "shallow pan of food", "emoji": "🥘"},
    {"word": "pot of food", "emoji": "🍲"},
    {"word": "fondue", "emoji": "🫕"},
    {"word": "bowl with spoon", "emoji": "🥣"},
    {"word": "green salad", "emoji": "🥗"},
    {"word": "popcorn", "emoji": "🍿"},
    {"word": "butter", "emoji": "🧈"},
    {"word": "salt", "emoji": "🧂"},
    {"word": "canned food", "emoji": "🥫"},
    {"word": "bento box", "emoji": "🍱"},

    // この辺でスレッド移行

    {"word": "rice cracker", "emoji": "🍘"},
    {"word": "rice ball", "emoji": "🍙"},
    {"word": "cooked rice", "emoji": "🍚"},
    {"word": "curry rice", "emoji": "🍛"},
    {"word": "steaming bowl", "emoji": "🍜"},
    {"word": "spaghetti", "emoji": "🍝"},
    {"word": "roasted sweet potato", "emoji": "🍠"},
    {"word": "oden", "emoji": "🍢"},
    {"word": "sushi", "emoji": "🍣"},
    {"word": "fried shrimp", "emoji": "🍤"},
    {"word": "fish cake with swirl", "emoji": "🍥"},
    {"word": "moon cake", "emoji": "🥮"},
    {"word": "dango", "emoji": "🍡"},
    {"word": "dumpling", "emoji": "🥟"},
    {"word": "fortune cookie", "emoji": "🥠"},
    {"word": "takeout box", "emoji": "🥡"},
    {"word": "soft ice cream", "emoji": "🍦"},
    {"word": "shaved ice", "emoji": "🍧"},
    {"word": "ice cream", "emoji": "🍨"},
    {"word": "doughnut", "emoji": "🍩"},
    {"word": "cookie", "emoji": "🍪"},
    {"word": "birthday cake", "emoji": "🎂"},
    {"word": "shortcake", "emoji": "🍰"},
    {"word": "cupcake", "emoji": "🧁"},
    {"word": "pie", "emoji": "🥧"},
    {"word": "chocolate bar", "emoji": "🍫"},
    {"word": "candy", "emoji": "🍬"},
    {"word": "lollipop", "emoji": "🍭"},
    {"word": "custard", "emoji": "🍮"},
    {"word": "honey pot", "emoji": "🍯"},
    {"word": "baby bottle", "emoji": "🍼"},
    {"word": "glass of milk", "emoji": "🥛"},
    {"word": "hot beverage", "emoji": "☕"},
    {"word": "teapot", "emoji": "🫖"},
    {"word": "teacup without handle", "emoji": "🍵"},
    {"word": "sake", "emoji": "🍶"},
    {"word": "bottle with popping cork", "emoji": "🍾"},
    {"word": "wine glass", "emoji": "🍷"},
    {"word": "cocktail glass", "emoji": "🍸"},
    {"word": "tropical drink", "emoji": "🍹"},
    {"word": "beer mug", "emoji": "🍺"},
    {"word": "clinking beer mugs", "emoji": "🍻"},
    {"word": "clinking glasses", "emoji": "🥂"},
    {"word": "tumbler glass", "emoji": "🥃"},
    {"word": "pouring liquid", "emoji": "🫗"},
    {"word": "cup with straw", "emoji": "🥤"},
    {"word": "bubble tea", "emoji": "🧋"},
    {"word": "beverage box", "emoji": "🧃"},
    {"word": "mate", "emoji": "🧉"},
    {"word": "ice", "emoji": "🧊"},
    {"word": "chopsticks", "emoji": "🥢"},
    {"word": "fork and knife with plate", "emoji": "🍽️"},
    {"word": "fork and knife", "emoji": "🍴"},
    {"word": "spoon", "emoji": "🥄"},
    {"word": "kitchen knife", "emoji": "🔪"},
    {"word": "jar", "emoji": "🫙"},
    {"word": "amphora", "emoji": "🏺"},
    {"word": "globe showing europe-africa", "emoji": "🌍"},
    {"word": "globe showing americas", "emoji": "🌎"},
    {"word": "globe showing asia-australia", "emoji": "🌏"},
    {"word": "globe with meridians", "emoji": "🌐"},
    {"word": "world map", "emoji": "🗺️"},
    {"word": "map of japan", "emoji": "🗾"},
    {"word": "compass", "emoji": "🧭"},
    {"word": "snow-capped mountain", "emoji": "🏔️"},
    {"word": "mountain", "emoji": "⛰️"},
    {"word": "landslide", "emoji": "🛘"},
    {"word": "volcano", "emoji": "🌋"},
    {"word": "mount fuji", "emoji": "🗻"},
    {"word": "camping", "emoji": "🏕️"},
    {"word": "beach with umbrella", "emoji": "🏖️"},
    {"word": "desert", "emoji": "🏜️"},
    {"word": "desert island", "emoji": "🏝️"},
    {"word": "national park", "emoji": "🏞️"},
    {"word": "stadium", "emoji": "🏟️"},
    {"word": "classical building", "emoji": "🏛️"},
    {"word": "building construction", "emoji": "🏗️"},
    {"word": "brick", "emoji": "🧱"},
    {"word": "rock", "emoji": "🪨"},
    {"word": "wood", "emoji": "🪵"},
    {"word": "hut", "emoji": "🛖"},
    {"word": "houses", "emoji": "🏘️"},
    {"word": "derelict house", "emoji": "🏚️"},
    {"word": "house", "emoji": "🏠"},
    {"word": "house with garden", "emoji": "🏡"},
    {"word": "office building", "emoji": "🏢"},
    {"word": "japanese post office", "emoji": "🏣"},
    {"word": "post office", "emoji": "🏤"},
    {"word": "hospital", "emoji": "🏥"},
    {"word": "bank", "emoji": "🏦"},
    {"word": "hotel", "emoji": "🏨"},
    {"word": "love hotel", "emoji": "🏩"},
    {"word": "convenience store", "emoji": "🏪"},
    {"word": "school", "emoji": "🏫"},
    {"word": "department store", "emoji": "🏬"},
    {"word": "factory", "emoji": "🏭"},
    {"word": "japanese castle", "emoji": "🏯"},
    {"word": "castle", "emoji": "🏰"},
    {"word": "wedding", "emoji": "💒"},
    {"word": "tokyo tower", "emoji": "🗼"},
    {"word": "statue of liberty", "emoji": "🗽"},
    {"word": "church", "emoji": "⛪"},
    {"word": "mosque", "emoji": "🕌"},
    {"word": "hindu temple", "emoji": "🛕"},
    {"word": "synagogue", "emoji": "🕍"},
    {"word": "shinto shrine", "emoji": "⛩️"},
    {"word": "kaaba", "emoji": "🕋"},
    {"word": "fountain", "emoji": "⛲"},
    {"word": "tent", "emoji": "⛺"},
    {"word": "foggy", "emoji": "🌁"},
    {"word": "night with stars", "emoji": "🌃"},
    {"word": "cityscape", "emoji": "🏙️"},
    {"word": "sunrise over mountains", "emoji": "🌄"},
    {"word": "sunrise", "emoji": "🌅"},
    {"word": "cityscape at dusk", "emoji": "🌆"},
    {"word": "sunset", "emoji": "🌇"},
    {"word": "bridge at night", "emoji": "🌉"},
    {"word": "hot springs", "emoji": "♨️"},
    {"word": "carousel horse", "emoji": "🎠"},
    {"word": "playground slide", "emoji": "🛝"},
    {"word": "ferris wheel", "emoji": "🎡"},
    {"word": "roller coaster", "emoji": "🎢"},
    {"word": "barber pole", "emoji": "💈"},
    {"word": "circus tent", "emoji": "🎪"},
    {"word": "locomotive", "emoji": "🚂"},
    {"word": "railway car", "emoji": "🚃"},
    {"word": "high-speed train", "emoji": "🚄"},
    {"word": "bullet train", "emoji": "🚅"},
    {"word": "train", "emoji": "🚆"},
    {"word": "metro", "emoji": "🚇"},
    {"word": "light rail", "emoji": "🚈"},
    {"word": "station", "emoji": "🚉"},
    {"word": "tram", "emoji": "🚊"},
    {"word": "monorail", "emoji": "🚝"},
    {"word": "mountain railway", "emoji": "🚞"},
    {"word": "tram car", "emoji": "🚋"},
    {"word": "bus", "emoji": "🚌"},
    {"word": "oncoming bus", "emoji": "🚍"},
    {"word": "trolleybus", "emoji": "🚎"},
    {"word": "minibus", "emoji": "🚐"},
    {"word": "ambulance", "emoji": "🚑"},
    {"word": "fire engine", "emoji": "🚒"},
    {"word": "police car", "emoji": "🚓"},
    {"word": "oncoming police car", "emoji": "🚔"},
    {"word": "taxi", "emoji": "🚕"},
    {"word": "oncoming taxi", "emoji": "🚖"},
    {"word": "automobile", "emoji": "🚗"},
    {"word": "oncoming automobile", "emoji": "🚘"},
    {"word": "sport utility vehicle", "emoji": "🚙"},
    {"word": "pickup truck", "emoji": "🛻"},
    {"word": "delivery truck", "emoji": "🚚"},
    {"word": "articulated lorry", "emoji": "🚛"},
    {"word": "tractor", "emoji": "🚜"},
    {"word": "racing car", "emoji": "🏎️"},
    {"word": "motorcycle", "emoji": "🏍️"},
    {"word": "motor scooter", "emoji": "🛵"},
    {"word": "manual wheelchair", "emoji": "🦽"},
    {"word": "motorized wheelchair", "emoji": "🦼"},
    {"word": "auto rickshaw", "emoji": "🛺"},
    {"word": "bicycle", "emoji": "🚲"},
    {"word": "kick scooter", "emoji": "🛴"},
    {"word": "skateboard", "emoji": "🛹"},
    {"word": "roller skate", "emoji": "🛼"},
    {"word": "bus stop", "emoji": "🚏"},
    {"word": "motorway", "emoji": "🛣️"},
    {"word": "railway track", "emoji": "🛤️"},
    {"word": "oil drum", "emoji": "🛢️"},
    {"word": "fuel pump", "emoji": "⛽"},
    {"word": "wheel", "emoji": "🛞"},
    {"word": "police car light", "emoji": "🚨"},
    {"word": "horizontal traffic light", "emoji": "🚥"},
    {"word": "vertical traffic light", "emoji": "🚦"},
    {"word": "stop sign", "emoji": "🛑"},
    {"word": "construction", "emoji": "🚧"},
    {"word": "anchor", "emoji": "⚓"},
    {"word": "ring buoy", "emoji": "🛟"},
    {"word": "sailboat", "emoji": "⛵"},
    {"word": "canoe", "emoji": "🛶"},
    {"word": "speedboat", "emoji": "🚤"},
    {"word": "passenger ship", "emoji": "🛳️"},
    {"word": "ferry", "emoji": "⛴️"},
    {"word": "motor boat", "emoji": "🛥️"},
    {"word": "ship", "emoji": "🚢"},
    {"word": "airplane", "emoji": "✈️"},
    {"word": "small airplane", "emoji": "🛩️"},
    {"word": "airplane departure", "emoji": "🛫"},
    {"word": "airplane arrival", "emoji": "🛬"},
    {"word": "parachute", "emoji": "🪂"},
    {"word": "seat", "emoji": "💺"},
    {"word": "helicopter", "emoji": "🚁"},
    {"word": "suspension railway", "emoji": "🚟"},
    {"word": "mountain cableway", "emoji": "🚠"},
    {"word": "aerial tramway", "emoji": "🚡"},
    {"word": "satellite", "emoji": "🛰️"},
    {"word": "rocket", "emoji": "🚀"},
    {"word": "flying saucer", "emoji": "🛸"},
    {"word": "bellhop bell", "emoji": "🛎️"},
    {"word": "luggage", "emoji": "🧳"},
    {"word": "hourglass done", "emoji": "⌛"},
    {"word": "hourglass not done", "emoji": "⏳"},
    {"word": "watch", "emoji": "⌚"},
    {"word": "alarm clock", "emoji": "⏰"},
    {"word": "stopwatch", "emoji": "⏱️"},
    {"word": "timer clock", "emoji": "⏲️"},
    {"word": "mantelpiece clock", "emoji": "🕰️"},
    {"word": "twelve o’clock", "emoji": "🕛"},
    {"word": "twelve-thirty", "emoji": "🕧"},
    {"word": "one o’clock", "emoji": "🕐"},
    {"word": "one-thirty", "emoji": "🕜"},
    {"word": "two o’clock", "emoji": "🕑"},
    {"word": "two-thirty", "emoji": "🕝"},
    {"word": "three o’clock", "emoji": "🕒"},
    {"word": "three-thirty", "emoji": "🕞"},
    {"word": "four o’clock", "emoji": "🕓"},
    {"word": "four-thirty", "emoji": "🕟"},
    {"word": "five o’clock", "emoji": "🕔"},
    {"word": "five-thirty", "emoji": "🕠"},
    {"word": "six o’clock", "emoji": "🕕"},
    {"word": "six-thirty", "emoji": "🕡"},
    {"word": "seven o’clock", "emoji": "🕖"},
    {"word": "seven-thirty", "emoji": "🕢"},
    {"word": "eight o’clock", "emoji": "🕗"},
    {"word": "eight-thirty", "emoji": "🕣"},
    {"word": "nine o’clock", "emoji": "🕘"},
    {"word": "nine-thirty", "emoji": "🕤"},
    {"word": "ten o’clock", "emoji": "🕙"},
    {"word": "ten-thirty", "emoji": "🕥"},
    {"word": "eleven o’clock", "emoji": "🕚"},
    {"word": "eleven-thirty", "emoji": "🕦"},
    {"word": "new moon", "emoji": "🌑"},
    {"word": "waxing crescent moon", "emoji": "🌒"},
    {"word": "first quarter moon", "emoji": "🌓"},
    {"word": "waxing gibbous moon", "emoji": "🌔"},
    {"word": "full moon", "emoji": "🌕"},
    {"word": "waning gibbous moon", "emoji": "🌖"},
    {"word": "last quarter moon", "emoji": "🌗"},
    {"word": "waning crescent moon", "emoji": "🌘"},
    {"word": "crescent moon", "emoji": "🌙"},
    {"word": "new moon face", "emoji": "🌚"},
    {"word": "first quarter moon face", "emoji": "🌛"},
    {"word": "last quarter moon face", "emoji": "🌜"},
    {"word": "thermometer", "emoji": "🌡️"},
    {"word": "sun", "emoji": "☀️"},
    {"word": "full moon face", "emoji": "🌝"},
    {"word": "sun with face", "emoji": "🌞"},
    {"word": "ringed planet", "emoji": "🪐"},
    {"word": "star", "emoji": "⭐"},
    {"word": "glowing star", "emoji": "🌟"},
    {"word": "shooting star", "emoji": "🌠"},
    {"word": "milky way", "emoji": "🌌"},
    {"word": "cloud", "emoji": "☁️"},
    {"word": "sun behind cloud", "emoji": "⛅"},
    {"word": "cloud with lightning and rain", "emoji": "⛈️"},
    {"word": "sun behind small cloud", "emoji": "🌤️"},
    {"word": "sun behind large cloud", "emoji": "🌥️"},
    {"word": "sun behind rain cloud", "emoji": "🌦️"},
    {"word": "cloud with rain", "emoji": "🌧️"},
    {"word": "cloud with snow", "emoji": "🌨️"},
    {"word": "cloud with lightning", "emoji": "🌩️"},
    {"word": "tornado", "emoji": "🌪️"},
    {"word": "fog", "emoji": "🌫️"},
    {"word": "wind face", "emoji": "🌬️"},
    {"word": "cyclone", "emoji": "🌀"},
    {"word": "rainbow", "emoji": "🌈"},
    {"word": "closed umbrella", "emoji": "🌂"},
    {"word": "umbrella", "emoji": "☂️"},
    {"word": "umbrella with rain drops", "emoji": "☔"},
    {"word": "umbrella on ground", "emoji": "⛱️"},
    {"word": "high voltage", "emoji": "⚡"},
    {"word": "snowflake", "emoji": "❄️"},
    {"word": "snowman", "emoji": "☃️"},
    {"word": "snowman without snow", "emoji": "⛄"},
    {"word": "comet", "emoji": "☄️"},
    {"word": "fire", "emoji": "🔥"},
    {"word": "droplet", "emoji": "💧"},
    {"word": "water wave", "emoji": "🌊"},
    {"word": "jack-o-lantern", "emoji": "🎃"},
    {"word": "christmas tree", "emoji": "🎄"},
    {"word": "fireworks", "emoji": "🎆"},
    {"word": "sparkler", "emoji": "🎇"},
    {"word": "firecracker", "emoji": "🧨"},
    {"word": "sparkles", "emoji": "✨"},
    {"word": "balloon", "emoji": "🎈"},
    {"word": "party popper", "emoji": "🎉"},
    {"word": "confetti ball", "emoji": "🎊"},
    {"word": "tanabata tree", "emoji": "🎋"},
    {"word": "pine decoration", "emoji": "🎍"},
    {"word": "japanese dolls", "emoji": "🎎"},
    {"word": "carp streamer", "emoji": "🎏"},
    {"word": "wind chime", "emoji": "🎐"},
    {"word": "moon viewing ceremony", "emoji": "🎑"},
    {"word": "red envelope", "emoji": "🧧"},
    {"word": "ribbon", "emoji": "🎀"},
    {"word": "wrapped gift", "emoji": "🎁"},
    {"word": "reminder ribbon", "emoji": "🎗️"},
    {"word": "admission tickets", "emoji": "🎟️"},
    {"word": "ticket", "emoji": "🎫"},
    {"word": "military medal", "emoji": "🎖️"},
    {"word": "trophy", "emoji": "🏆"},
    {"word": "sports medal", "emoji": "🏅"},
    {"word": "1st place medal", "emoji": "🥇"},
    {"word": "2nd place medal", "emoji": "🥈"},
    {"word": "3rd place medal", "emoji": "🥉"},
    {"word": "soccer ball", "emoji": "⚽"},
    {"word": "baseball", "emoji": "⚾"},
    {"word": "softball", "emoji": "🥎"},
    {"word": "basketball", "emoji": "🏀"},
    {"word": "volleyball", "emoji": "🏐"},
    {"word": "american football", "emoji": "🏈"},
    {"word": "rugby football", "emoji": "🏉"},
    {"word": "tennis", "emoji": "🎾"},
    {"word": "flying disc", "emoji": "🥏"},
    {"word": "bowling", "emoji": "🎳"},
    {"word": "cricket game", "emoji": "🏏"},
    {"word": "field hockey", "emoji": "🏑"},
    {"word": "ice hockey", "emoji": "🏒"},
    {"word": "lacrosse", "emoji": "🥍"},
    {"word": "ping pong", "emoji": "🏓"},
    {"word": "badminton", "emoji": "🏸"},
    {"word": "boxing glove", "emoji": "🥊"},
    {"word": "martial arts uniform", "emoji": "🥋"},
    {"word": "goal net", "emoji": "🥅"},
    {"word": "flag in hole", "emoji": "⛳"},
    {"word": "ice skate", "emoji": "⛸️"},
    {"word": "fishing pole", "emoji": "🎣"},
    {"word": "diving mask", "emoji": "🤿"},
    {"word": "running shirt", "emoji": "🎽"},
    {"word": "skis", "emoji": "🎿"},
    {"word": "sled", "emoji": "🛷"},
    {"word": "curling stone", "emoji": "🥌"},
    {"word": "bullseye", "emoji": "🎯"},
    {"word": "yo-yo", "emoji": "🪀"},
    {"word": "kite", "emoji": "🪁"},
    {"word": "water pistol", "emoji": "🔫"},
    {"word": "pool 8 ball", "emoji": "🎱"},
    {"word": "crystal ball", "emoji": "🔮"},
    {"word": "magic wand", "emoji": "🪄"},
    {"word": "video game", "emoji": "🎮"},
    {"word": "joystick", "emoji": "🕹️"},
    {"word": "slot machine", "emoji": "🎰"},
    {"word": "game die", "emoji": "🎲"},
    {"word": "puzzle piece", "emoji": "🧩"},
    {"word": "teddy bear", "emoji": "🧸"},
    {"word": "piñata", "emoji": "🪅"},
    {"word": "mirror ball", "emoji": "🪩"},
    {"word": "nesting dolls", "emoji": "🪆"},
    {"word": "spade suit", "emoji": "♠️"},

    // この辺でスレッド移行

    {"word": "heart suit", "emoji": "♥️"},
    {"word": "diamond suit", "emoji": "♦️"},
    {"word": "club suit", "emoji": "♣️"},
    {"word": "chess pawn", "emoji": "♟️"},
    {"word": "joker", "emoji": "🃏"},
    {"word": "mahjong red dragon", "emoji": "🀄"},
    {"word": "flower playing cards", "emoji": "🎴"},
    {"word": "performing arts", "emoji": "🎭"},
    {"word": "framed picture", "emoji": "🖼️"},
    {"word": "artist palette", "emoji": "🎨"},
    {"word": "thread", "emoji": "🧵"},
    {"word": "sewing needle", "emoji": "🪡"},
    {"word": "yarn", "emoji": "🧶"},
    {"word": "knot", "emoji": "🪢"},
    {"word": "glasses", "emoji": "👓"},
    {"word": "sunglasses", "emoji": "🕶️"},
    {"word": "goggles", "emoji": "🥽"},
    {"word": "lab coat", "emoji": "🥼"},
    {"word": "safety vest", "emoji": "🦺"},
    {"word": "necktie", "emoji": "👔"},
    {"word": "t-shirt", "emoji": "👕"},
    {"word": "jeans", "emoji": "👖"},
    {"word": "scarf", "emoji": "🧣"},
    {"word": "gloves", "emoji": "🧤"},
    {"word": "coat", "emoji": "🧥"},
    {"word": "socks", "emoji": "🧦"},
    {"word": "dress", "emoji": "👗"},
    {"word": "kimono", "emoji": "👘"},
    {"word": "sari", "emoji": "🥻"},
    {"word": "one-piece swimsuit", "emoji": "🩱"},
    {"word": "briefs", "emoji": "🩲"},
    {"word": "shorts", "emoji": "🩳"},
    {"word": "bikini", "emoji": "👙"},
    {"word": "woman’s clothes", "emoji": "👚"},
    {"word": "folding hand fan", "emoji": "🪭"},
    {"word": "purse", "emoji": "👛"},
    {"word": "handbag", "emoji": "👜"},
    {"word": "clutch bag", "emoji": "👝"},
    {"word": "shopping bags", "emoji": "🛍️"},
    {"word": "backpack", "emoji": "🎒"},
    {"word": "thong sandal", "emoji": "🩴"},
    {"word": "man’s shoe", "emoji": "👞"},
    {"word": "running shoe", "emoji": "👟"},
    {"word": "hiking boot", "emoji": "🥾"},
    {"word": "flat shoe", "emoji": "🥿"},
    {"word": "high-heeled shoe", "emoji": "👠"},
    {"word": "woman’s sandal", "emoji": "👡"},
    {"word": "ballet shoes", "emoji": "🩰"},
    {"word": "woman’s boot", "emoji": "👢"},
    {"word": "hair pick", "emoji": "🪮"},
    {"word": "crown", "emoji": "👑"},
    {"word": "woman’s hat", "emoji": "👒"},
    {"word": "top hat", "emoji": "🎩"},
    {"word": "graduation cap", "emoji": "🎓"},
    {"word": "billed cap", "emoji": "🧢"},
    {"word": "military helmet", "emoji": "🪖"},
    {"word": "rescue worker’s helmet", "emoji": "⛑️"},
    {"word": "prayer beads", "emoji": "📿"},
    {"word": "lipstick", "emoji": "💄"},
    {"word": "ring", "emoji": "💍"},
    {"word": "gem stone", "emoji": "💎"},
    {"word": "muted speaker", "emoji": "🔇"},
    {"word": "speaker low volume", "emoji": "🔈"},
    {"word": "speaker medium volume", "emoji": "🔉"},
    {"word": "speaker high volume", "emoji": "🔊"},
    {"word": "loudspeaker", "emoji": "📢"},
    {"word": "megaphone", "emoji": "📣"},
    {"word": "postal horn", "emoji": "📯"},
    {"word": "bell", "emoji": "🔔"},
    {"word": "bell with slash", "emoji": "🔕"},
    {"word": "musical score", "emoji": "🎼"},
    {"word": "musical note", "emoji": "🎵"},
    {"word": "musical notes", "emoji": "🎶"},
    {"word": "studio microphone", "emoji": "🎙️"},
    {"word": "level slider", "emoji": "🎚️"},
    {"word": "control knobs", "emoji": "🎛️"},
    {"word": "microphone", "emoji": "🎤"},
    {"word": "headphone", "emoji": "🎧"},
    {"word": "radio", "emoji": "📻"},
    {"word": "saxophone", "emoji": "🎷"},
    {"word": "trumpet", "emoji": "🎺"},
    {"word": "trombone", "emoji": "🪊"},
    {"word": "accordion", "emoji": "🪗"},
    {"word": "guitar", "emoji": "🎸"},
    {"word": "musical keyboard", "emoji": "🎹"},
    {"word": "violin", "emoji": "🎻"},
    {"word": "banjo", "emoji": "🪕"},
    {"word": "drum", "emoji": "🥁"},
    {"word": "long drum", "emoji": "🪘"},
    {"word": "maracas", "emoji": "🪇"},
    {"word": "flute", "emoji": "🪈"},
    {"word": "harp", "emoji": "🪉"},
    {"word": "mobile phone", "emoji": "📱"},
    {"word": "mobile phone with arrow", "emoji": "📲"},
    {"word": "telephone", "emoji": "☎️"},
    {"word": "telephone receiver", "emoji": "📞"},
    {"word": "pager", "emoji": "📟"},
    {"word": "fax machine", "emoji": "📠"},
    {"word": "battery", "emoji": "🔋"},
    {"word": "low battery", "emoji": "🪫"},
    {"word": "electric plug", "emoji": "🔌"},
    {"word": "laptop", "emoji": "💻"},
    {"word": "desktop computer", "emoji": "🖥️"},
    {"word": "printer", "emoji": "🖨️"},
    {"word": "keyboard", "emoji": "⌨️"},
    {"word": "computer mouse", "emoji": "🖱️"},
    {"word": "trackball", "emoji": "🖲️"},
    {"word": "computer disk", "emoji": "💽"},
    {"word": "floppy disk", "emoji": "💾"},
    {"word": "optical disk", "emoji": "💿"},
    {"word": "dvd", "emoji": "📀"},
    {"word": "abacus", "emoji": "🧮"},
    {"word": "movie camera", "emoji": "🎥"},
    {"word": "film frames", "emoji": "🎞️"},
    {"word": "film projector", "emoji": "📽️"},
    {"word": "clapper board", "emoji": "🎬"},
    {"word": "television", "emoji": "📺"},
    {"word": "camera", "emoji": "📷"},
    {"word": "camera with flash", "emoji": "📸"},
    {"word": "video camera", "emoji": "📹"},
    {"word": "videocassette", "emoji": "📼"},
    {"word": "magnifying glass tilted left", "emoji": "🔍"},
    {"word": "magnifying glass tilted right", "emoji": "🔎"},
    {"word": "candle", "emoji": "🕯️"},
    {"word": "light bulb", "emoji": "💡"},
    {"word": "flashlight", "emoji": "🔦"},
    {"word": "red paper lantern", "emoji": "🏮"},
    {"word": "diya lamp", "emoji": "🪔"},
    {"word": "notebook with decorative cover", "emoji": "📔"},
    {"word": "closed book", "emoji": "📕"},
    {"word": "open book", "emoji": "📖"},
    {"word": "green book", "emoji": "📗"},
    {"word": "blue book", "emoji": "📘"},
    {"word": "orange book", "emoji": "📙"},
    {"word": "books", "emoji": "📚"},
    {"word": "notebook", "emoji": "📓"},
    {"word": "ledger", "emoji": "📒"},
    {"word": "page with curl", "emoji": "📃"},
    {"word": "scroll", "emoji": "📜"},
    {"word": "page facing up", "emoji": "📄"},
    {"word": "newspaper", "emoji": "📰"},
    {"word": "rolled-up newspaper", "emoji": "🗞️"},
    {"word": "bookmark tabs", "emoji": "📑"},
    {"word": "bookmark", "emoji": "🔖"},
    {"word": "label", "emoji": "🏷️"},
    {"word": "coin", "emoji": "🪙"},
    {"word": "money bag", "emoji": "💰"},
    {"word": "treasure chest", "emoji": "🪎"},
    {"word": "yen banknote", "emoji": "💴"},
    {"word": "dollar banknote", "emoji": "💵"},
    {"word": "euro banknote", "emoji": "💶"},
    {"word": "pound banknote", "emoji": "💷"},
    {"word": "money with wings", "emoji": "💸"},
    {"word": "credit card", "emoji": "💳"},
    {"word": "receipt", "emoji": "🧾"},
    {"word": "chart increasing with yen", "emoji": "💹"},
    {"word": "envelope", "emoji": "✉️"},
    {"word": "e-mail", "emoji": "📧"},
    {"word": "incoming envelope", "emoji": "📨"},
    {"word": "envelope with arrow", "emoji": "📩"},
    {"word": "outbox tray", "emoji": "📤"},
    {"word": "inbox tray", "emoji": "📥"},
    {"word": "package", "emoji": "📦"},
    {"word": "closed mailbox with raised flag", "emoji": "📫"},
    {"word": "closed mailbox with lowered flag", "emoji": "📪"},
    {"word": "open mailbox with raised flag", "emoji": "📬"},
    {"word": "open mailbox with lowered flag", "emoji": "📭"},
    {"word": "postbox", "emoji": "📮"},
    {"word": "ballot box with ballot", "emoji": "🗳️"},
    {"word": "pencil", "emoji": "✏️"},
    {"word": "black nib", "emoji": "✒️"},
    {"word": "fountain pen", "emoji": "🖋️"},
    {"word": "pen", "emoji": "🖊️"},
    {"word": "paintbrush", "emoji": "🖌️"},
    {"word": "crayon", "emoji": "🖍️"},
    {"word": "memo", "emoji": "📝"},
    {"word": "briefcase", "emoji": "💼"},
    {"word": "file folder", "emoji": "📁"},
    {"word": "open file folder", "emoji": "📂"},
    {"word": "card index dividers", "emoji": "🗂️"},
    {"word": "calendar", "emoji": "📅"},
    {"word": "tear-off calendar", "emoji": "📆"},
    {"word": "spiral notepad", "emoji": "🗒️"},
    {"word": "spiral calendar", "emoji": "🗓️"},
    {"word": "card index", "emoji": "📇"},
    {"word": "chart increasing", "emoji": "📈"},
    {"word": "chart decreasing", "emoji": "📉"},
    {"word": "bar chart", "emoji": "📊"},
    {"word": "clipboard", "emoji": "📋"},
    {"word": "pushpin", "emoji": "📌"},
    {"word": "round pushpin", "emoji": "📍"},
    {"word": "paperclip", "emoji": "📎"},
    {"word": "linked paperclips", "emoji": "🖇️"},
    {"word": "straight ruler", "emoji": "📏"},
    {"word": "triangular ruler", "emoji": "📐"},
    {"word": "scissors", "emoji": "✂️"},
    {"word": "card file box", "emoji": "🗃️"},
    {"word": "file cabinet", "emoji": "🗄️"},
    {"word": "wastebasket", "emoji": "🗑️"},
    {"word": "locked", "emoji": "🔒"},
    {"word": "unlocked", "emoji": "🔓"},
    {"word": "locked with pen", "emoji": "🔏"},
    {"word": "locked with key", "emoji": "🔐"},
    {"word": "key", "emoji": "🔑"},
    {"word": "old key", "emoji": "🗝️"},
    {"word": "hammer", "emoji": "🔨"},
    {"word": "axe", "emoji": "🪓"},
    {"word": "pick", "emoji": "⛏️"},
    {"word": "hammer and pick", "emoji": "⚒️"},
    {"word": "hammer and wrench", "emoji": "🛠️"},
    {"word": "dagger", "emoji": "🗡️"},
    {"word": "crossed swords", "emoji": "⚔️"},
    {"word": "bomb", "emoji": "💣"},
    {"word": "boomerang", "emoji": "🪃"},
    {"word": "bow and arrow", "emoji": "🏹"},
    {"word": "shield", "emoji": "🛡️"},
    {"word": "carpentry saw", "emoji": "🪚"},
    {"word": "wrench", "emoji": "🔧"},
    {"word": "screwdriver", "emoji": "🪛"},
    {"word": "nut and bolt", "emoji": "🔩"},
    {"word": "gear", "emoji": "⚙️"},
    {"word": "clamp", "emoji": "🗜️"},
    {"word": "balance scale", "emoji": "⚖️"},
    {"word": "white cane", "emoji": "🦯"},
    {"word": "link", "emoji": "🔗"},
    {"word": "broken chain", "emoji": "⛓️‍💥"},
    {"word": "chains", "emoji": "⛓️"},
    {"word": "hook", "emoji": "🪝"},
    {"word": "toolbox", "emoji": "🧰"},
    {"word": "magnet", "emoji": "🧲"},
    {"word": "ladder", "emoji": "🪜"},
    {"word": "shovel", "emoji": "🪏"},
    {"word": "alembic", "emoji": "⚗️"},
    {"word": "test tube", "emoji": "🧪"},
    {"word": "petri dish", "emoji": "🧫"},
    {"word": "dna", "emoji": "🧬"},
    {"word": "microscope", "emoji": "🔬"},
    {"word": "telescope", "emoji": "🔭"},
    {"word": "satellite antenna", "emoji": "📡"},
    {"word": "syringe", "emoji": "💉"},
    {"word": "drop of blood", "emoji": "🩸"},
    {"word": "pill", "emoji": "💊"},
    {"word": "adhesive bandage", "emoji": "🩹"},
    {"word": "crutch", "emoji": "🩼"},
    {"word": "stethoscope", "emoji": "🩺"},
    {"word": "x-ray", "emoji": "🩻"},
    {"word": "door", "emoji": "🚪"},
    {"word": "elevator", "emoji": "🛗"},
    {"word": "mirror", "emoji": "🪞"},
    {"word": "window", "emoji": "🪟"},
    {"word": "bed", "emoji": "🛏️"},
    {"word": "couch and lamp", "emoji": "🛋️"},
    {"word": "chair", "emoji": "🪑"},
    {"word": "toilet", "emoji": "🚽"},
    {"word": "plunger", "emoji": "🪠"},
    {"word": "shower", "emoji": "🚿"},
    {"word": "bathtub", "emoji": "🛁"},
    {"word": "mouse trap", "emoji": "🪤"},
    {"word": "razor", "emoji": "🪒"},
    {"word": "lotion bottle", "emoji": "🧴"},
    {"word": "safety pin", "emoji": "🧷"},
    {"word": "broom", "emoji": "🧹"},
    {"word": "basket", "emoji": "🧺"},
    {"word": "roll of paper", "emoji": "🧻"},
    {"word": "bucket", "emoji": "🪣"},
    {"word": "soap", "emoji": "🧼"},
    {"word": "bubbles", "emoji": "🫧"},
    {"word": "toothbrush", "emoji": "🪥"},
    {"word": "sponge", "emoji": "🧽"},
    {"word": "fire extinguisher", "emoji": "🧯"},
    {"word": "shopping cart", "emoji": "🛒"},
    {"word": "cigarette", "emoji": "🚬"},
    {"word": "coffin", "emoji": "⚰️"},
    {"word": "headstone", "emoji": "🪦"},
    {"word": "funeral urn", "emoji": "⚱️"},
    {"word": "nazar amulet", "emoji": "🧿"},
    {"word": "hamsa", "emoji": "🪬"},
    {"word": "moai", "emoji": "🗿"},
    {"word": "placard", "emoji": "🪧"},
    {"word": "identification card", "emoji": "🪪"},
    {"word": "atm sign", "emoji": "🏧"},
    {"word": "litter in bin sign", "emoji": "🚮"},
    {"word": "potable water", "emoji": "🚰"},
    {"word": "wheelchair symbol", "emoji": "♿"},
    {"word": "men’s room", "emoji": "🚹"},
    {"word": "women’s room", "emoji": "🚺"},
    {"word": "restroom", "emoji": "🚻"},
    {"word": "baby symbol", "emoji": "🚼"},
    {"word": "water closet", "emoji": "🚾"},
    {"word": "passport control", "emoji": "🛂"},
    {"word": "customs", "emoji": "🛃"},
    {"word": "baggage claim", "emoji": "🛄"},
    {"word": "left luggage", "emoji": "🛅"},
    {"word": "warning", "emoji": "⚠️"},
    {"word": "children crossing", "emoji": "🚸"},
    {"word": "no entry", "emoji": "⛔"},
    {"word": "prohibited", "emoji": "🚫"},
    {"word": "no bicycles", "emoji": "🚳"},
    {"word": "no smoking", "emoji": "🚭"},
    {"word": "no littering", "emoji": "🚯"},
    {"word": "non-potable water", "emoji": "🚱"},
    {"word": "no pedestrians", "emoji": "🚷"},
    {"word": "no mobile phones", "emoji": "📵"},
    {"word": "no one under eighteen", "emoji": "🔞"},
    {"word": "radioactive", "emoji": "☢️"},
    {"word": "biohazard", "emoji": "☣️"},
    {"word": "up arrow", "emoji": "⬆️"},
    {"word": "up-right arrow", "emoji": "↗️"},
    {"word": "right arrow", "emoji": "➡️"},
    {"word": "down-right arrow", "emoji": "↘️"},
    {"word": "down arrow", "emoji": "⬇️"},
    {"word": "down-left arrow", "emoji": "↙️"},
    {"word": "left arrow", "emoji": "⬅️"},
    {"word": "up-left arrow", "emoji": "↖️"},
    {"word": "up-down arrow", "emoji": "↕️"},
    {"word": "left-right arrow", "emoji": "↔️"},
    {"word": "right arrow curving left", "emoji": "↩️"},
    {"word": "left arrow curving right", "emoji": "↪️"},
    {"word": "right arrow curving up", "emoji": "⤴️"},
    {"word": "right arrow curving down", "emoji": "⤵️"},
    {"word": "clockwise vertical arrows", "emoji": "🔃"},
    {"word": "counterclockwise arrows button", "emoji": "🔄"},
    {"word": "back arrow", "emoji": "🔙"},
    {"word": "end arrow", "emoji": "🔚"},
    {"word": "on! arrow", "emoji": "🔛"},
    {"word": "soon arrow", "emoji": "🔜"},
    {"word": "top arrow", "emoji": "🔝"},
    {"word": "place of worship", "emoji": "🛐"},
    {"word": "atom symbol", "emoji": "⚛️"},
    {"word": "om", "emoji": "🕉️"},
    {"word": "star of david", "emoji": "✡️"},
    {"word": "wheel of dharma", "emoji": "☸️"},
    {"word": "yin yang", "emoji": "☯️"},
    {"word": "latin cross", "emoji": "✝️"},
    {"word": "orthodox cross", "emoji": "☦️"},
    {"word": "star and crescent", "emoji": "☪️"},
    {"word": "peace symbol", "emoji": "☮️"},
    {"word": "menorah", "emoji": "🕎"},
    {"word": "dotted six-pointed star", "emoji": "🔯"},
    {"word": "khanda", "emoji": "🪯"},
    {"word": "aries", "emoji": "♈"},
    {"word": "taurus", "emoji": "♉"},
    {"word": "gemini", "emoji": "♊"},
    {"word": "cancer", "emoji": "♋"},
    {"word": "leo", "emoji": "♌"},
    {"word": "virgo", "emoji": "♍"},
    {"word": "libra", "emoji": "♎"},
    
    // この辺でスレッド移行

    {"word": "scorpio", "emoji": "♏"},
    {"word": "sagittarius", "emoji": "♐"},
    {"word": "capricorn", "emoji": "♑"},
    {"word": "aquarius", "emoji": "♒"},
    {"word": "pisces", "emoji": "♓"},
    {"word": "ophiuchus", "emoji": "⛎"},
    {"word": "shuffle tracks button", "emoji": "🔀"},
    {"word": "repeat button", "emoji": "🔁"},
    {"word": "repeat single button", "emoji": "🔂"},
    {"word": "play button", "emoji": "▶️"},
    {"word": "fast-forward button", "emoji": "⏩"},
    {"word": "next track button", "emoji": "⏭️"},
    {"word": "play or pause button", "emoji": "⏯️"},
    {"word": "reverse button", "emoji": "◀️"},
    {"word": "fast reverse button", "emoji": "⏪"},
    {"word": "last track button", "emoji": "⏮️"},
    {"word": "upwards button", "emoji": "🔼"},
    {"word": "fast up button", "emoji": "⏫"},
    {"word": "downwards button", "emoji": "🔽"},
    {"word": "fast down button", "emoji": "⏬"},
    {"word": "pause button", "emoji": "⏸️"},
    {"word": "stop button", "emoji": "⏹️"},
    {"word": "record button", "emoji": "⏺️"},
    {"word": "eject button", "emoji": "⏏️"},
    {"word": "cinema", "emoji": "🎦"},
    {"word": "dim button", "emoji": "🔅"},
    {"word": "bright button", "emoji": "🔆"},
    {"word": "antenna bars", "emoji": "📶"},
    {"word": "wireless", "emoji": "🛜"},
    {"word": "vibration mode", "emoji": "📳"},
    {"word": "mobile phone off", "emoji": "📴"},
    {"word": "female sign", "emoji": "♀️"},
    {"word": "male sign", "emoji": "♂️"},
    {"word": "transgender symbol", "emoji": "⚧️"},
    {"word": "multiply", "emoji": "✖️"},
    {"word": "plus", "emoji": "➕"},
    {"word": "minus", "emoji": "➖"},
    {"word": "divide", "emoji": "➗"},
    {"word": "heavy equals sign", "emoji": "🟰"},
    {"word": "infinity", "emoji": "♾️"},
    {"word": "double exclamation mark", "emoji": "‼️"},
    {"word": "exclamation question mark", "emoji": "⁉️"},
    {"word": "red question mark", "emoji": "❓"},
    {"word": "white question mark", "emoji": "❔"},
    {"word": "white exclamation mark", "emoji": "❕"},
    {"word": "red exclamation mark", "emoji": "❗"},
    {"word": "wavy dash", "emoji": "〰️"},
    {"word": "currency exchange", "emoji": "💱"},
    {"word": "heavy dollar sign", "emoji": "💲"},
    {"word": "medical symbol", "emoji": "⚕️"},
    {"word": "recycling symbol", "emoji": "♻️"},
    {"word": "fleur-de-lis", "emoji": "⚜️"},
    {"word": "trident emblem", "emoji": "🔱"},
    {"word": "name badge", "emoji": "📛"},
    {"word": "japanese symbol for beginner", "emoji": "🔰"},
    {"word": "hollow red circle", "emoji": "⭕"},
    {"word": "check mark button", "emoji": "✅"},
    {"word": "check box with check", "emoji": "☑️"},
    {"word": "check mark", "emoji": "✔️"},
    {"word": "cross mark", "emoji": "❌"},
    {"word": "cross mark button", "emoji": "❎"},
    {"word": "curly loop", "emoji": "➰"},
    {"word": "double curly loop", "emoji": "➿"},
    {"word": "part alternation mark", "emoji": "〽️"},
    {"word": "eight-spoked asterisk", "emoji": "✳️"},
    {"word": "eight-pointed star", "emoji": "✴️"},
    {"word": "sparkle", "emoji": "❇️"},
    {"word": "copyright", "emoji": "©️"},
    {"word": "registered", "emoji": "®️"},
    {"word": "trade mark", "emoji": "™️"},

    
];

window.wordPool = [

// 生成済
    {"word": "keycap 2", "emoji": "2️⃣"},
    {"word": "keycap 3", "emoji": "3️⃣"},
    {"word": "keycap 4", "emoji": "4️⃣"},
    {"word": "keycap 5", "emoji": "5️⃣"},
    {"word": "keycap 6", "emoji": "6️⃣"},
    {"word": "keycap 7", "emoji": "7️⃣"},
    {"word": "keycap 8", "emoji": "8️⃣"},
    {"word": "keycap 9", "emoji": "9️⃣"},
    {"word": "keycap 10", "emoji": "🔟"},
    {"word": "input latin uppercase", "emoji": "🔠"},
    {"word": "input latin lowercase", "emoji": "🔡"},
    {"word": "input numbers", "emoji": "🔢"},
    {"word": "input symbols", "emoji": "🔣"},
    {"word": "input latin letters", "emoji": "🔤"},
    {"word": "a button (blood type)", "emoji": "🅰️"},
    {"word": "ab button (blood type)", "emoji": "🆎"},
    {"word": "b button (blood type)", "emoji": "🅱️"},
    {"word": "information", "emoji": "ℹ️"},
    {"word": "circled m", "emoji": "Ⓜ️"},
    {"word": "o button (blood type)", "emoji": "🅾️"},
    {"word": "p button", "emoji": "🅿️"},
    {"word": "japanese “service charge” button", "emoji": "🈂️"},
    {"word": "japanese “monthly amount” button", "emoji": "🈷️"},
    {"word": "japanese “congratulations” button", "emoji": "㊗️"},
    {"word": "japanese “secret” button", "emoji": "㊙️"},
    {"word": "red circle", "emoji": "🔴"},
    {"word": "orange circle", "emoji": "🟠"},
    {"word": "yellow circle", "emoji": "🟡"},
    {"word": "green circle", "emoji": "🟢"},
    {"word": "blue circle", "emoji": "🔵"},
    {"word": "purple circle", "emoji": "🟣"},
    {"word": "brown circle", "emoji": "🟤"},
    {"word": "red square", "emoji": "🟥"},
    {"word": "orange square", "emoji": "🟧"},
    {"word": "yellow square", "emoji": "🟨"},
    {"word": "green square", "emoji": "🟩"},
    {"word": "blue square", "emoji": "🟦"},
    {"word": "purple square", "emoji": "🟪"},
    {"word": "brown square", "emoji": "🟫"},
    {"word": "black large square", "emoji": "⬛"},
    {"word": "white large square", "emoji": "⬜"},
    {"word": "black medium square", "emoji": "◼️"},
    {"word": "white medium square", "emoji": "◻️"},
    {"word": "black medium-small square", "emoji": "◾"},
    {"word": "white medium-small square", "emoji": "◽"},
    {"word": "black small square", "emoji": "▪️"},
    {"word": "white small square", "emoji": "▫️"},
    {"word": "large orange diamond", "emoji": "🔶"},
    {"word": "large blue diamond", "emoji": "🔷"},
    {"word": "small orange diamond", "emoji": "🔸"},
    {"word": "small blue diamond", "emoji": "🔹"},
    {"word": "red triangle pointed up", "emoji": "🔺"},
    {"word": "red triangle pointed down", "emoji": "🔻"},
    {"word": "diamond with a dot", "emoji": "💠"},
    {"word": "radio button", "emoji": "🔘"},
    {"word": "white square button", "emoji": "🔳"},
    {"word": "black square button", "emoji": "🔲"},
    {"word": "chequered flag", "emoji": "🏁"},
    {"word": "triangular flag", "emoji": "🚩"},
    {"word": "crossed flags", "emoji": "🎌"},
    {"word": "black flag", "emoji": "🏴"},
    {"word": "white flag", "emoji": "🏳️"},
    {"word": "rainbow flag", "emoji": "🏳️‍🌈"},
    {"word": "transgender flag", "emoji": "🏳️‍⚧️"},
    {"word": "pirate flag", "emoji": "🏴‍☠️"},



];