window.wordPool = [

// 生成元
    {"word": "smiling face with horns", "emoji": "😈", "color": "", "effect": "", "facing": ""},
    {"word": "angry face with horns", "emoji": "👿", "color": "", "effect": "", "facing": ""},
    {"word": "skull", "emoji": "💀", "color": "", "effect": "", "facing": ""},
    {"word": "skull and crossbones", "emoji": "☠️", "color": "", "effect": "", "facing": ""},
    {"word": "pile of poo", "emoji": "💩", "color": "", "effect": "", "facing": ""},
    {"word": "clown face", "emoji": "🤡", "color": "", "effect": "", "facing": ""},
    {"word": "ogre", "emoji": "👹", "color": "", "effect": "", "facing": ""},
    {"word": "goblin", "emoji": "👺", "color": "", "effect": "", "facing": ""},
    {"word": "ghost", "emoji": "👻", "color": "", "effect": "", "facing": ""},
    {"word": "alien", "emoji": "👽", "color": "", "effect": "", "facing": ""},
    {"word": "alien monster", "emoji": "👾", "color": "", "effect": "", "facing": ""},
    {"word": "robot", "emoji": "🤖", "color": "", "effect": "", "facing": ""},
    {"word": "see-no-evil monkey", "emoji": "🙈", "color": "", "effect": "", "facing": ""},
    {"word": "hear-no-evil monkey", "emoji": "🙉", "color": "", "effect": "", "facing": ""},
    {"word": "speak-no-evil monkey", "emoji": "🙊", "color": "", "effect": "", "facing": ""},
    {"word": "love letter", "emoji": "💌", "color": "", "effect": "", "facing": ""},
    {"word": "heart with arrow", "emoji": "💘", "color": "", "effect": "", "facing": ""},
    {"word": "heart with ribbon", "emoji": "💝", "color": "", "effect": "", "facing": ""},
    {"word": "sparkling heart", "emoji": "💖", "color": "", "effect": "", "facing": ""},
    {"word": "growing heart", "emoji": "💗", "color": "", "effect": "", "facing": ""},
    {"word": "beating heart", "emoji": "💓", "color": "", "effect": "", "facing": ""},
    {"word": "revolving hearts", "emoji": "💞", "color": "", "effect": "", "facing": ""},
    {"word": "two hearts", "emoji": "💕", "color": "", "effect": "", "facing": ""},
    {"word": "heart decoration", "emoji": "💟", "color": "", "effect": "", "facing": ""},
    {"word": "heart exclamation", "emoji": "❣️", "color": "", "effect": "", "facing": ""},
    {"word": "broken heart", "emoji": "💔", "color": "", "effect": "", "facing": ""},
    {"word": "heart on fire", "emoji": "❤️‍🔥", "color": "", "effect": "", "facing": ""},
    {"word": "mending heart", "emoji": "❤️‍🩹", "color": "", "effect": "", "facing": ""},
    {"word": "red heart", "emoji": "❤️", "color": "", "effect": "", "facing": ""},
    {"word": "pink heart", "emoji": "🩷", "color": "", "effect": "", "facing": ""},
    {"word": "orange heart", "emoji": "🧡", "color": "", "effect": "", "facing": ""},
    {"word": "yellow heart", "emoji": "💛", "color": "", "effect": "", "facing": ""},
    {"word": "green heart", "emoji": "💚", "color": "", "effect": "", "facing": ""},
    {"word": "blue heart", "emoji": "💙", "color": "", "effect": "", "facing": ""},
    {"word": "light blue heart", "emoji": "🩵", "color": "", "effect": "", "facing": ""},
    {"word": "purple heart", "emoji": "💜", "color": "", "effect": "", "facing": ""},
    {"word": "brown heart", "emoji": "🤎", "color": "", "effect": "", "facing": ""},
    {"word": "black heart", "emoji": "🖤", "color": "", "effect": "", "facing": ""},
    {"word": "grey heart", "emoji": "🩶", "color": "", "effect": "", "facing": ""},
    {"word": "white heart", "emoji": "🤍", "color": "", "effect": "", "facing": ""},
    {"word": "kiss mark", "emoji": "💋", "color": "", "effect": "", "facing": ""},
    {"word": "hundred points", "emoji": "💯", "color": "", "effect": "", "facing": ""},
    {"word": "anger symbol", "emoji": "💢", "color": "", "effect": "", "facing": ""},
    {"word": "collision", "emoji": "💥", "color": "", "effect": "", "facing": ""},
    {"word": "dizzy", "emoji": "💫", "color": "", "effect": "", "facing": ""},
    {"word": "sweat droplets", "emoji": "💦", "color": "", "effect": "", "facing": ""},
    {"word": "dashing away", "emoji": "💨", "color": "", "effect": "", "facing": ""},
    {"word": "hole", "emoji": "🕳️", "color": "", "effect": "", "facing": ""},
    {"word": "speech balloon", "emoji": "💬", "color": "", "effect": "", "facing": ""},
    {"word": "eye in speech bubble", "emoji": "👁️‍🗨️", "color": "", "effect": "", "facing": ""},







    // 😈 Smiling Face with Horns
    {"word": "devil", "emoji": "😈", "color": "purple", "effect": "", "facing": ""},
    {"word": "demon", "emoji": "😈", "color": "darkpurple", "effect": "", "facing": ""},
    {"word": "horn", "emoji": "😈", "color": "magenta", "effect": "", "facing": ""},
    {"word": "smile", "emoji": "😈", "color": "pink", "effect": "", "facing": ""},
    {"word": "purple", "emoji": "😈", "color": "purple", "effect": "", "facing": ""},
    {"word": "mischief", "emoji": "😈", "color": "violet", "effect": "", "facing": ""},
    {"word": "evil", "emoji": "😈", "color": "black", "effect": "", "facing": ""},
    {"word": "imp", "emoji": "😈", "color": "lavender", "effect": "", "facing": ""},
    {"word": "trick", "emoji": "😈", "color": "orange", "effect": "", "facing": ""},
    {"word": "sin", "emoji": "😈", "color": "crimson", "effect": "", "facing": ""},
    {"word": "prank", "emoji": "😈", "color": "yellow", "effect": "", "facing": ""},
    {"word": "bad", "emoji": "😈", "color": "gray", "effect": "", "facing": ""},
    {"word": "smirk", "emoji": "😈", "color": "indigo", "effect": "", "facing": ""},
    {"word": "villain", "emoji": "😈", "color": "darkred", "effect": "", "facing": ""},
    {"word": "monster", "emoji": "😈", "color": "green", "effect": "", "facing": ""},

    // 👿 Angry Face with Horns
    {"word": "angry", "emoji": "👿", "color": "red", "effect": "", "facing": ""},
    {"word": "fury", "emoji": "👿", "color": "crimson", "effect": "", "facing": ""},
    {"word": "mad", "emoji": "👿", "color": "orange", "effect": "", "facing": ""},
    {"word": "rage", "emoji": "👿", "color": "darkred", "effect": "", "facing": ""},
    {"word": "demon", "emoji": "👿", "color": "purple", "effect": "", "facing": ""},
    {"word": "devil", "emoji": "👿", "color": "darkpurple", "effect": "", "facing": ""},
    {"word": "horn", "emoji": "👿", "color": "black", "effect": "", "facing": ""},
    {"word": "scowl", "emoji": "👿", "color": "gray", "effect": "", "facing": ""},
    {"word": "purple", "emoji": "👿", "color": "purple", "effect": "", "facing": ""},
    {"word": "hell", "emoji": "👿", "color": "maroon", "effect": "", "facing": ""},
    {"word": "hate", "emoji": "👿", "color": "charcoal", "effect": "", "facing": ""},
    {"word": "threat", "emoji": "👿", "color": "navy", "effect": "", "facing": ""},
    {"word": "enemy", "emoji": "👿", "color": "brown", "effect": "", "facing": ""},
    {"word": "malice", "emoji": "👿", "color": "indigo", "effect": "", "facing": ""},
    {"word": "ogre", "emoji": "👿", "color": "darkgreen", "effect": "", "facing": ""},

    // 💀 Skull
    {"word": "skull", "emoji": "💀", "color": "white", "effect": "", "facing": ""},
    {"word": "bone", "emoji": "💀", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "head", "emoji": "💀", "color": "ivory", "effect": "", "facing": ""},
    {"word": "death", "emoji": "💀", "color": "black", "effect": "", "facing": ""},
    {"word": "skeleton", "emoji": "💀", "color": "silver", "effect": "", "facing": ""},
    {"word": "ghost", "emoji": "💀", "color": "cyan", "effect": "", "facing": ""},
    {"word": "dead", "emoji": "💀", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "grave", "emoji": "💀", "color": "brown", "effect": "", "facing": ""},
    {"word": "scary", "emoji": "💀", "color": "purple", "effect": "", "facing": ""},
    {"word": "horror", "emoji": "💀", "color": "crimson", "effect": "", "facing": ""},
    {"word": "anatomy", "emoji": "💀", "color": "tan", "effect": "", "facing": ""},
    {"word": "white", "emoji": "💀", "color": "white", "effect": "", "facing": ""},
    {"word": "spook", "emoji": "💀", "color": "lime", "effect": "", "facing": ""},
    {"word": "creepy", "emoji": "💀", "color": "darkgreen", "effect": "", "facing": ""},
    {"word": "crypt", "emoji": "💀", "color": "stone", "effect": "", "facing": ""},

    // ☠️ Skull and Crossbones
    {"word": "pirate", "emoji": "☠️", "color": "black", "effect": "", "facing": ""},
    {"word": "danger", "emoji": "☠️", "color": "red", "effect": "", "facing": ""},
    {"word": "poison", "emoji": "☠️", "color": "lime", "effect": "", "facing": ""},
    {"word": "hazard", "emoji": "☠️", "color": "orange", "effect": "", "facing": ""},
    {"word": "warning", "emoji": "☠️", "color": "yellow", "effect": "", "facing": ""},
    {"word": "toxic", "emoji": "☠️", "color": "green", "effect": "", "facing": ""},
    {"word": "skull", "emoji": "☠️", "color": "white", "effect": "", "facing": ""},
    {"word": "bone", "emoji": "☠️", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "cross", "emoji": "☠️", "color": "gray", "effect": "", "facing": ""},
    {"word": "flag", "emoji": "☠️", "color": "navy", "effect": "", "facing": ""},
    {"word": "ship", "emoji": "☠️", "color": "brown", "effect": "", "facing": ""},
    {"word": "captain", "emoji": "☠️", "color": "gold", "effect": "", "facing": ""},
    {"word": "treasure", "emoji": "☠️", "color": "yellow", "effect": "", "facing": ""},
    {"word": "curse", "emoji": "☠️", "color": "purple", "effect": "", "facing": ""},
    {"word": "risk", "emoji": "☠️", "color": "darkorange", "effect": "", "facing": ""},

    // 💩 Pile of Poo
    {"word": "poop", "emoji": "💩", "color": "brown", "effect": "", "facing": ""},
    {"word": "poo", "emoji": "💩", "color": "saddlebrown", "effect": "", "facing": ""},
    {"word": "feces", "emoji": "💩", "color": "darkbrown", "effect": "", "facing": ""},
    {"word": "brown", "emoji": "💩", "color": "brown", "effect": "", "facing": ""},
    {"word": "smell", "emoji": "💩", "color": "green", "effect": "", "facing": ""},
    {"word": "stink", "emoji": "💩", "color": "olive", "effect": "", "facing": ""},
    {"word": "toilet", "emoji": "💩", "color": "white", "effect": "", "facing": ""},
    {"word": "smile", "emoji": "💩", "color": "pink", "effect": "", "facing": ""},
    {"word": "dirt", "emoji": "💩", "color": "tan", "effect": "", "facing": ""},
    {"word": "manure", "emoji": "💩", "color": "ochre", "effect": "", "facing": ""},
    {"word": "waste", "emoji": "💩", "color": "gray", "effect": "", "facing": ""},
    {"word": "dump", "emoji": "💩", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "pile", "emoji": "💩", "color": "lightbrown", "effect": "", "facing": ""},
    {"word": "joke", "emoji": "💩", "color": "yellow", "effect": "", "facing": ""},
    {"word": "flush", "emoji": "💩", "color": "blue", "effect": "", "facing": ""},

// 🤡 Clown Face
    {"word": "clown", "emoji": "🤡", "color": "white", "effect": "", "facing": ""},
    {"word": "circus", "emoji": "🤡", "color": "red", "effect": "", "facing": ""},
    {"word": "joker", "emoji": "🤡", "color": "purple", "effect": "", "facing": ""},
    {"word": "makeup", "emoji": "🤡", "color": "pink", "effect": "", "facing": ""},
    {"word": "nose", "emoji": "🤡", "color": "red", "effect": "", "facing": ""},
    {"word": "smile", "emoji": "🤡", "color": "yellow", "effect": "", "facing": ""},
    {"word": "balloon", "emoji": "🤡", "color": "orange", "effect": "", "facing": ""},
    {"word": "joke", "emoji": "🤡", "color": "green", "effect": "", "facing": ""},
    {"word": "funny", "emoji": "🤡", "color": "cyan", "effect": "", "facing": ""},
    {"word": "mime", "emoji": "🤡", "color": "black", "effect": "", "facing": ""},
    {"word": "wig", "emoji": "🤡", "color": "blue", "effect": "", "facing": ""},
    {"word": "show", "emoji": "🤡", "color": "gold", "effect": "", "facing": ""},
    {"word": "party", "emoji": "🤡", "color": "magenta", "effect": "", "facing": ""},
    {"word": "costume", "emoji": "🤡", "color": "violet", "effect": "", "facing": ""},
    {"word": "laugh", "emoji": "🤡", "color": "lime", "effect": "", "facing": ""},

    // 👹 Ogre
    {"word": "ogre", "emoji": "👹", "color": "red", "effect": "", "facing": ""},
    {"word": "demon", "emoji": "👹", "color": "darkred", "effect": "", "facing": ""},
    {"word": "mask", "emoji": "👹", "color": "maroon", "effect": "", "facing": ""},
    {"word": "red", "emoji": "👹", "color": "crimson", "effect": "", "facing": ""},
    {"word": "horn", "emoji": "👹", "color": "gold", "effect": "", "facing": ""},
    {"word": "scary", "emoji": "👹", "color": "purple", "effect": "", "facing": ""},
    {"word": "monster", "emoji": "👹", "color": "black", "effect": "", "facing": ""},
    {"word": "teeth", "emoji": "👹", "color": "white", "effect": "", "facing": ""},
    {"word": "japan", "emoji": "👹", "color": "navy", "effect": "", "facing": ""},
    {"word": "folklore", "emoji": "👹", "color": "brown", "effect": "", "facing": ""},
    {"word": "evil", "emoji": "👹", "color": "charcoal", "effect": "", "facing": ""},
    {"word": "beast", "emoji": "👹", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "glare", "emoji": "👹", "color": "orange", "effect": "", "facing": ""},
    {"word": "fury", "emoji": "👹", "color": "orange red", "effect": "", "facing": ""},
    {"word": "wrath", "emoji": "👹", "color": "indigo", "effect": "", "facing": ""},

    // 👺 Goblin
    {"word": "goblin", "emoji": "👺", "color": "red", "effect": "", "facing": ""},
    {"word": "nose", "emoji": "👺", "color": "crimson", "effect": "", "facing": ""},
    {"word": "mask", "emoji": "👺", "color": "darkred", "effect": "", "facing": ""},
    {"word": "red", "emoji": "👺", "color": "red", "effect": "", "facing": ""},
    {"word": "tengu", "emoji": "👺", "color": "black", "effect": "", "facing": ""},
    {"word": "japan", "emoji": "👺", "color": "white", "effect": "", "facing": ""},
    {"word": "culture", "emoji": "👺", "color": "gold", "effect": "", "facing": ""},
    {"word": "spirit", "emoji": "👺", "color": "cyan", "effect": "", "facing": ""},
    {"word": "mountain", "emoji": "👺", "color": "green", "effect": "", "facing": ""},
    {"word": "ninja", "emoji": "👺", "color": "navy", "effect": "", "facing": ""},
    {"word": "legend", "emoji": "👺", "color": "brown", "effect": "", "facing": ""},
    {"word": "shrine", "emoji": "👺", "color": "orange", "effect": "", "facing": ""},
    {"word": "proud", "emoji": "👺", "color": "purple", "effect": "", "facing": ""},
    {"word": "wood", "emoji": "👺", "color": "darkgreen", "effect": "", "facing": ""},
    {"word": "myth", "emoji": "👺", "color": "gray", "effect": "", "facing": ""},

    // 👻 Ghost
    {"word": "ghost", "emoji": "👻", "color": "white", "effect": "", "facing": ""},
    {"word": "spook", "emoji": "👻", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "phantom", "emoji": "👻", "color": "silver", "effect": "", "facing": ""},
    {"word": "spirit", "emoji": "👻", "color": "cyan", "effect": "", "facing": ""},
    {"word": "white", "emoji": "👻", "color": "white", "effect": "", "facing": ""},
    {"word": "scary", "emoji": "👻", "color": "purple", "effect": "", "facing": ""},
    {"word": "halloween", "emoji": "👻", "color": "orange", "effect": "", "facing": ""},
    {"word": "float", "emoji": "👻", "color": "lightblue", "effect": "", "facing": ""},
    {"word": "boo", "emoji": "👻", "color": "lime", "effect": "", "facing": ""},
    {"word": "sheet", "emoji": "👻", "color": "ivory", "effect": "", "facing": ""},
    {"word": "haunt", "emoji": "👻", "color": "indigo", "effect": "", "facing": ""},
    {"word": "night", "emoji": "👻", "color": "navy", "effect": "", "facing": ""},
    {"word": "soul", "emoji": "👻", "color": "violet", "effect": "", "facing": ""},
    {"word": "shadow", "emoji": "👻", "color": "black", "effect": "", "facing": ""},
    {"word": "horror", "emoji": "👻", "color": "darkred", "effect": "", "facing": ""},

    // 👽 Alien
    {"word": "alien", "emoji": "👽", "color": "green", "effect": "", "facing": ""},
    {"word": "space", "emoji": "👽", "color": "black", "effect": "", "facing": ""},
    {"word": "ufo", "emoji": "👽", "color": "silver", "effect": "", "facing": ""},
    {"word": "martian", "emoji": "👽", "color": "lime", "effect": "", "facing": ""},
    {"word": "galaxy", "emoji": "👽", "color": "purple", "effect": "", "facing": ""},
    {"word": "star", "emoji": "👽", "color": "yellow", "effect": "", "facing": ""},
    {"word": "planet", "emoji": "👽", "color": "blue", "effect": "", "facing": ""},
    {"word": "green", "emoji": "👽", "color": "green", "effect": "", "facing": ""},
    {"word": "gray", "emoji": "👽", "color": "gray", "effect": "", "facing": ""},
    {"word": "orbit", "emoji": "👽", "color": "cyan", "effect": "", "facing": ""},
    {"word": "rocket", "emoji": "👽", "color": "orange", "effect": "", "facing": ""},
    {"word": "scifi", "emoji": "👽", "color": "indigo", "effect": "", "facing": ""},
    {"word": "future", "emoji": "👽", "color": "gold", "effect": "", "facing": ""},
    {"word": "cosmos", "emoji": "👽", "color": "navy", "effect": "", "facing": ""},
    {"word": "abduction", "emoji": "👽", "color": "darkgray", "effect": "", "facing": ""},

// 👾 Alien Monster
    {"word": "monster", "emoji": "👾", "color": "purple", "effect": "", "facing": ""},
    {"word": "invader", "emoji": "👾", "color": "magenta", "effect": "", "facing": ""},
    {"word": "game", "emoji": "👾", "color": "green", "effect": "", "facing": ""},
    {"word": "pixel", "emoji": "👾", "color": "cyan", "effect": "", "facing": ""},
    {"word": "alien", "emoji": "👾", "color": "darkpurple", "effect": "", "facing": ""},
    {"word": "purple", "emoji": "👾", "color": "purple", "effect": "", "facing": ""},
    {"word": "retro", "emoji": "👾", "color": "orange", "effect": "", "facing": ""},
    {"word": "arcade", "emoji": "👾", "color": "yellow", "effect": "", "facing": ""},
    {"word": "enemy", "emoji": "👾", "color": "red", "effect": "", "facing": ""},
    {"word": "boss", "emoji": "👾", "color": "crimson", "effect": "", "facing": ""},
    {"word": "glitch", "emoji": "👾", "color": "lime", "effect": "", "facing": ""},
    {"word": "player", "emoji": "👾", "color": "blue", "effect": "", "facing": ""},
    {"word": "space", "emoji": "👾", "color": "black", "effect": "", "facing": ""},
    {"word": "attack", "emoji": "👾", "color": "darkorange", "effect": "", "facing": ""},
    {"word": "laser", "emoji": "👾", "color": "red", "effect": "", "facing": ""},

    // 🤖 Robot
    {"word": "robot", "emoji": "🤖", "color": "gray", "effect": "", "facing": ""},
    {"word": "bot", "emoji": "🤖", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "cyborg", "emoji": "🤖", "color": "silver", "effect": "", "facing": ""},
    {"word": "metal", "emoji": "🤖", "color": "slate", "effect": "", "facing": ""},
    {"word": "gear", "emoji": "🤖", "color": "gold", "effect": "", "facing": ""},
    {"word": "iron", "emoji": "🤖", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "future", "emoji": "🤖", "color": "cyan", "effect": "", "facing": ""},
    {"word": "android", "emoji": "🤖", "color": "green", "effect": "", "facing": ""},
    {"word": "machine", "emoji": "🤖", "color": "blue", "effect": "", "facing": ""},
    {"word": "code", "emoji": "🤖", "color": "black", "effect": "", "facing": ""},
    {"word": "tech", "emoji": "🤖", "color": "navy", "effect": "", "facing": ""},
    {"word": "ai", "emoji": "🤖", "color": "white", "effect": "", "facing": ""},
    {"word": "wire", "emoji": "🤖", "color": "orange", "effect": "", "facing": ""},
    {"word": "screen", "emoji": "🤖", "color": "lightblue", "effect": "", "facing": ""},
    {"word": "battery", "emoji": "🤖", "color": "lime", "effect": "", "facing": ""},

    // 🙈 See-No-Evil Monkey
    {"word": "monkey", "emoji": "🙈", "color": "brown", "effect": "", "facing": ""},
    {"word": "ape", "emoji": "🙈", "color": "darkbrown", "effect": "", "facing": ""},
    {"word": "eye", "emoji": "🙈", "color": "white", "effect": "", "facing": ""},
    {"word": "blind", "emoji": "🙈", "color": "black", "effect": "", "facing": ""},
    {"word": "shy", "emoji": "🙈", "color": "pink", "effect": "", "facing": ""},
    {"word": "hide", "emoji": "🙈", "color": "gray", "effect": "", "facing": ""},
    {"word": "secret", "emoji": "🙈", "color": "purple", "effect": "", "facing": ""},
    {"word": "peek", "emoji": "🙈", "color": "yellow", "effect": "", "facing": ""},
    {"word": "shame", "emoji": "🙈", "color": "red", "effect": "", "facing": ""},
    {"word": "cover", "emoji": "🙈", "color": "tan", "effect": "", "facing": ""},
    {"word": "japan", "emoji": "🙈", "color": "crimson", "effect": "", "facing": ""},
    {"word": "shrine", "emoji": "🙈", "color": "orange", "effect": "", "facing": ""},
    {"word": "wisdom", "emoji": "🙈", "color": "gold", "effect": "", "facing": ""},
    {"word": "fur", "emoji": "🙈", "color": "saddlebrown", "effect": "", "facing": ""},
    {"word": "jungle", "emoji": "🙈", "color": "green", "effect": "", "facing": ""},

    // 🙉 Hear-No-Evil Monkey
    {"word": "monkey", "emoji": "🙉", "color": "brown", "effect": "", "facing": ""},
    {"word": "ape", "emoji": "🙉", "color": "darkbrown", "effect": "", "facing": ""},
    {"word": "ear", "emoji": "🙉", "color": "pink", "effect": "", "facing": ""},
    {"word": "deaf", "emoji": "🙉", "color": "black", "effect": "", "facing": ""},
    {"word": "sound", "emoji": "🙉", "color": "blue", "effect": "", "facing": ""},
    {"word": "noise", "emoji": "🙉", "color": "orange", "effect": "", "facing": ""},
    {"word": "quiet", "emoji": "🙉", "color": "white", "effect": "", "facing": ""},
    {"word": "listen", "emoji": "🙉", "color": "green", "effect": "", "facing": ""},
    {"word": "loud", "emoji": "🙉", "color": "red", "effect": "", "facing": ""},
    {"word": "cover", "emoji": "🙉", "color": "tan", "effect": "", "facing": ""},
    {"word": "japan", "emoji": "🙉", "color": "crimson", "effect": "", "facing": ""},
    {"word": "shrine", "emoji": "🙉", "color": "orange", "effect": "", "facing": ""},
    {"word": "wisdom", "emoji": "🙉", "color": "gold", "effect": "", "facing": ""},
    {"word": "fur", "emoji": "🙉", "color": "saddlebrown", "effect": "", "facing": ""},
    {"word": "jungle", "emoji": "🙉", "color": "green", "effect": "", "facing": ""},

    // 🙊 Speak-No-Evil Monkey
    {"word": "monkey", "emoji": "🙊", "color": "brown", "effect": "", "facing": ""},
    {"word": "ape", "emoji": "🙊", "color": "darkbrown", "effect": "", "facing": ""},
    {"word": "mouth", "emoji": "🙊", "color": "pink", "effect": "", "facing": ""},
    {"word": "mute", "emoji": "🙊", "color": "black", "effect": "", "facing": ""},
    {"word": "silent", "emoji": "🙊", "color": "white", "effect": "", "facing": ""},
    {"word": "secret", "emoji": "🙊", "color": "purple", "effect": "", "facing": ""},
    {"word": "quiet", "emoji": "🙊", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "speak", "emoji": "🙊", "color": "blue", "effect": "", "facing": ""},
    {"word": "talk", "emoji": "🙊", "color": "cyan", "effect": "", "facing": ""},
    {"word": "cover", "emoji": "🙊", "color": "tan", "effect": "", "facing": ""},
    {"word": "japan", "emoji": "🙊", "color": "crimson", "effect": "", "facing": ""},
    {"word": "shrine", "emoji": "🙊", "color": "orange", "effect": "", "facing": ""},
    {"word": "wisdom", "emoji": "🙊", "color": "gold", "effect": "", "facing": ""},
    {"word": "fur", "emoji": "🙊", "color": "saddlebrown", "effect": "", "facing": ""},
    {"word": "jungle", "emoji": "🙊", "color": "green", "effect": "", "facing": ""},

// 💌 Love Letter
    {"word": "letter", "emoji": "💌", "color": "white", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💌", "color": "red", "effect": "", "facing": ""},
    {"word": "mail", "emoji": "💌", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "envelope", "emoji": "💌", "color": "ivory", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💌", "color": "pink", "effect": "", "facing": ""},
    {"word": "stamp", "emoji": "💌", "color": "crimson", "effect": "", "facing": ""},
    {"word": "secret", "emoji": "💌", "color": "purple", "effect": "", "facing": ""},
    {"word": "message", "emoji": "💌", "color": "cream", "effect": "", "facing": ""},
    {"word": "romance", "emoji": "💌", "color": "rose", "effect": "", "facing": ""},
    {"word": "note", "emoji": "💌", "color": "tan", "effect": "", "facing": ""},
    {"word": "paper", "emoji": "💌", "color": "white", "effect": "", "facing": ""},
    {"word": "confession", "emoji": "💌", "color": "magenta", "effect": "", "facing": ""},
    {"word": "write", "emoji": "💌", "color": "blue", "effect": "", "facing": ""},
    {"word": "send", "emoji": "💌", "color": "cyan", "effect": "", "facing": ""},
    {"word": "valentines", "emoji": "💌", "color": "darkred", "effect": "", "facing": ""},

    // 💘 Heart with Arrow
    {"word": "arrow", "emoji": "💘", "color": "gray", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💘", "color": "red", "effect": "", "facing": ""},
    {"word": "cupid", "emoji": "💘", "color": "gold", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💘", "color": "pink", "effect": "", "facing": ""},
    {"word": "shot", "emoji": "💘", "color": "crimson", "effect": "", "facing": ""},
    {"word": "crush", "emoji": "💘", "color": "magenta", "effect": "", "facing": ""},
    {"word": "pierce", "emoji": "💘", "color": "silver", "effect": "", "facing": ""},
    {"word": "target", "emoji": "💘", "color": "orange", "effect": "", "facing": ""},
    {"word": "romance", "emoji": "💘", "color": "rose", "effect": "", "facing": ""},
    {"word": "passion", "emoji": "💘", "color": "darkred", "effect": "", "facing": ""},
    {"word": "weapon", "emoji": "💘", "color": "black", "effect": "", "facing": ""},
    {"word": "match", "emoji": "💘", "color": "yellow", "effect": "", "facing": ""},
    {"word": "aim", "emoji": "💘", "color": "lime", "effect": "", "facing": ""},
    {"word": "fall", "emoji": "💘", "color": "violet", "effect": "", "facing": ""},
    {"word": "pink", "emoji": "💘", "color": "pink", "effect": "", "facing": ""},

    // 💝 Heart with Ribbon
    {"word": "gift", "emoji": "💝", "color": "gold", "effect": "", "facing": ""},
    {"word": "present", "emoji": "💝", "color": "orange", "effect": "", "facing": ""},
    {"word": "ribbon", "emoji": "💝", "color": "yellow", "effect": "", "facing": ""},
    {"word": "bow", "emoji": "💝", "color": "red", "effect": "", "facing": ""},
    {"word": "box", "emoji": "💝", "color": "brown", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💝", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💝", "color": "crimson", "effect": "", "facing": ""},
    {"word": "chocolate", "emoji": "💝", "color": "darkbrown", "effect": "", "facing": ""},
    {"word": "anniversary", "emoji": "💝", "color": "purple", "effect": "", "facing": ""},
    {"word": "birthday", "emoji": "💝", "color": "cyan", "effect": "", "facing": ""},
    {"word": "wrap", "emoji": "💝", "color": "green", "effect": "", "facing": ""},
    {"word": "give", "emoji": "💝", "color": "blue", "effect": "", "facing": ""},
    {"word": "reward", "emoji": "💝", "color": "magenta", "effect": "", "facing": ""},
    {"word": "surprise", "emoji": "💝", "color": "lime", "effect": "", "facing": ""},
    {"word": "package", "emoji": "💝", "color": "tan", "effect": "", "facing": ""},

    // 💖 Sparkling Heart
    {"word": "sparkle", "emoji": "💖", "color": "yellow", "effect": "", "facing": ""},
    {"word": "glitter", "emoji": "💖", "color": "gold", "effect": "", "facing": ""},
    {"word": "shine", "emoji": "💖", "color": "white", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💖", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💖", "color": "red", "effect": "", "facing": ""},
    {"word": "star", "emoji": "💖", "color": "yellow", "effect": "", "facing": ""},
    {"word": "cute", "emoji": "💖", "color": "magenta", "effect": "", "facing": ""},
    {"word": "bright", "emoji": "💖", "color": "cyan", "effect": "", "facing": ""},
    {"word": "pink", "emoji": "💖", "color": "pink", "effect": "", "facing": ""},
    {"word": "glow", "emoji": "💖", "color": "lime", "effect": "", "facing": ""},
    {"word": "magic", "emoji": "💖", "color": "purple", "effect": "", "facing": ""},
    {"word": "fancy", "emoji": "💖", "color": "violet", "effect": "", "facing": ""},
    {"word": "gem", "emoji": "💖", "color": "silver", "effect": "", "facing": ""},
    {"word": "pretty", "emoji": "💖", "color": "rose", "effect": "", "facing": ""},
    {"word": "pure", "emoji": "💖", "color": "ivory", "effect": "", "facing": ""},

    // 💗 Growing Heart
    {"word": "pulse", "emoji": "💗", "color": "pink", "effect": "", "facing": ""},
    {"word": "beat", "emoji": "💗", "color": "red", "effect": "", "facing": ""},
    {"word": "throb", "emoji": "💗", "color": "crimson", "effect": "", "facing": ""},
    {"word": "grow", "emoji": "💗", "color": "lime", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💗", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💗", "color": "magenta", "effect": "", "facing": ""},
    {"word": "wave", "emoji": "💗", "color": "cyan", "effect": "", "facing": ""},
    {"word": "emotion", "emoji": "💗", "color": "purple", "effect": "", "facing": ""},
    {"word": "vibration", "emoji": "💗", "color": "orange", "effect": "", "facing": ""},
    {"word": "excite", "emoji": "💗", "color": "yellow", "effect": "", "facing": ""},
    {"word": "layer", "emoji": "💗", "color": "lightpink", "effect": "", "facing": ""},
    {"word": "pink", "emoji": "💗", "color": "pink", "effect": "", "facing": ""},
    {"word": "size", "emoji": "💗", "color": "gray", "effect": "", "facing": ""},
    {"word": "expand", "emoji": "💗", "color": "blue", "effect": "", "facing": ""},
    {"word": "feeling", "emoji": "💗", "color": "rose", "effect": "", "facing": ""},

// 💓 Beating Heart
    {"word": "beat", "emoji": "💓", "color": "pink", "effect": "", "facing": ""},
    {"word": "pulse", "emoji": "💓", "color": "magenta", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💓", "color": "red", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💓", "color": "rose", "effect": "", "facing": ""},
    {"word": "throb", "emoji": "💓", "color": "crimson", "effect": "", "facing": ""},
    {"word": "wave", "emoji": "💓", "color": "lightpink", "effect": "", "facing": ""},
    {"word": "shock", "emoji": "💓", "color": "orange", "effect": "", "facing": ""},
    {"word": "sound", "emoji": "💓", "color": "yellow", "effect": "", "facing": ""},
    {"word": "life", "emoji": "💓", "color": "lime", "effect": "", "facing": ""},
    {"word": "pink", "emoji": "💓", "color": "pink", "effect": "", "facing": ""},
    {"word": "scare", "emoji": "💓", "color": "purple", "effect": "", "facing": ""},
    {"word": "excite", "emoji": "💓", "color": "gold", "effect": "", "facing": ""},
    {"word": "move", "emoji": "💓", "color": "cyan", "effect": "", "facing": ""},
    {"word": "signal", "emoji": "💓", "color": "blue", "effect": "", "facing": ""},
    {"word": "vibe", "emoji": "💓", "color": "violet", "effect": "", "facing": ""},

    // 💞 Revolving Hearts
    {"word": "orbit", "emoji": "💞", "color": "cyan", "effect": "", "facing": ""},
    {"word": "spin", "emoji": "💞", "color": "orange", "effect": "", "facing": ""},
    {"word": "turn", "emoji": "💞", "color": "yellow", "effect": "", "facing": ""},
    {"word": "circle", "emoji": "💞", "color": "lime", "effect": "", "facing": ""},
    {"word": "loop", "emoji": "💞", "color": "gray", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💞", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💞", "color": "red", "effect": "", "facing": ""},
    {"word": "dance", "emoji": "💞", "color": "magenta", "effect": "", "facing": ""},
    {"word": "bond", "emoji": "💞", "color": "purple", "effect": "", "facing": ""},
    {"word": "couple", "emoji": "💞", "color": "rose", "effect": "", "facing": ""},
    {"word": "friend", "emoji": "💞", "color": "blue", "effect": "", "facing": ""},
    {"word": "twin", "emoji": "💞", "color": "silver", "effect": "", "facing": ""},
    {"word": "mix", "emoji": "💞", "color": "violet", "effect": "", "facing": ""},
    {"word": "pink", "emoji": "💞", "color": "pink", "effect": "", "facing": ""},
    {"word": "cycle", "emoji": "💞", "color": "green", "effect": "", "facing": ""},

    // 💕 Two Hearts
    {"word": "pair", "emoji": "💕", "color": "gold", "effect": "", "facing": ""},
    {"word": "two", "emoji": "💕", "color": "orange", "effect": "", "facing": ""},
    {"word": "double", "emoji": "💕", "color": "yellow", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💕", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💕", "color": "red", "effect": "", "facing": ""},
    {"word": "friend", "emoji": "💕", "color": "green", "effect": "", "facing": ""},
    {"word": "couple", "emoji": "💕", "color": "purple", "effect": "", "facing": ""},
    {"word": "match", "emoji": "💕", "color": "cyan", "effect": "", "facing": ""},
    {"word": "pink", "emoji": "💕", "color": "pink", "effect": "", "facing": ""},
    {"word": "cute", "emoji": "💕", "color": "magenta", "effect": "", "facing": ""},
    {"word": "date", "emoji": "💕", "color": "rose", "effect": "", "facing": ""},
    {"word": "duo", "emoji": "💕", "color": "blue", "effect": "", "facing": ""},
    {"word": "close", "emoji": "💕", "color": "lightpink", "effect": "", "facing": ""},
    {"word": "share", "emoji": "💕", "color": "white", "effect": "", "facing": ""},
    {"word": "trust", "emoji": "💕", "color": "navy", "effect": "", "facing": ""},

    // 💟 Heart Decoration
    {"word": "badge", "emoji": "💟", "color": "purple", "effect": "", "facing": ""},
    {"word": "button", "emoji": "💟", "color": "darkpurple", "effect": "", "facing": ""},
    {"word": "purple", "emoji": "💟", "color": "purple", "effect": "", "facing": ""},
    {"word": "square", "emoji": "💟", "color": "lavender", "effect": "", "facing": ""},
    {"word": "frame", "emoji": "💟", "color": "gray", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💟", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💟", "color": "red", "effect": "", "facing": ""},
    {"word": "icon", "emoji": "💟", "color": "violet", "effect": "", "facing": ""},
    {"word": "sign", "emoji": "💟", "color": "indigo", "effect": "", "facing": ""},
    {"word": "stamp", "emoji": "💟", "color": "magenta", "effect": "", "facing": ""},
    {"word": "white", "emoji": "💟", "color": "white", "effect": "", "facing": ""},
    {"word": "art", "emoji": "💟", "color": "gold", "effect": "", "facing": ""},
    {"word": "deco", "emoji": "💟", "color": "pink", "effect": "", "facing": ""},
    {"word": "design", "emoji": "💟", "color": "cyan", "effect": "", "facing": ""},
    {"word": "tile", "emoji": "💟", "color": "lightgray", "effect": "", "facing": ""},

    // ❣️ Heart Exclamation
    {"word": "point", "emoji": "❣️", "color": "red", "effect": "", "facing": ""},
    {"word": "mark", "emoji": "❣️", "color": "crimson", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "❣️", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "❣️", "color": "darkred", "effect": "", "facing": ""},
    {"word": "alert", "emoji": "❣️", "color": "orange", "effect": "", "facing": ""},
    {"word": "shout", "emoji": "❣️", "color": "yellow", "effect": "", "facing": ""},
    {"word": "red", "emoji": "❣️", "color": "red", "effect": "", "facing": ""},
    {"word": "dot", "emoji": "❣️", "color": "black", "effect": "", "facing": ""},
    {"word": "shock", "emoji": "❣️", "color": "orange red", "effect": "", "facing": ""},
    {"word": "note", "emoji": "❣️", "color": "gray", "effect": "", "facing": ""},
    {"word": "accent", "emoji": "❣️", "color": "magenta", "effect": "", "facing": ""},
    {"word": "passion", "emoji": "❣️", "color": "maroon", "effect": "", "facing": ""},
    {"word": "emphasize", "emoji": "❣️", "color": "purple", "effect": "", "facing": ""},
    {"word": "sign", "emoji": "❣️", "color": "blue", "effect": "", "facing": ""},
    {"word": "surprise", "emoji": "❣️", "color": "gold", "effect": "", "facing": ""},

    // 💔 Broken Heart
    {"word": "break", "emoji": "💔", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "crack", "emoji": "💔", "color": "gray", "effect": "", "facing": ""},
    {"word": "sad", "emoji": "💔", "color": "blue", "effect": "", "facing": ""},
    {"word": "split", "emoji": "💔", "color": "black", "effect": "", "facing": ""},
    {"word": "hurt", "emoji": "💔", "color": "red", "effect": "", "facing": ""},
    {"word": "pain", "emoji": "💔", "color": "crimson", "effect": "", "facing": ""},
    {"word": "grief", "emoji": "💔", "color": "indigo", "effect": "", "facing": ""},
    {"word": "tear", "emoji": "💔", "color": "cyan", "effect": "", "facing": ""},
    {"word": "end", "emoji": "💔", "color": "charcoal", "effect": "", "facing": ""},
    {"word": "divorce", "emoji": "💔", "color": "maroon", "effect": "", "facing": ""},
    {"word": "sorrow", "emoji": "💔", "color": "purple", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💔", "color": "pink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💔", "color": "darkred", "effect": "", "facing": ""},
    {"word": "cry", "emoji": "💔", "color": "lightblue", "effect": "", "facing": ""},
    {"word": "damage", "emoji": "💔", "color": "stone", "effect": "", "facing": ""},

    // ❤️‍🔥 Heart on Fire
    {"word": "fire", "emoji": "❤️‍🔥", "color": "orange", "effect": "", "facing": ""},
    {"word": "flame", "emoji": "❤️‍🔥", "color": "red", "effect": "", "facing": ""},
    {"word": "burn", "emoji": "❤️‍🔥", "color": "darkorange", "effect": "", "facing": ""},
    {"word": "hot", "emoji": "❤️‍🔥", "color": "yellow", "effect": "", "facing": ""},
    {"word": "passion", "emoji": "❤️‍🔥", "color": "crimson", "effect": "", "facing": ""},
    {"word": "love", "emoji": "❤️‍🔥", "color": "red", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "❤️‍🔥", "color": "pink", "effect": "", "facing": ""},
    {"word": "desire", "emoji": "❤️‍🔥", "color": "magenta", "effect": "", "facing": ""},
    {"word": "energy", "emoji": "❤️‍🔥", "color": "gold", "effect": "", "facing": ""},
    {"word": "zeal", "emoji": "❤️‍🔥", "color": "maroon", "effect": "", "facing": ""},
    {"word": "match", "emoji": "❤️‍🔥", "color": "brown", "effect": "", "facing": ""},
    {"word": "heat", "emoji": "❤️‍🔥", "color": "orange red", "effect": "", "facing": ""},
    {"word": "glow", "emoji": "❤️‍🔥", "color": "lightyellow", "effect": "", "facing": ""},
    {"word": "blaze", "emoji": "❤️‍🔥", "color": "scarlet", "effect": "", "facing": ""},
    {"word": "red", "emoji": "❤️‍🔥", "color": "red", "effect": "", "facing": ""},

    // ❤️‍🩹 Mending Heart
    {"word": "bandage", "emoji": "❤️‍🩹", "color": "tan", "effect": "", "facing": ""},
    {"word": "heal", "emoji": "❤️‍🩹", "color": "lime", "effect": "", "facing": ""},
    {"word": "mend", "emoji": "❤️‍🩹", "color": "green", "effect": "", "facing": ""},
    {"word": "cure", "emoji": "❤️‍🩹", "color": "cyan", "effect": "", "facing": ""},
    {"word": "care", "emoji": "❤️‍🩹", "color": "pink", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "❤️‍🩹", "color": "red", "effect": "", "facing": ""},
    {"word": "love", "emoji": "❤️‍🩹", "color": "rose", "effect": "", "facing": ""},
    {"word": "nurse", "emoji": "❤️‍🩹", "color": "white", "effect": "", "facing": ""},
    {"word": "rehab", "emoji": "❤️‍🩹", "color": "blue", "effect": "", "facing": ""},
    {"word": "hurt", "emoji": "❤️‍🩹", "color": "gray", "effect": "", "facing": ""},
    {"word": "hope", "emoji": "❤️‍🩹", "color": "gold", "effect": "", "facing": ""},
    {"word": "doctor", "emoji": "❤️‍🩹", "color": "navy", "effect": "", "facing": ""},
    {"word": "recovery", "emoji": "❤️‍🩹", "color": "emerald", "effect": "", "facing": ""},
    {"word": "tape", "emoji": "❤️‍🩹", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "relief", "emoji": "❤️‍🩹", "color": "skyblue", "effect": "", "facing": ""},

    // ❤️ Red Heart
    {"word": "heart", "emoji": "❤️", "color": "red", "effect": "", "facing": ""},
    {"word": "love", "emoji": "❤️", "color": "crimson", "effect": "", "facing": ""},
    {"word": "red", "emoji": "❤️", "color": "red", "effect": "", "facing": ""},
    {"word": "like", "emoji": "❤️", "color": "pink", "effect": "", "facing": ""},
    {"word": "life", "emoji": "❤️", "color": "scarlet", "effect": "", "facing": ""},
    {"word": "blood", "emoji": "❤️", "color": "darkred", "effect": "", "facing": ""},
    {"word": "romance", "emoji": "❤️", "color": "rose", "effect": "", "facing": ""},
    {"word": "sweet", "emoji": "❤️", "color": "magenta", "effect": "", "facing": ""},
    {"word": "card", "emoji": "❤️", "color": "white", "effect": "", "facing": ""},
    {"word": "suit", "emoji": "❤️", "color": "black", "effect": "", "facing": ""},
    {"word": "gift", "emoji": "❤️", "color": "gold", "effect": "", "facing": ""},
    {"word": "soul", "emoji": "❤️", "color": "purple", "effect": "", "facing": ""},
    {"word": "favor", "emoji": "❤️", "color": "orange", "effect": "", "facing": ""},
    {"word": "true", "emoji": "❤️", "color": "gold", "effect": "", "facing": ""},
    {"word": "amity", "emoji": "❤️", "color": "green", "effect": "", "facing": ""},

    // 🩷 Pink Heart
    {"word": "pink", "emoji": "🩷", "color": "pink", "effect": "", "facing": ""},
    {"word": "cute", "emoji": "🩷", "color": "magenta", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "🩷", "color": "lightpink", "effect": "", "facing": ""},
    {"word": "love", "emoji": "🩷", "color": "rose", "effect": "", "facing": ""},
    {"word": "girl", "emoji": "🩷", "color": "hotpink", "effect": "", "facing": ""},
    {"word": "sweet", "emoji": "🩷", "color": "pastelpink", "effect": "", "facing": ""},
    {"word": "pretty", "emoji": "🩷", "color": "violet", "effect": "", "facing": ""},
    {"word": "soft", "emoji": "🩷", "color": "cream", "effect": "", "facing": ""},
    {"word": "mild", "emoji": "🩷", "color": "white", "effect": "", "facing": ""},
    {"word": "charm", "emoji": "🩷", "color": "gold", "effect": "", "facing": ""},
    {"word": "blush", "emoji": "🩷", "color": "red", "effect": "", "facing": ""},
    {"word": "friend", "emoji": "🩷", "color": "green", "effect": "", "facing": ""},
    {"word": "pure", "emoji": "🩷", "color": "ivory", "effect": "", "facing": ""},
    {"word": "petal", "emoji": "🩷", "color": "salmon", "effect": "", "facing": ""},
    {"word": "fairy", "emoji": "🩷", "color": "cyan", "effect": "", "facing": ""},

// 🧡 Orange Heart
    {"word": "orange", "emoji": "🧡", "color": "orange", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "🧡", "color": "lightorange", "effect": "", "facing": ""},
    {"word": "love", "emoji": "🧡", "color": "red", "effect": "", "facing": ""},
    {"word": "warm", "emoji": "🧡", "color": "brown", "effect": "", "facing": ""},
    {"word": "autumn", "emoji": "🧡", "color": "darkorange", "effect": "", "facing": ""},
    {"word": "sun", "emoji": "🧡", "color": "yellow", "effect": "", "facing": ""},
    {"word": "fruit", "emoji": "🧡", "color": "orange", "effect": "", "facing": ""},
    {"word": "citrus", "emoji": "🧡", "color": "lime", "effect": "", "facing": ""},
    {"word": "carrot", "emoji": "🧡", "color": "orange", "effect": "", "facing": ""},
    {"word": "tiger", "emoji": "🧡", "color": "black", "effect": "", "facing": ""},
    {"word": "sunset", "emoji": "🧡", "color": "purple", "effect": "", "facing": ""},
    {"word": "gold", "emoji": "🧡", "color": "gold", "effect": "", "facing": ""},
    {"word": "bright", "emoji": "🧡", "color": "white", "effect": "", "facing": ""},
    {"word": "energy", "emoji": "🧡", "color": "yellow", "effect": "", "facing": ""},
    {"word": "cheer", "emoji": "🧡", "color": "pink", "effect": "", "facing": ""},

    // 💛 Yellow Heart
    {"word": "yellow", "emoji": "💛", "color": "yellow", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💛", "color": "lightyellow", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💛", "color": "red", "effect": "", "facing": ""},
    {"word": "sun", "emoji": "💛", "color": "orange", "effect": "", "facing": ""},
    {"word": "happy", "emoji": "💛", "color": "pink", "effect": "", "facing": ""},
    {"word": "gold", "emoji": "💛", "color": "gold", "effect": "", "facing": ""},
    {"word": "banana", "emoji": "💛", "color": "yellow", "effect": "", "facing": ""},
    {"word": "lemon", "emoji": "💛", "color": "lime", "effect": "", "facing": ""},
    {"word": "star", "emoji": "💛", "color": "gold", "effect": "", "facing": ""},
    {"word": "honey", "emoji": "💛", "color": "brown", "effect": "", "facing": ""},
    {"word": "light", "emoji": "💛", "color": "white", "effect": "", "facing": ""},
    {"word": "friend", "emoji": "💛", "color": "green", "effect": "", "facing": ""},
    {"word": "smile", "emoji": "💛", "color": "orange", "effect": "", "facing": ""},
    {"word": "duck", "emoji": "💛", "color": "yellow", "effect": "", "facing": ""},
    {"word": "summer", "emoji": "💛", "color": "cyan", "effect": "", "facing": ""},

    // 💚 Green Heart
    {"word": "green", "emoji": "💚", "color": "green", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💚", "color": "lightgreen", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💚", "color": "red", "effect": "", "facing": ""},
    {"word": "nature", "emoji": "💚", "color": "green", "effect": "", "facing": ""},
    {"word": "leaf", "emoji": "💚", "color": "lime", "effect": "", "facing": ""},
    {"word": "tree", "emoji": "💚", "color": "brown", "effect": "", "facing": ""},
    {"word": "grass", "emoji": "💚", "color": "green", "effect": "", "facing": ""},
    {"word": "forest", "emoji": "💚", "color": "darkgreen", "effect": "", "facing": ""},
    {"word": "life", "emoji": "💚", "color": "cyan", "effect": "", "facing": ""},
    {"word": "envy", "emoji": "💚", "color": "purple", "effect": "", "facing": ""},
    {"word": "melon", "emoji": "💚", "color": "lime", "effect": "", "facing": ""},
    {"word": "frog", "emoji": "💚", "color": "green", "effect": "", "facing": ""},
    {"word": "fresh", "emoji": "💚", "color": "white", "effect": "", "facing": ""},
    {"word": "peace", "emoji": "💚", "color": "blue", "effect": "", "facing": ""},
    {"word": "earth", "emoji": "💚", "color": "blue", "effect": "", "facing": ""},

    // 💙 Blue Heart
    {"word": "blue", "emoji": "💙", "color": "blue", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💙", "color": "lightblue", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💙", "color": "red", "effect": "", "facing": ""},
    {"word": "sea", "emoji": "💙", "color": "cyan", "effect": "", "facing": ""},
    {"word": "ocean", "emoji": "💙", "color": "navy", "effect": "", "facing": ""},
    {"word": "sky", "emoji": "💙", "color": "skyblue", "effect": "", "facing": ""},
    {"word": "water", "emoji": "💙", "color": "blue", "effect": "", "facing": ""},
    {"word": "ice", "emoji": "💙", "color": "white", "effect": "", "facing": ""},
    {"word": "cool", "emoji": "💙", "color": "silver", "effect": "", "facing": ""},
    {"word": "deep", "emoji": "💙", "color": "black", "effect": "", "facing": ""},
    {"word": "sad", "emoji": "💙", "color": "gray", "effect": "", "facing": ""},
    {"word": "whale", "emoji": "💙", "color": "navy", "effect": "", "facing": ""},
    {"word": "peace", "emoji": "💙", "color": "white", "effect": "", "facing": ""},
    {"word": "calm", "emoji": "💙", "color": "teal", "effect": "", "facing": ""},
    {"word": "trust", "emoji": "💙", "color": "indigo", "effect": "", "facing": ""},

    // 🩵 Light Blue Heart
    {"word": "cyan", "emoji": "🩵", "color": "cyan", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "🩵", "color": "white", "effect": "", "facing": ""},
    {"word": "love", "emoji": "🩵", "color": "red", "effect": "", "facing": ""},
    {"word": "aqua", "emoji": "🩵", "color": "cyan", "effect": "", "facing": ""},
    {"word": "sky", "emoji": "🩵", "color": "skyblue", "effect": "", "facing": ""},
    {"word": "ice", "emoji": "🩵", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "clear", "emoji": "🩵", "color": "white", "effect": "", "facing": ""},
    {"word": "frost", "emoji": "🩵", "color": "silver", "effect": "", "facing": ""},
    {"word": "mint", "emoji": "🩵", "color": "lime", "effect": "", "facing": ""},
    {"word": "river", "emoji": "🩵", "color": "blue", "effect": "", "facing": ""},
    {"word": "glass", "emoji": "🩵", "color": "clear", "effect": "", "facing": ""},
    {"word": "diamond", "emoji": "🩵", "color": "gold", "effect": "", "facing": ""},
    {"word": "bubble", "emoji": "🩵", "color": "white", "effect": "", "facing": ""},
    {"word": "fresh", "emoji": "🩵", "color": "cyan", "effect": "", "facing": ""},
    {"word": "breeze", "emoji": "🩵", "color": "lightblue", "effect": "", "facing": ""},

// 💜 Purple Heart
    {"word": "purple", "emoji": "💜", "color": "purple", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "💜", "color": "lavender", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💜", "color": "red", "effect": "", "facing": ""},
    {"word": "grape", "emoji": "💜", "color": "purple", "effect": "", "facing": ""},
    {"word": "wine", "emoji": "💜", "color": "darkred", "effect": "", "facing": ""},
    {"word": "royal", "emoji": "💜", "color": "gold", "effect": "", "facing": ""},
    {"word": "magic", "emoji": "💜", "color": "magenta", "effect": "", "facing": ""},
    {"word": "violet", "emoji": "💜", "color": "violet", "effect": "", "facing": ""},
    {"word": "galaxy", "emoji": "💜", "color": "black", "effect": "", "facing": ""},
    {"word": "mystery", "emoji": "💜", "color": "indigo", "effect": "", "facing": ""},
    {"word": "sweet", "emoji": "💜", "color": "pink", "effect": "", "facing": ""},
    {"word": "plum", "emoji": "💜", "color": "maroon", "effect": "", "facing": ""},
    {"word": "night", "emoji": "💜", "color": "navy", "effect": "", "facing": ""},
    {"word": "orchid", "emoji": "💜", "color": "fuchsia", "effect": "", "facing": ""},
    {"word": "noble", "emoji": "💜", "color": "purple", "effect": "", "facing": ""},

    // 🤎 Brown Heart
    {"word": "brown", "emoji": "🤎", "color": "brown", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "🤎", "color": "lightbrown", "effect": "", "facing": ""},
    {"word": "love", "emoji": "🤎", "color": "red", "effect": "", "facing": ""},
    {"word": "chocolate", "emoji": "🤎", "color": "darkbrown", "effect": "", "facing": ""},
    {"word": "coffee", "emoji": "🤎", "color": "saddlebrown", "effect": "", "facing": ""},
    {"word": "wood", "emoji": "🤎", "color": "brown", "effect": "", "facing": ""},
    {"word": "earth", "emoji": "🤎", "color": "green", "effect": "", "facing": ""},
    {"word": "bear", "emoji": "🤎", "color": "brown", "effect": "", "facing": ""},
    {"word": "mud", "emoji": "🤎", "color": "ochre", "effect": "", "facing": ""},
    {"word": "cookie", "emoji": "🤎", "color": "tan", "effect": "", "facing": ""},
    {"word": "cocoa", "emoji": "🤎", "color": "darkbrown", "effect": "", "facing": ""},
    {"word": "autumn", "emoji": "🤎", "color": "orange", "effect": "", "facing": ""},
    {"word": "warm", "emoji": "🤎", "color": "gold", "effect": "", "facing": ""},
    {"word": "brick", "emoji": "🤎", "color": "red brown", "effect": "", "facing": ""},
    {"word": "nut", "emoji": "🤎", "color": "tan", "effect": "", "facing": ""},

    // 🖤 Black Heart
    {"word": "black", "emoji": "🖤", "color": "black", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "🖤", "color": "charcoal", "effect": "", "facing": ""},
    {"word": "love", "emoji": "🖤", "color": "red", "effect": "", "facing": ""},
    {"word": "dark", "emoji": "🖤", "color": "black", "effect": "", "facing": ""},
    {"word": "night", "emoji": "🖤", "color": "navy", "effect": "", "facing": ""},
    {"word": "shadow", "emoji": "🖤", "color": "gray", "effect": "", "facing": ""},
    {"word": "cool", "emoji": "🖤", "color": "silver", "effect": "", "facing": ""},
    {"word": "rock", "emoji": "🖤", "color": "purple", "effect": "", "facing": ""},
    {"word": "ink", "emoji": "🖤", "color": "black", "effect": "", "facing": ""},
    {"word": "coal", "emoji": "🖤", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "goth", "emoji": "🖤", "color": "plum", "effect": "", "facing": ""},
    {"word": "space", "emoji": "🖤", "color": "indigo", "effect": "", "facing": ""},
    {"word": "mystery", "emoji": "🖤", "color": "violet", "effect": "", "facing": ""},
    {"word": "void", "emoji": "🖤", "color": "black", "effect": "", "facing": ""},
    {"word": "cat", "emoji": "🖤", "color": "yellow", "effect": "", "facing": ""},

    // 🩶 Grey Heart
    {"word": "gray", "emoji": "🩶", "color": "gray", "effect": "", "facing": ""},
    {"word": "grey", "emoji": "🩶", "color": "grey", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "🩶", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "love", "emoji": "🩶", "color": "red", "effect": "", "facing": ""},
    {"word": "silver", "emoji": "🩶", "color": "silver", "effect": "", "facing": ""},
    {"word": "metal", "emoji": "🩶", "color": "slate", "effect": "", "facing": ""},
    {"word": "iron", "emoji": "🩶", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "stone", "emoji": "🩶", "color": "stone", "effect": "", "facing": ""},
    {"word": "cloud", "emoji": "🩶", "color": "white", "effect": "", "facing": ""},
    {"word": "smoke", "emoji": "🩶", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "ash", "emoji": "🩶", "color": "charcoal", "effect": "", "facing": ""},
    {"word": "steel", "emoji": "🩶", "color": "silver", "effect": "", "facing": ""},
    {"word": "cool", "emoji": "🩶", "color": "cyan", "effect": "", "facing": ""},
    {"word": "fog", "emoji": "🩶", "color": "ivory", "effect": "", "facing": ""},
    {"word": "cement", "emoji": "🩶", "color": "gray", "effect": "", "facing": ""},

    // 🤍 White Heart
    {"word": "white", "emoji": "🤍", "color": "white", "effect": "", "facing": ""},
    {"word": "heart", "emoji": "🤍", "color": "ivory", "effect": "", "facing": ""},
    {"word": "love", "emoji": "🤍", "color": "red", "effect": "", "facing": ""},
    {"word": "pure", "emoji": "🤍", "color": "gold", "effect": "", "facing": ""},
    {"word": "snow", "emoji": "🤍", "color": "white", "effect": "", "facing": ""},
    {"word": "ice", "emoji": "🤍", "color": "cyan", "effect": "", "facing": ""},
    {"word": "milk", "emoji": "🤍", "color": "cream", "effect": "", "facing": ""},
    {"word": "angel", "emoji": "🤍", "color": "yellow", "effect": "", "facing": ""},
    {"word": "cloud", "emoji": "🤍", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "peace", "emoji": "🤍", "color": "green", "effect": "", "facing": ""},
    {"word": "light", "emoji": "🤍", "color": "white", "effect": "", "facing": ""},
    {"word": "clean", "emoji": "🤍", "color": "skyblue", "effect": "", "facing": ""},
    {"word": "ghost", "emoji": "🤍", "color": "silver", "effect": "", "facing": ""},
    {"word": "dove", "emoji": "🤍", "color": "white", "effect": "", "facing": ""},
    {"word": "sugar", "emoji": "🤍", "color": "white", "effect": "", "facing": ""},

    // 💋 Kiss Mark
    {"word": "kiss", "emoji": "💋", "color": "red", "effect": "", "facing": ""},
    {"word": "lip", "emoji": "💋", "color": "crimson", "effect": "", "facing": ""},
    {"word": "mouth", "emoji": "💋", "color": "pink", "effect": "", "facing": ""},
    {"word": "red", "emoji": "💋", "color": "red", "effect": "", "facing": ""},
    {"word": "makeup", "emoji": "💋", "color": "magenta", "effect": "", "facing": ""},
    {"word": "lipstick", "emoji": "💋", "color": "darkred", "effect": "", "facing": ""},
    {"word": "love", "emoji": "💋", "color": "rose", "effect": "", "facing": ""},
    {"word": "sexy", "emoji": "💋", "color": "purple", "effect": "", "facing": ""},
    {"word": "romance", "emoji": "💋", "color": "scarlet", "effect": "", "facing": ""},
    {"word": "beauty", "emoji": "💋", "color": "gold", "effect": "", "facing": ""},
    {"word": "mark", "emoji": "💋", "color": "red", "effect": "", "facing": ""},
    {"word": "print", "emoji": "💋", "color": "lightpink", "effect": "", "facing": ""},
    {"word": "passion", "emoji": "💋", "color": "maroon", "effect": "", "facing": ""},
    {"word": "flirt", "emoji": "💋", "color": "violet", "effect": "", "facing": ""},
    {"word": "pink", "emoji": "💋", "color": "pink", "effect": "", "facing": ""},

    // 💯 Hundred Points
    {"word": "score", "emoji": "💯", "color": "red", "effect": "", "facing": ""},
    {"word": "test", "emoji": "💯", "color": "white", "effect": "", "facing": ""},
    {"word": "exam", "emoji": "💯", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "perfect", "emoji": "💯", "color": "gold", "effect": "", "facing": ""},
    {"word": "grade", "emoji": "💯", "color": "crimson", "effect": "", "facing": ""},
    {"word": "red", "emoji": "💯", "color": "red", "effect": "", "facing": ""},
    {"word": "number", "emoji": "💯", "color": "black", "effect": "", "facing": ""},
    {"word": "math", "emoji": "💯", "color": "blue", "effect": "", "facing": ""},
    {"word": "school", "emoji": "💯", "color": "navy", "effect": "", "facing": ""},
    {"word": "study", "emoji": "💯", "color": "green", "effect": "", "facing": ""},
    {"word": "smart", "emoji": "💯", "color": "cyan", "effect": "", "facing": ""},
    {"word": "full", "emoji": "💯", "color": "orange", "effect": "", "facing": ""},
    {"word": "success", "emoji": "💯", "color": "yellow", "effect": "", "facing": ""},
    {"word": "win", "emoji": "💯", "color": "gold", "effect": "", "facing": ""},
    {"word": "best", "emoji": "💯", "color": "lime", "effect": "", "facing": ""},

    // 💢 Anger Symbol
    {"word": "anger", "emoji": "💢", "color": "red", "effect": "", "facing": ""},
    {"word": "mad", "emoji": "💢", "color": "orange", "effect": "", "facing": ""},
    {"word": "rage", "emoji": "💢", "color": "darkred", "effect": "", "facing": ""},
    {"word": "fury", "emoji": "💢", "color": "crimson", "effect": "", "facing": ""},
    {"word": "annoy", "emoji": "💢", "color": "purple", "effect": "", "facing": ""},
    {"word": "vein", "emoji": "💢", "color": "blue", "effect": "", "facing": ""},
    {"word": "red", "emoji": "💢", "color": "red", "effect": "", "facing": ""},
    {"word": "comic", "emoji": "💢", "color": "black", "effect": "", "facing": ""},
    {"word": "anime", "emoji": "💢", "color": "yellow", "effect": "", "facing": ""},
    {"word": "stress", "emoji": "💢", "color": "gray", "effect": "", "facing": ""},
    {"word": "hate", "emoji": "💢", "color": "charcoal", "effect": "", "facing": ""},
    {"word": "scold", "emoji": "💢", "color": "brown", "effect": "", "facing": ""},
    {"word": "fight", "emoji": "💢", "color": "maroon", "effect": "", "facing": ""},
    {"word": "cross", "emoji": "💢", "color": "white", "effect": "", "facing": ""},
    {"word": "bother", "emoji": "💢", "color": "indigo", "effect": "", "facing": ""},

    // 💥 Collision
    {"word": "boom", "emoji": "💥", "color": "orange", "effect": "", "facing": ""},
    {"word": "bang", "emoji": "💥", "color": "red", "effect": "", "facing": ""},
    {"word": "crash", "emoji": "💥", "color": "yellow", "effect": "", "facing": ""},
    {"word": "blast", "emoji": "💥", "color": "darkorange", "effect": "", "facing": ""},
    {"word": "burst", "emoji": "💥", "color": "crimson", "effect": "", "facing": ""},
    {"word": "spark", "emoji": "💥", "color": "gold", "effect": "", "facing": ""},
    {"word": "fire", "emoji": "💥", "color": "red", "effect": "", "facing": ""},
    {"word": "hit", "emoji": "💥", "color": "brown", "effect": "", "facing": ""},
    {"word": "smash", "emoji": "💥", "color": "black", "effect": "", "facing": ""},
    {"word": "clash", "emoji": "💥", "color": "maroon", "effect": "", "facing": ""},
    {"word": "shock", "emoji": "💥", "color": "white", "effect": "", "facing": ""},
    {"word": "orange", "emoji": "💥", "color": "orange", "effect": "", "facing": ""},
    {"word": "yellow", "emoji": "💥", "color": "yellow", "effect": "", "facing": ""},
    {"word": "comic", "emoji": "💥", "color": "gray", "effect": "", "facing": ""},
    {"word": "power", "emoji": "💥", "color": "lime", "effect": "", "facing": ""},

    // 💫 Dizzy
    {"word": "dizzy", "emoji": "💫", "color": "yellow", "effect": "", "facing": ""},
    {"word": "star", "emoji": "💫", "color": "gold", "effect": "", "facing": ""},
    {"word": "gold", "emoji": "💫", "color": "gold", "effect": "", "facing": ""},
    {"word": "yellow", "emoji": "💫", "color": "yellow", "effect": "", "facing": ""},
    {"word": "spin", "emoji": "💫", "color": "orange", "effect": "", "facing": ""},
    {"word": "turn", "emoji": "💫", "color": "lightyellow", "effect": "", "facing": ""},
    {"word": "circle", "emoji": "💫", "color": "white", "effect": "", "facing": ""},
    {"word": "comet", "emoji": "💫", "color": "cyan", "effect": "", "facing": ""},
    {"word": "meteor", "emoji": "💫", "color": "blue", "effect": "", "facing": ""},
    {"word": "space", "emoji": "💫", "color": "black", "effect": "", "facing": ""},
    {"word": "sky", "emoji": "💫", "color": "navy", "effect": "", "facing": ""},
    {"word": "magic", "emoji": "💫", "color": "purple", "effect": "", "facing": ""},
    {"word": "orbit", "emoji": "💫", "color": "silver", "effect": "", "facing": ""},
    {"word": "sparkle", "emoji": "💫", "color": "lime", "effect": "", "facing": ""},
    {"word": "loop", "emoji": "💫", "color": "gray", "effect": "", "facing": ""},

// 💦 Sweat Droplets
    {"word": "sweat", "emoji": "💦", "color": "cyan", "effect": "", "facing": ""},
    {"word": "water", "emoji": "💦", "color": "blue", "effect": "", "facing": ""},
    {"word": "drop", "emoji": "💦", "color": "lightblue", "effect": "", "facing": ""},
    {"word": "splash", "emoji": "💦", "color": "skyblue", "effect": "", "facing": ""},
    {"word": "blue", "emoji": "💦", "color": "blue", "effect": "", "facing": ""},
    {"word": "rain", "emoji": "💦", "color": "navy", "effect": "", "facing": ""},
    {"word": "wet", "emoji": "💦", "color": "cyan", "effect": "", "facing": ""},
    {"word": "liquid", "emoji": "💦", "color": "clear", "effect": "", "facing": ""},
    {"word": "tired", "emoji": "💦", "color": "gray", "effect": "", "facing": ""},
    {"word": "work", "emoji": "💦", "color": "orange", "effect": "", "facing": ""},
    {"word": "tear", "emoji": "💦", "color": "white", "effect": "", "facing": ""},
    {"word": "clean", "emoji": "💦", "color": "lime", "effect": "", "facing": ""},
    {"word": "spray", "emoji": "💦", "color": "silver", "effect": "", "facing": ""},
    {"word": "leak", "emoji": "💦", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "shower", "emoji": "💦", "color": "aqua", "effect": "", "facing": ""},

    // 💨 Dashing Away
    {"word": "dash", "emoji": "💨", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "wind", "emoji": "💨", "color": "white", "effect": "", "facing": ""},
    {"word": "speed", "emoji": "💨", "color": "red", "effect": "", "facing": ""},
    {"word": "fast", "emoji": "💨", "color": "yellow", "effect": "", "facing": ""},
    {"word": "smoke", "emoji": "💨", "color": "gray", "effect": "", "facing": ""},
    {"word": "steam", "emoji": "💨", "color": "silver", "effect": "", "facing": ""},
    {"word": "run", "emoji": "💨", "color": "blue", "effect": "", "facing": ""},
    {"word": "gush", "emoji": "💨", "color": "cyan", "effect": "", "facing": ""},
    {"word": "dust", "emoji": "💨", "color": "brown", "effect": "", "facing": ""},
    {"word": "motion", "emoji": "💨", "color": "orange", "effect": "", "facing": ""},
    {"word": "quick", "emoji": "💨", "color": "gold", "effect": "", "facing": ""},
    {"word": "escape", "emoji": "💨", "color": "purple", "effect": "", "facing": ""},
    {"word": "blow", "emoji": "💨", "color": "lightblue", "effect": "", "facing": ""},
    {"word": "haste", "emoji": "💨", "color": "magenta", "effect": "", "facing": ""},
    {"word": "race", "emoji": "💨", "color": "lime", "effect": "", "facing": ""},

    // 🕳️ Hole
    {"word": "hole", "emoji": "🕳️", "color": "black", "effect": "", "facing": ""},
    {"word": "pit", "emoji": "🕳️", "color": "charcoal", "effect": "", "facing": ""},
    {"word": "black", "emoji": "🕳️", "color": "black", "effect": "", "facing": ""},
    {"word": "dark", "emoji": "🕳️", "color": "indigo", "effect": "", "facing": ""},
    {"word": "drop", "emoji": "🕳️", "color": "gray", "effect": "", "facing": ""},
    {"word": "fall", "emoji": "🕳️", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "trap", "emoji": "🕳️", "color": "red", "effect": "", "facing": ""},
    {"word": "deep", "emoji": "🕳️", "color": "navy", "effect": "", "facing": ""},
    {"word": "void", "emoji": "🕳️", "color": "purple", "effect": "", "facing": ""},
    {"word": "golf", "emoji": "🕳️", "color": "green", "effect": "", "facing": ""},
    {"word": "ground", "emoji": "🕳️", "color": "brown", "effect": "", "facing": ""},
    {"word": "dig", "emoji": "🕳️", "color": "tan", "effect": "", "facing": ""},
    {"word": "tunnel", "emoji": "🕳️", "color": "stone", "effect": "", "facing": ""},
    {"word": "grave", "emoji": "🕳️", "color": "maroon", "effect": "", "facing": ""},
    {"word": "escape", "emoji": "🕳️", "color": "silver", "effect": "", "facing": ""},

    // 💬 Speech Balloon
    {"word": "speech", "emoji": "💬", "color": "white", "effect": "", "facing": ""},
    {"word": "balloon", "emoji": "💬", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "bubble", "emoji": "💬", "color": "cyan", "effect": "", "facing": ""},
    {"word": "talk", "emoji": "💬", "color": "blue", "effect": "", "facing": ""},
    {"word": "chat", "emoji": "💬", "color": "green", "effect": "", "facing": ""},
    {"word": "speak", "emoji": "💬", "color": "navy", "effect": "", "facing": ""},
    {"word": "word", "emoji": "💬", "color": "black", "effect": "", "facing": ""},
    {"word": "voice", "emoji": "💬", "color": "gold", "effect": "", "facing": ""},
    {"word": "message", "emoji": "💬", "color": "orange", "effect": "", "facing": ""},
    {"word": "text", "emoji": "💬", "color": "gray", "effect": "", "facing": ""},
    {"word": "comic", "emoji": "💬", "color": "yellow", "effect": "", "facing": ""},
    {"word": "comment", "emoji": "💬", "color": "purple", "effect": "", "facing": ""},
    {"word": "gossip", "emoji": "💬", "color": "pink", "effect": "", "facing": ""},
    {"word": "say", "emoji": "💬", "color": "cream", "effect": "", "facing": ""},
    {"word": "dialogue", "emoji": "💬", "color": "silver", "effect": "", "facing": ""},

    // 👁️‍🗨️ Eye in Speech Bubble
    {"word": "eye", "emoji": "👁️‍🗨️", "color": "white", "effect": "", "facing": ""},
    {"word": "bubble", "emoji": "👁️‍🗨️", "color": "gray", "effect": "", "facing": ""},
    {"word": "witness", "emoji": "👁️‍🗨️", "color": "red", "effect": "", "facing": ""},
    {"word": "see", "emoji": "👁️‍🗨️", "color": "cyan", "effect": "", "facing": ""},
    {"word": "watch", "emoji": "👁️‍🗨️", "color": "black", "effect": "", "facing": ""},
    {"word": "look", "emoji": "👁️‍🗨️", "color": "blue", "effect": "", "facing": ""},
    {"word": "vision", "emoji": "👁️‍🗨️", "color": "purple", "effect": "", "facing": ""},
    {"word": "spy", "emoji": "👁️‍🗨️", "color": "darkgray", "effect": "", "facing": ""},
    {"word": "secret", "emoji": "👁️‍🗨️", "color": "indigo", "effect": "", "facing": ""},
    {"word": "chat", "emoji": "👁️‍🗨️", "color": "green", "effect": "", "facing": ""},
    {"word": "sight", "emoji": "👁️‍🗨️", "color": "silver", "effect": "", "facing": ""},
    {"word": "notice", "emoji": "👁️‍🗨️", "color": "orange", "effect": "", "facing": ""},
    {"word": "gaze", "emoji": "👁️‍🗨️", "color": "navy", "effect": "", "facing": ""},
    {"word": "speech", "emoji": "👁️‍🗨️", "color": "lightgray", "effect": "", "facing": ""},
    {"word": "scout", "emoji": "👁️‍🗨️", "color": "lime", "effect": "", "facing": ""},


];