window.wordPool = [
  // === 数字・記号・アルファベット（記号・数字順） ===
  {"word": "0", "emojis": ["0️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "1", "emoji": "👆", "color": "", "effect": "", "facing": ""}, // 元データの個別重複分
  {"word": "1", "emojis": ["🕐", "🕜"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "1", "emojis": ["1️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "10", "emojis": ["十", "🕥"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "10", "emojis": ["🔟"], "color": "blue", "effect": "", "facing": ""},
  {"word": "100", "emojis": ["💯"], "color": "red", "effect": "", "facing": ""},
  {"word": "11", "emojis": ["⑪", "🕦"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "12", "emojis": ["🕛", "🕧"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "123", "emojis": ["🔢", "🔣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "2", "emojis": ["🕑", "🕝"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "2", "emojis": ["2️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "3", "emojis": ["🕒", "🕞"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "3", "emojis": ["3️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "4", "emojis": ["🕓", "🕟"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "4", "emojis": ["4️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "5", "emojis": ["🕔", "🕠"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "5", "emojis": ["5️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "6", "emojis": ["⑥", "🕡"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "6", "emojis": ["6️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "7", "emojis": ["🕖", "🕢"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "7", "emojis": ["7️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "8", "emojis": ["🕗", "🕣"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "8", "emojis": ["8️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "9", "emojis": ["🕘", "🕤"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "9", "emojis": ["9️⃣"], "color": "blue", "effect": "", "facing": ""},

  // === A ===
  {"word": "a", "emojis": ["🅰️"], "color": "red", "effect": "", "facing": ""},
  {"word": "ab", "emojis": ["🆎"], "color": "red", "effect": "", "facing": ""},
  {"word": "abacus", "emojis": ["🧮"], "color": "brown", "effect": "", "facing": ""},
  {"word": "abc", "emojis": ["🔠", "🔡", "🔤"], "color": "blue", "effect": "", "facing": ""},
  {"word": "accordion", "emojis": ["🪗"], "color": "red", "effect": "", "facing": ""},
  {"word": "acrobat", "emojis": ["🤸", "🤸‍♂️", "🤸‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "afternoon", "emojis": ["🌆", "🌇"], "color": "orange", "effect": "", "facing": ""},
  {"word": "air", "emojis": ["💨"], "color": "grey", "effect": "", "facing": ""},
  {"word": "airplane", "emojis": ["✈️", "🛩️"], "color": "cyan", "effect": "cross", "facing": "left"},
  {"word": "airport", "emojis": ["🇲🇹", "🛃", "🛄", "🛅"], "color": "blue", "effect": "", "facing": ""},
  {"word": "alcohol", "emojis": ["🍷", "🍸", "🍹", "🍺", "🍻"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "alien", "emojis": ["👽"], "color": "green", "effect": "", "facing": ""},
  {"word": "ambulance", "emojis": ["🚑"], "color": "white", "effect": "cross", "facing": "left"},
  {"word": "amusement", "emojis": ["🎠", "🎡", "🎢", "🎪"], "color": "pink", "effect": "", "facing": ""},
  {"word": "amulet", "emojis": ["🧿", "🪬"], "color": "blue", "effect": "", "facing": ""},
  {"word": "anchor", "emojis": ["⚓"], "color": "blue", "effect": "", "facing": ""},
  {"word": "angel", "emojis": ["👼"], "color": "", "effect": "", "facing": ""},
  {"word": "angry", "emoji": "😠", "color": "", "effect": "", "facing": ""},
  {"word": "angry", "emojis": ["😾"], "color": "red", "effect": "", "facing": ""},
  {"word": "angry", "emojis": ["💢"], "color": "red", "effect": "", "facing": ""},
  {"word": "anxious", "emoji": "😰", "color": "", "effect": "", "facing": ""},
  {"word": "ant", "emojis": ["🐜"], "color": "black", "effect": "cross", "facing": "left"},
  {"word": "antenna", "emojis": ["📡"], "color": "grey", "effect": "", "facing": ""},
  {"word": "apple", "emojis": ["🍎", "🍏"], "color": "red", "effect": "rain", "facing": ""},
  {"word": "architect", "emojis": ["🏛️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "arrow", "emojis": ["💘"], "color": "", "effect": "", "facing": ""},
  {"word": "arrow", "emojis": ["🏹"], "color": "brown", "effect": "cross", "facing": "right"},
  {"word": "arrow", "emojis": ["💘", "⬆️", "↗️", "➡️", "↘️", "⬇️", "↙️", "⬅️", "↖️", "↕️", "↔️", "↩️", "↪️", "⤴️", "⤵️", "🔃", "🔄", "🔙", "🔚", "🔛", "🔜", "🔝"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "art", "emojis": ["🎭", "🖼️", "🎨"], "color": "pink", "effect": "", "facing": ""},
  {"word": "art", "emojis": ["🎨", "🎭", "🖼️"], "color": "pink", "effect": "", "facing": ""},
  {"word": "artist", "emojis": ["🧑‍🎨", "👨‍🎨", "👩‍🎨"], "color": "", "effect": "", "facing": ""},
  {"word": "atm", "emojis": ["🏧"], "color": "blue", "effect": "", "facing": ""},
  {"word": "audio", "emojis": ["🎙️", "🎚️", "🎛️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "autumn", "emojis": ["🎑"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "avocado", "emojis": ["🥑"], "color": "green", "effect": "", "facing": ""},
  {"word": "axe", "emojis": ["🪓"], "color": "brown", "effect": "", "facing": ""},

  // === B ===
  {"word": "b", "emojis": ["🅱️"], "color": "red", "effect": "", "facing": ""},
  {"word": "baby", "emojis": ["👶"], "color": "", "effect": "", "facing": ""},
  {"word": "back", "emojis": ["🔙"], "color": "grey", "effect": "", "facing": ""},
  {"word": "backhand", "emoji": "🤚", "color": "", "effect": "", "facing": ""},
  {"word": "bacon", "emojis": ["🥓"], "color": "red", "effect": "", "facing": ""},
  {"word": "bad", "emoji": "👎", "color": "", "effect": "", "facing": ""},
  {"word": "badger", "emojis": ["🦡"], "color": "grey", "effect": "", "facing": ""},
  {"word": "bag", "emojis": ["👛", "👜", "👝", "🛍️", "🎒"], "color": "pink", "effect": "", "facing": ""},
  {"word": "bag", "emojis": ["🎒", "👛", "🛍️"], "color": "pink", "effect": "", "facing": ""},
  {"word": "bald", "emojis": ["🧑‍🦲", "👨‍🦲", "👩‍🦲"], "color": "", "effect": "", "facing": ""},
  {"word": "ballet", "emojis": ["🩰"], "color": "pink", "effect": "up", "facing": ""},
  {"word": "ball", "emojis": ["⚽", "⚾", "🥎", "🏀", "🏐", "🏈", "🏉", "🎾", "🎱"], "color": "white", "effect": "", "facing": ""},
  {"word": "balloon", "emojis": ["🎈"], "color": "red", "effect": "up", "facing": ""},
  {"word": "banana", "emojis": ["🍌"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "bandage", "emojis": ["❤️‍🩹"], "color": "", "effect": "", "facing": ""},
  {"word": "bank", "emojis": ["🏦"], "color": "grey", "effect": "", "facing": ""},
  {"word": "barber", "emojis": ["💈"], "color": "blue", "effect": "", "facing": ""},
  {"word": "baseball", "emojis": ["⚾", "🥎"], "color": "white", "effect": "", "facing": ""},
  {"word": "basket", "emojis": ["備", "🧺"], "color": "brown", "effect": "", "facing": ""},
  {"word": "basketball", "emojis": ["⛹️", "⛹️‍♂️", "⛹️‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "basketball", "emojis": ["🏀"], "color": "orange", "effect": "", "facing": ""},
  {"word": "bath", "emojis": ["🛀"], "color": "", "effect": "", "facing": ""},
  {"word": "bath", "emojis": ["🚿", "🛁"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "bat", "emojis": ["🦇"], "color": "purple", "effect": "rain", "facing": ""},
  {"word": "bbq", "emojis": ["🍖", "🥩", "🥓"], "color": "red", "effect": "", "facing": ""},
  {"word": "beach", "emojis": ["🏖️", "🏝️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "beads", "emojis": ["📿"], "color": "purple", "effect": "", "facing": ""},
  {"word": "bean", "emojis": ["🫘"], "color": "brown", "effect": "", "facing": ""},
  {"word": "bear", "emojis": ["🐻", "🐻‍❄️"], "color": "brown", "effect": "", "facing": ""},
  {"word": "beard", "emojis": ["🧔", "🧔‍♂️", "🧔‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "beaver", "emojis": ["🦫"], "color": "brown", "effect": "", "facing": ""},
  {"word": "bed", "emojis": ["🛌"], "color": "", "effect": "", "facing": ""},
  {"word": "bed", "emojis": ["🛏️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "beetle", "emojis": ["🪲", "🐞"], "color": "green", "effect": "", "facing": ""},
  {"word": "bee", "emojis": ["🐝"], "color": "yellow", "effect": "rain", "facing": ""},
  {"word": "bell", "emojis": ["🛎️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "bell", "emojis": ["🔔", "🔕"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "bento", "emojis": ["🍱"], "color": "red", "effect": "", "facing": ""},
  {"word": "bike", "emojis": ["🚴", "🚴‍♂️", "🚴‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "bike", "emojis": ["🏍️", "🛵", "🚲", "🛴"], "color": "orange", "effect": "cross", "facing": "left"},
  {"word": "bird", "emojis": ["🐦", "🐦‍⬛", "🕊️", "🦩", "🦜"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "bison", "emojis": ["🦬"], "color": "brown", "effect": "", "facing": ""},
  {"word": "bite", "emojis": ["🫦"], "color": "", "effect": "", "facing": ""},
  {"word": "black", "emojis": ["🖤"], "color": "black", "effect": "", "facing": ""},
  {"word": "black", "emojis": ["♠️", "♣️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "black", "emojis": ["⚫", "⬛", "◼️", "◾", "▪️", "🔳", "🖤"], "color": "black", "effect": "", "facing": ""},
  {"word": "blank", "emoji": "😑", "color": "", "effect": "", "facing": ""},
  {"word": "blind", "emojis": ["🙈"], "color": "brown", "effect": "", "facing": ""},
  {"word": "blond", "emojis": ["👱", "👱‍♂️", "👱‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "blood", "emojis": ["🅰️", "🆎", "🅱️", "🅾️", "🩸"], "color": "red", "effect": "", "facing": ""},
  {"word": "blood", "emojis": ["🩸"], "color": "red", "effect": "", "facing": ""},
  {"word": "blush", "emoji": "😊", "color": "", "effect": "", "facing": ""},
  {"word": "blush2", "emoji": "😳", "color": "", "effect": "", "facing": ""},
  {"word": "board", "emojis": ["🪧", "🪪"], "color": "brown", "effect": "", "facing": ""},
  {"word": "boat", "emojis": ["⛵", "🛶", "🚤", "🛳️", "⛴️", "🛥️", "🚢"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "boba", "emojis": ["🧋"], "color": "brown", "effect": "", "facing": ""},
  {"word": "bomb", "emojis": ["💣"], "color": "red", "effect": "up", "facing": ""},
  {"word": "bone", "emojis": ["☠️", "💀"], "color": "white", "effect": "", "facing": ""},
  {"word": "bone", "emojis": ["🦴"], "color": "white", "effect": "", "facing": ""},
  {"word": "book", "emojis": ["📔", "📕", "📖", "📗", "📘", "📙", "📚", "📓", "📒"], "color": "orange", "effect": "rain", "facing": ""},
  {"word": "bookmark", "emojis": ["🔖"], "color": "red", "effect": "", "facing": ""},
  {"word": "boom", "emoji": "🤯", "color": "", "effect": "", "facing": ""},
  {"word": "boom", "emojis": ["💥"], "color": "orange", "effect": "", "facing": ""},
  {"word": "boots", "emojis": ["🥾", "ブーツ"], "color": "brown", "effect": "", "facing": ""},
  {"word": "bored", "emoji": "😒", "color": "", "effect": "", "facing": ""},
  {"word": "bouquet", "emojis": ["💐"], "color": "pink", "effect": "", "facing": ""},
  {"word": "bow", "emojis": ["🙇", "🙇‍♂️", "🙇‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "bowling", "emojis": ["🎳"], "color": "red", "effect": "", "facing": ""},
  {"word": "box", "emojis": ["📦"], "color": "brown", "effect": "", "facing": ""},
  {"word": "boxing", "emojis": ["🥊"], "color": "red", "effect": "", "facing": ""},
  {"word": "boy", "emojis": ["👦"], "color": "", "effect": "", "facing": ""},
  {"word": "brain", "emojis": ["🧠"], "color": "pink", "effect": "", "facing": ""},
  {"word": "bread", "emojis": ["🍞", "🥐", "🥖", "🫓", "🥨", "🥯"], "color": "orange", "effect": "", "facing": ""},
  {"word": "breathe", "emojis": ["🫁"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "briefcase", "emojis": ["💼"], "color": "brown", "effect": "", "facing": ""},
  {"word": "broccoli", "emojis": ["🥦"], "color": "green", "effect": "", "facing": ""},
  {"word": "broken", "emojis": ["💔"], "color": "", "effect": "", "facing": ""},
  {"word": "broom", "emojis": ["🧹"], "color": "brown", "effect": "", "facing": ""},
  {"word": "brown", "emojis": ["🤎"], "color": "brown", "effect": "", "facing": ""},
  {"word": "brown", "emojis": ["🟤", "🟫", "🪵", "🧱", "💩"], "color": "brown", "effect": "", "facing": ""},
  {"word": "brush", "emojis": ["🖌️"], "color": "pink", "effect": "", "facing": ""},
  {"word": "bubble", "emojis": ["🗨️"], "color": "", "effect": "", "facing": ""},
  {"word": "bubble", "emojis": ["🫧", "💬"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "bucket", "emojis": ["🪣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "building", "emojis": ["🏛️", "🏢", "🏣", "🏤", "🏬"], "color": "grey", "effect": "", "facing": ""},
  {"word": "bunny", "emojis": ["👯", "👯‍♂️", "👯‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "bunny", "emojis": ["🐰", "🐇"], "color": "white", "effect": "", "facing": ""},
  {"word": "burger", "emojis": ["🍔"], "color": "orange", "effect": "", "facing": ""},
  {"word": "burn", "emojis": ["❤️‍🔥"], "color": "orange", "effect": "", "facing": ""},
  {"word": "bus", "emojis": ["🚌", "🚍", "🚐"], "color": "yellow", "effect": "cross", "facing": "left"},
  {"word": "butter", "emojis": ["🧈"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "butterfly", "emojis": ["🦋"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "button", "emojis": ["🔀", "🔁", "🔂", "▶️", "⏩", "⏭️", "⏯️", "◀️", "⏪", "⏮️", "🔼", "⏫", "🔽", "⏬", "⏸️", "⏹️", "⏺️", "⏏️", "🔅", "🔆"], "color": "grey", "effect": "", "facing": ""},
  {"word": "boar", "emojis": ["🐗"], "color": "brown", "effect": "", "facing": ""},
  {"word": "bug", "emojis": ["🐛", "🐜", "🪲", "🐞", "🪳"], "color": "green", "effect": "", "facing": ""},
  {"word": "boomerang", "emojis": ["🛬"], "color": "brown", "effect": "cross", "facing": "right"},

  // === C ===
  {"word": "cabbage", "emojis": ["🥬"], "color": "green", "effect": "", "facing": ""},
  {"word": "cablecar", "emojis": ["🚠"], "color": "orange", "effect": "cross", "facing": "left"},
  {"word": "cactus", "emojis": ["🌵"], "color": "green", "effect": "", "facing": ""},
  {"word": "cake", "emojis": ["🎂", "🍰", "🧁", "🥧"], "color": "pink", "effect": "", "facing": ""},
  {"word": "calm", "emoji": "☺️", "color": "", "effect": "", "facing": ""},
  {"word": "calendar", "emojis": ["📅", "📆", "🗓️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "camel", "emojis": ["🐪", "🐫"], "color": "brown", "effect": "cross", "facing": "left"},
  {"word": "camera", "emojis": ["📷", "📸", "📹"], "color": "grey", "effect": "", "facing": ""},
  {"word": "camp", "emojis": ["🏕️", "⛺"], "color": "orange", "effect": "", "facing": ""},
  {"word": "candy", "emojis": ["🍬", "🍭"], "color": "pink", "effect": "rain", "facing": ""},
  {"word": "cane", "emojis": ["🧑‍🦯", "👨‍🦯", "👩‍🦯", "🧑‍🦯‍➡️", "👨‍🦯‍➡️", "👩‍🦯‍➡️"], "color": "", "effect": "", "facing": ""},
  {"word": "cane", "emojis": ["🦯"], "color": "white", "effect": "", "facing": ""},
  {"word": "can", "emojis": ["🥫"], "color": "red", "effect": "", "facing": ""},
  {"word": "cap", "emoji": "👲", "color": "", "effect": "", "facing": ""},
  {"word": "cap", "emojis": ["🧢"], "color": "blue", "effect": "", "facing": ""},
  {"word": "car", "emojis": ["🚗", "🚘", "🚙", "🏎️"], "color": "red", "effect": "cross", "facing": "left"},
  {"word": "card", "emojis": ["💟"], "color": "purple", "effect": "", "facing": ""},
  {"word": "card", "emojis": ["♠️", "♥️", "♦️", "♣️", "🃏", "🎴"], "color": "red", "effect": "rain", "facing": ""},
  {"word": "card", "emojis": ["💳"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "cardindex", "emojis": ["📇", "🗃️", "🗄️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "carrot", "emojis": ["🥕"], "color": "orange", "effect": "", "facing": ""},
  {"word": "cart", "emojis": ["🛒"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "cash", "emojis": ["💵", "💴", "💶", "💷"], "color": "green", "effect": "rain", "facing": ""},
  {"word": "castle", "emojis": ["🏯", "🏰"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "cat", "emojis": ["😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾"], "color": "orange", "effect": "", "facing": ""},
  {"word": "cat", "emojis": ["🐱", "🐈", "🐈‍⬛"], "color": "orange", "effect": "", "facing": ""},
  {"word": "caterpillar", "emojis": ["🐛"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "celebrate", "emojis": ["🎉", "🎊", "🎈"], "color": "pink", "effect": "rain", "facing": ""},
  {"word": "chain", "emojis": ["⛓️‍💥", "⛓️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "chair", "emojis": ["🪑"], "color": "brown", "effect": "", "facing": ""},
  {"word": "chart", "emojis": ["💹", "📈", "📉", "📊"], "color": "green", "effect": "up", "facing": ""},
  {"word": "chat", "emojis": ["💬"], "color": "", "effect": "", "facing": ""},
  {"word": "cheer", "emoji": "🙌", "color": "", "effect": "", "facing": ""},
  {"word": "cheers", "emojis": ["🥂", "🍻"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "cheese", "emojis": ["🧀"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "chef", "emojis": ["🧑‍🍳", "👨‍🍳", "👩‍🍳"], "color": "", "effect": "", "facing": ""},
  {"word": "cherry", "emojis": ["🍒"], "color": "red", "effect": "", "facing": ""},
  {"word": "cherryblossom", "emojis": ["🌸"], "color": "pink", "effect": "rain", "facing": ""},
  {"word": "chess", "emojis": ["♟️"], "color": "white", "effect": "", "facing": ""},
  {"word": "cheetah", "emojis": ["🐆"], "color": "yellow", "effect": "cross", "facing": "left"},
  {"word": "chicken", "emojis": ["🐔", "🐓"], "color": "white", "effect": "", "facing": ""},
  {"word": "chick", "emojis": ["🐣", "🐤", "🐥"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "child", "emojis": ["🧒"], "color": "", "effect": "", "facing": ""},
  {"word": "chime", "emojis": ["🎐"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "chipmunk", "emojis": ["🐿️"], "color": "orange", "effect": "cross", "facing": "left"},
  {"word": "chocolate", "emojis": ["🍫"], "color": "brown", "effect": "", "facing": ""},
  {"word": "chopsticks", "emojis": ["🥢"], "color": "brown", "effect": "", "facing": ""},
  {"word": "christmas", "emojis": ["🎄"], "color": "green", "effect": "", "facing": ""},
  {"word": "chu", "emoji": "😗", "color": "", "effect": "", "facing": ""},
  {"word": "church", "emojis": ["⛪", "🕌", "🕍", "🕋"], "color": "white", "effect": "", "facing": ""},
  {"word": "cinema", "emojis": ["🎥", "🎞️", "📽️", "🎬"], "color": "grey", "effect": "", "facing": ""},
  {"word": "cinema", "emojis": ["🎦"], "color": "grey", "effect": "", "facing": ""},
  {"word": "circle", "emojis": ["🔴", "🟠", "🟡", "🟢", "🔵", "🟣", "🟤", "⚫", "⚪"], "color": "pink", "effect": "", "facing": ""},
  {"word": "citrus", "emojis": ["🍋", "🍋‍🟩", "🍊"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "clap", "emoji": "👏", "color": "", "effect": "", "facing": ""},
  {"word": "clear", "emojis": ["🏁", "✨"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "clean", "emojis": ["🧹", "🧺", "🧻", "🪣", "🧼", "🫧", "🪥", "🧽"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "clip", "emojis": ["📎", "🖇️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "climb", "emojis": ["🧗", "🧗‍♂️", "🧗‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "clock", "emojis": ["⌚", "⏰", "⏱️", "⏲️", "🕰️", "🕛", "🕧", "🕐", "🕜", "🕑", "🕝", "🕒", "🕞", "🕟", "🕔", "🕠", "🕕", "🕡", "🕖", "🕢", "🕗", "🕣", "🕘", "🕤", "╏", "🕥", "⑪", "🕦"], "color": "grey", "effect": "", "facing": ""},
  {"word": "clothes", "emojis": ["👔", "👕", "👖", "🧥", "👚"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "clover", "emojis": ["☘️", "🍀"], "color": "green", "effect": "rain", "facing": ""},
  {"word": "clown", "emojis": ["🤡"], "color": "", "effect": "", "facing": ""},
  {"word": "club", "emojis": ["♣️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "cloud", "emojis": ["☁️", "⛅", "🌤️", "🌥️", "🌦️"], "color": "white", "effect": "", "facing": ""},
  {"word": "coach", "emojis": ["🚎"], "color": "yellow", "effect": "cross", "facing": "left"},
  {"word": "coat", "emojis": ["🧥", "🧣", "🧤"], "color": "white", "effect": "", "facing": ""},
  {"word": "cocktail", "emojis": ["🍸", "🍹"], "color": "pink", "effect": "", "facing": ""},
  {"word": "coconut", "emojis": ["🥥"], "color": "brown", "effect": "", "facing": ""},
  {"word": "coder", "emojis": ["🧑‍💻", "👨‍💻", "👩‍💻"], "color": "", "effect": "", "facing": ""},
  {"word": "coffee", "emojis": ["☕"], "color": "brown", "effect": "", "facing": ""},
  {"word": "coin", "emojis": ["🪙"], "color": "yellow", "effect": "rain", "facing": ""},
  {"word": "cold", "emoji": "🥶", "color": "", "effect": "", "facing": ""},
  {"word": "comet", "emojis": ["☄️"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "comb", "emojis": ["🪮"], "color": "brown", "effect": "", "facing": ""},
  {"word": "compass", "emojis": ["🧭"], "color": "grey", "effect": "", "facing": ""},
  {"word": "computer", "emojis": ["💻", "🖥️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "congrats", "emojis": ["㊗️"], "color": "red", "effect": "up", "facing": ""},
  {"word": "cookie", "emojis": ["🍪"], "color": "brown", "effect": "rain", "facing": ""},
  {"word": "cool", "emoji": "😎", "color": "", "effect": "", "facing": ""},
  {"word": "cool", "emojis": ["🕶️"], "color": "black", "effect": "", "facing": ""},
  {"word": "coral", "emojis": ["🪸"], "color": "pink", "effect": "", "facing": ""},
  {"word": "corner", "emojis": ["↗️", "↘️", "↙️", "↖️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "corn", "emojis": ["🌽"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "couch", "emojis": ["🛋️"], "color": "brown", "effect": "", "facing": ""},
  {"word": "couple", "emojis": ["🧑‍🤝‍🧑", "👭", "👫", "👬"], "color": "", "effect": "", "facing": ""},
  {"word": "cowboy", "emoji": "🤠", "color": "", "effect": "", "facing": ""},
  {"word": "cow", "emojis": ["🐮", "🐄", "🦬", "🐂", "🐃"], "color": "white", "effect": "", "facing": ""},
  {"word": "crab", "emojis": ["🦀"], "color": "red", "effect": "", "facing": ""},
  {"word": "crane", "emojis": ["🏗️", "🚧"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "crazy", "emoji": "😜", "color": "", "effect": "", "facing": ""},
  {"word": "cricket", "emojis": ["🦗"], "color": "green", "effect": "", "facing": ""},
  {"word": "cricket", "emojis": ["🏏"], "color": "brown", "effect": "", "facing": ""},
  {"word": "crocodile", "emojis": ["🐊"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "cross", "emoji": "🤞", "color": "", "effect": "", "facing": ""},
  {"word": "crown", "emojis": ["🫅", "🤴", "👸"], "color": "", "effect": "", "facing": ""},
  {"word": "crown", "emojis": ["👑"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "cry", "emoji": "😭", "color": "", "effect": "", "facing": ""},
  {"word": "cry", "emojis": ["😿"], "color": "blue", "effect": "", "facing": ""},
  {"word": "crysmile", "emoji": "🥲", "color": "", "effect": "", "facing": ""},
  {"word": "cucumber", "emojis": ["🥒"], "color": "green", "effect": "", "facing": ""},
  {"word": "curly", "emojis": ["🧑‍🦱", "👨‍🦱", "👩‍🦱"], "color": "", "effect": "", "facing": ""},
  {"word": "curse", "emoji": "🤬", "color": "", "effect": "", "facing": ""},
  {"word": "curry", "emojis": ["🍛"], "color": "orange", "effect": "", "facing": ""},
  {"word": "cyber", "emojis": ["🦾", "🦿"], "color": "grey", "effect": "", "facing": ""},
  {"word": "cycle", "emojis": ["🚲", "🛵"], "color": "orange", "effect": "cross", "facing": "left"},

  // === D ===
  {"word": "dagger", "emojis": ["🗡️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "dance", "emojis": ["🧑‍🩰", "💃", "🕺"], "color": "", "effect": "", "facing": ""},
  {"word": "danger", "emojis": ["☠️"], "color": "red", "effect": "", "facing": ""},
  {"word": "dango", "emojis": ["🍡"], "color": "pink", "effect": "", "facing": ""},
  {"word": "dash", "emojis": ["💨"], "color": "grey", "effect": "", "facing": ""},
  {"word": "dead", "emoji": "😵", "color": "", "effect": "", "facing": ""},
  {"word": "deaf", "emojis": ["🙈"], "color": "brown", "effect": "", "facing": ""},
  {"word": "deaf", "emojis": ["🧏", "🧏‍♂️", "🧏‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "deafen", "emojis": ["🙉"], "color": "brown", "effect": "", "facing": ""},
  {"word": "deco", "emojis": ["💟"], "color": "purple", "effect": "", "facing": ""},
  {"word": "deer", "emojis": ["🦌", "🫎"], "color": "brown", "effect": "cross", "facing": "left"},
  {"word": "demon", "emojis": ["👿"], "color": "purple", "effect": "", "facing": ""},
  {"word": "desert", "emojis": ["🏜️"], "color": "orange", "effect": "", "facing": ""},
  {"word": "desk", "emojis": ["💁", "💁‍♂️", "💁‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "devil", "emojis": ["😈"], "color": "purple", "effect": "", "facing": ""},
  {"word": "diamond", "emojis": ["♦️"], "color": "red", "effect": "", "facing": ""},
  {"word": "diamond", "emojis": ["🔶", "🔷", "🔸", "🔹", "💠"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "dino", "emojis": ["🦕", "Rex"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "dinosaur", "emojis": ["🦕", "🦖"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "disc", "emojis": ["🥏"], "color": "cyan", "effect": "cross", "facing": "left"},
  {"word": "disco", "emojis": ["🪩"], "color": "grey", "effect": "rain", "facing": ""},
  {"word": "disk", "emojis": ["💽", "💾", "💿", "📀"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "dizzy", "emoji": "🥴", "color": "", "effect": "", "facing": ""},
  {"word": "dizzy", "emojis": ["💫"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "dna", "emojis": ["🧬"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "doctor", "emojis": ["🧑‍⚕️", "👨‍⚕️", "👩‍⚕️"], "color": "", "effect": "", "facing": ""},
  {"word": "dodo", "emojis": ["🦤"], "color": "brown", "effect": "", "facing": ""},
  {"word": "dog", "emojis": ["🐶", "🐕", "🦮", "🐕‍🦺", "🐩"], "color": "brown", "effect": "", "facing": ""},
  {"word": "doll", "emojis": ["🎎"], "color": "pink", "effect": "", "facing": ""},
  {"word": "dolphin", "emojis": ["🐬"], "color": "cyan", "effect": "cross", "facing": "left"},
  {"word": "donkey", "emojis": ["🫏"], "color": "grey", "effect": "", "facing": ""},
  {"word": "donut", "emojis": ["🍩"], "color": "pink", "effect": "", "facing": ""},
  {"word": "door", "emojis": ["🚪"], "color": "brown", "effect": "", "facing": ""},
  {"word": "dot", "emoji": "🫥", "color": "", "effect": "", "facing": ""},
  {"word": "dot", "emojis": ["🔘"], "color": "grey", "effect": "", "facing": ""},
  {"word": "dove", "emojis": ["🕊️"], "color": "white", "effect": "up", "facing": ""},
  {"word": "downcast", "emoji": "😞", "color": "", "effect": "", "facing": ""},
  {"word": "down", "emoji": "👇", "color": "", "effect": "", "facing": ""},
  {"word": "down", "emojis": ["⬇️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "dragon", "emojis": ["🐲", "🐉"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "dress", "emojis": ["👗", "👘", "🥻"], "color": "pink", "effect": "", "facing": ""},
  {"word": "drink", "emojis": ["🍼", "🥛", "☕", "🫖", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥤", "🧋", "🧃"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "drive", "emojis": ["🚗", "🚘", "🛣️"], "color": "red", "effect": "cross", "facing": "left"},
  {"word": "drool", "emoji": "🤤", "color": "", "effect": "", "facing": ""},
  {"word": "drum", "emojis": ["🥁", "🪘", "🪇", "🪉"], "color": "red", "effect": "", "facing": ""},
  {"word": "duck", "emojis": ["🦆"], "color": "green", "effect": "", "facing": ""},
  {"word": "dumpling", "emojis": ["🥟"], "color": "white", "effect": "", "facing": ""},

  // === E ===
  {"word": "eagle", "emojis": ["🦅"], "color": "brown", "effect": "cross", "facing": "left"},
  {"word": "ear", "emojis": ["👂", "🦻"], "color": "", "effect": "", "facing": ""},
  {"word": "earth", "emojis": ["🌍", "🌎", "🌏"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "eggplant", "emojis": ["🍆"], "color": "purple", "effect": "", "facing": ""},
  {"word": "egg", "emojis": ["🥚", "🍳"], "color": "white", "effect": "", "facing": ""},
  {"word": "eight", "emojis": ["🕗", "🕣"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "eight", "emojis": ["8️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "elder", "emojis": ["🧓", "👴", "👵"], "color": "", "effect": "", "facing": ""},
  {"word": "elephant", "emojis": ["🐘", "🦣"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "elevator", "emojis": ["🛗"], "color": "grey", "effect": "up", "facing": ""},
  {"word": "eleven", "emojis": ["⑪", "🕦"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "elf", "emojis": ["🧝", "🧝‍♂️", "🧝‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "end", "emojis": ["end"], "color": "grey", "effect": "", "facing": ""},
  {"word": "endure", "emoji": "😣", "color": "", "effect": "", "facing": ""},
  {"word": "engine", "emojis": ["🧑‍🚒", "👨‍🚒", "👩‍🚒"], "color": "", "effect": "", "facing": ""},
  {"word": "envelope", "emojis": ["🧧"], "color": "red", "effect": "", "facing": ""},
  {"word": "evil", "emojis": ["😈", "👿"], "color": "purple", "effect": "", "facing": ""},
  {"word": "exclamation", "emojis": ["❣️"], "color": "red", "effect": "", "facing": ""},
  {"word": "exhaust", "emoji": "😫", "color": "", "effect": "", "facing": ""},
  {"word": "extinguisher", "emojis": ["🧯"], "color": "red", "effect": "", "facing": ""},
  {"word": "eye", "emojis": ["👁️", "👀"], "color": "", "effect": "", "facing": ""},

  // === F ===
  {"word": "facepalm", "emojis": ["🤦", "🤦‍♂️", "🤦‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "factory", "emojis": ["🧑‍🏭", "👨‍🏭", "👩‍🏭"], "color": "", "effect": "", "facing": ""},
  {"word": "factory", "emojis": ["🏭"], "color": "grey", "effect": "", "facing": ""},
  {"word": "fairy", "emojis": ["🧚", "🧚‍♂️", "🧚‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "family", "emojis": ["👪", "🧑‍🧑‍🧒", "🧑‍🧑‍🧒‍🧒", "🧑‍🧒", "🧑‍🧒‍🧒", "👨‍👩‍👦", "👨‍👩‍👧", "👨‍👩‍👧‍👦", "👨‍👩‍👦‍👦", "👨‍👩‍👧‍👧", "👨‍👨‍👦", "👨‍👨‍👧", "👨‍👨‍👧‍👦", "👨‍👨‍👦‍👦", "👨‍👨‍👧‍👧", "👩‍👩‍👦", "👩‍👩‍👧", "👩‍👩‍👧‍👦", "👩‍👩‍👦‍👦", "👩‍👩‍👧‍👧", "👨‍👦", "👨‍👦‍👦", "👨‍👧", "👨‍👧‍👦", "👨‍👧‍👧", "👩‍👦", "👩‍👦‍👦", "👩‍👧", "👩‍👧‍👦", "👩‍👧‍👧"], "color": "", "effect": "", "facing": ""},
  {"word": "fan", "emojis": ["🪭"], "color": "red", "effect": "", "facing": ""},
  {"word": "farmer", "emojis": ["🧑‍🌾", "👨‍🌾", "👩‍🌾"], "color": "", "effect": "", "facing": ""},
  {"word": "fax", "emojis": ["📠"], "color": "grey", "effect": "", "facing": ""},
  {"word": "feather", "emojis": ["🪶"], "color": "grey", "effect": "rain", "facing": ""},
  {"word": "feed", "emojis": ["🤱", "🧑‍🍼", "👨‍🍼", "👩‍🍼"], "color": "", "effect": "", "facing": ""},
  {"word": "fencing", "emojis": ["🤺"], "color": "", "effect": "", "facing": ""},
  {"word": "fireworks", "emojis": ["🎆", "🎇", "🧨"], "color": "pink", "effect": "up", "facing": ""},
  {"word": "fire", "emojis": ["❤️‍🔥"], "color": "orange", "effect": "", "facing": ""},
  {"word": "fire", "emojis": ["🔥"], "color": "red", "effect": "up", "facing": ""},
  {"word": "fire", "emojis": ["🔥", "🧯"], "color": "red", "effect": "up", "facing": ""},
  {"word": "firetruck", "emojis": ["🚒"], "color": "red", "effect": "cross", "facing": "left"},
  {"word": "fish", "emojis": ["🐟", "🐠", "🐡"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "fishcake", "emojis": ["🍥"], "color": "pink", "effect": "", "facing": ""},
  {"word": "fist", "emoji": "✊", "color": "", "effect": "", "facing": ""},
  {"word": "fistleft", "emoji": "🤛", "color": "", "effect": "", "facing": ""},
  {"word": "fistright", "emoji": "🤜", "color": "", "effect": "", "facing": ""},
  {"word": "five", "emojis": ["🕔", "🛕"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "five", "emojis": ["5️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "flag", "emojis": ["🏁", "🚩", "🎌", "🏴", "🏳️", "🏳️‍🌈", "🏳️‍⚧️"], "color": "white", "effect": "rain", "facing": ""},
  {"word": "flamingo", "emojis": ["🦩"], "color": "pink", "effect": "", "facing": ""},
  {"word": "flute", "emojis": ["🪈"], "color": "brown", "effect": "", "facing": ""},
  {"word": "fly", "emojis": ["🪰"], "color": "black", "effect": "", "facing": ""},
  {"word": "fodder", "emojis": ["🌾"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "fog", "emoji": "😶‍🌫️", "color": "", "effect": "", "facing": ""},
  {"word": "fog", "emojis": ["🌫️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "folder", "emojis": ["📁", "📂", "🗂️"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "foot", "emojis": ["🦶"], "color": "", "effect": "", "facing": ""},
  {"word": "forest", "emojis": ["🌲", "🌳"], "color": "green", "effect": "", "facing": ""},
  {"word": "fork", "emojis": ["🍴", "🥄"], "color": "grey", "effect": "", "facing": ""},
  {"word": "fortune", "emojis": ["🥠"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "fountain", "emojis": [" fountains"], "color": "cyan", "effect": "up", "facing": ""},
  {"word": "fountainpen", "emojis": ["✒️", "🖋️"], "color": "black", "effect": "", "facing": ""},
  {"word": "four", "emojis": ["🕓", "🕟"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "four", "emojis": ["4️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "fox", "emojis": ["🦊"], "color": "orange", "effect": "", "facing": ""},
  {"word": "fries", "emojis": ["🍟"], "color": "red", "effect": "", "facing": ""},
  {"word": "frog", "emojis": ["🐸"], "color": "green", "effect": "", "facing": ""},
  {"word": "frown", "emoji": "🙁", "color": "", "effect": "", "facing": ""},
  {"word": "frown", "emojis": ["🙍", "🙍‍♂️", "🙍‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "fruit", "emojis": ["🍇", "🍈", "🍉", "🍊", "🍋", "🍌", "🍍", "🥭", "🍎", "🍏", "🍉", "🍒", "🍓", "🫐", "🥝"], "color": "yellow", "effect": "rain", "facing": ""},
  {"word": "fuck", "emoji": "🖕", "color": "", "effect": "", "facing": ""},
  {"word": "fuji", "emojis": ["🗻"], "color": "blue", "effect": "up", "facing": ""},

  // === G ===
  {"word": "galaxy", "emojis": ["🌌"], "color": "purple", "effect": "", "facing": ""},
  {"word": "game", "emojis": ["🎮", "🕹️", "🎰", "🎲", "🧩"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "garlic", "emojis": ["🧄"], "color": "white", "effect": "", "facing": ""},
  {"word": "gas", "emojis": ["⛽"], "color": "red", "effect": "", "facing": ""},
  {"word": "gasp", "emoji": "🤭", "color": "", "effect": "", "facing": ""},
  {"word": "gasp2", "emoji": "😦", "color": "", "effect": "", "facing": ""},
  {"word": "gear", "emojis": ["⚙️"], "color": "grey", "effect": "rain", "facing": ""},
  {"word": "gem", "emojis": ["💎"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "gender", "emojis": ["♀️", "♂️", "⚧️"], "color": "pink", "effect": "", "facing": ""},
  {"word": "genie", "emojis": ["🧞", "🧞‍♂️", "🧞‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "germ", "emojis": ["🦠"], "color": "green", "effect": "", "facing": ""},
  {"word": "gi", "emojis": ["🥋"], "color": "white", "effect": "", "facing": ""},
  {"word": "gift", "emojis": ["🎀", "🎁", "🎗️"], "color": "red", "effect": "", "facing": ""},
  {"word": "giggle", "emoji": "😁", "color": "", "effect": "", "facing": ""},
  {"word": "ginger", "emojis": ["🫚"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "giraffe", "emojis": ["🦒"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "girl", "emojis": ["👧"], "color": "", "effect": "", "facing": ""},
  {"word": "glass", "emoji": "🧐", "color": "", "effect": "", "facing": ""},
  {"word": "glass", "emojis": ["🥃", "🫗"], "color": "grey", "effect": "", "facing": ""},
  {"word": "glasses", "emojis": ["👓", "🕶️", "🥽"], "color": "grey", "effect": "", "facing": ""},
  {"word": "globe", "emojis": ["🌍", "🌎", "🌏", "🌐"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "goat", "emojis": ["🐐"], "color": "white", "effect": "cross", "facing": "left"},
  {"word": "goblin", "emojis": ["👺"], "color": "red", "effect": "", "facing": ""},
  {"word": "goal", "emojis": ["🥅"], "color": "white", "effect": "", "facing": ""},
  {"word": "goal", "emojis": ["🏁", "🚩"], "color": "white", "effect": "up", "facing": ""},
  {"word": "golf", "emojis": ["🏌️", "🏌️‍♂️", "🏌️‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "golf", "emojis": ["⛳"], "color": "green", "effect": "", "facing": ""},
  {"word": "good", "emoji": "👍", "color": "", "effect": "", "facing": ""},
  {"word": "goose", "emojis": ["🪿"], "color": "white", "effect": "", "facing": ""},
  {"word": "gorilla", "emojis": ["🦍"], "color": "grey", "effect": "", "facing": ""},
  {"word": "grad", "emojis": ["🎓"], "color": "purple", "effect": "up", "facing": ""},
  {"word": "grape", "emojis": ["🍇"], "color": "purple", "effect": "", "facing": ""},
  {"word": "grave", "emojis": ["⚰️", "🪦", "⚱️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "green", "emojis": ["💚"], "color": "green", "effect": "", "facing": ""},
  {"word": "green", "emojis": ["🟢", "🟩", "☘️", "🍀"], "color": "green", "effect": "", "facing": ""},
  {"word": "grimace", "emoji": "😬", "color": "", "effect": "", "facing": ""},
  {"word": "grinning", "emoji": "😀", "color": "", "effect": "", "facing": ""},
  {"word": "grow", "emojis": ["💗"], "color": "", "effect": "", "facing": ""},
  {"word": "guard", "emojis": ["💂", "💂‍♂️", "💂‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "guitar", "emojis": ["🎸", "🪕"], "color": "red", "effect": "", "facing": ""},
  {"word": "guitar", "emojis": ["🎸", "🪕"], "color": "red", "effect": "", "facing": ""}, // 重複維持
  {"word": "gun", "emojis": ["🔫"], "color": "green", "effect": "cross", "facing": "right"},
  {"word": "ghost", "emojis": ["👻"], "color": "white", "effect": "up", "facing": ""},

  // === H ===
  {"word": "haircut", "emojis": ["💇", "💇‍♂️", "💇‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "halloween", "emojis": ["🎃"], "color": "orange", "effect": "", "facing": ""},
  {"word": "hamburger", "emojis": ["🍔"], "color": "orange", "effect": "", "facing": ""},
  {"word": "hammer", "emojis": ["🔨", "⚒️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "hamster", "emojis": ["🐹"], "color": "orange", "effect": "", "facing": ""},
  {"word": "hanafuda", "emojis": ["🎴"], "color": "red", "effect": "", "facing": ""},
  {"word": "handball", "emojis": ["🤾", "🤾‍♂️", "🤾‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "happy", "emoji": "😄", "color": "", "effect": "", "facing": ""},
  {"word": "happy", "emojis": ["😸", "😺"], "color": "orange", "effect": "", "facing": ""},
  {"word": "hash", "emojis": ["#️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "hat", "emojis": ["👒", "🎩", "🎓", "🧢"], "color": "blue", "effect": "", "facing": ""},
  {"word": "headphone", "emojis": ["🎧"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "hear", "emojis": ["👂", "🦻"], "color": "", "effect": "", "facing": ""},
  {"word": "hearingaid", "emojis": ["🦻"], "color": "", "effect": "", "facing": ""},
  {"word": "heart", "emojis": ["💌", "💘", "💝", "💖", "💗", "💓", "💞", "💕", "💟", "❣️", "💔", "❤️‍🔥", "❤️‍🩹", "❤️", "🩷", "🧡", "💛", "💚", "💙", "🩵", "💜", "🤎", "🖤", "🩶", "White"], "color": "", "effect": "", "facing": ""},
  {"word": "heart", "emojis": ["♥️"], "color": "red", "effect": "", "facing": ""},
  {"word": "hearthand", "emoji": "🫶", "color": "", "effect": "", "facing": ""},
  {"word": "hearts", "emoji": "🥰", "color": "", "effect": "", "facing": ""},
  {"word": "hearts", "emojis": ["💕"], "color": "", "effect": "", "facing": ""},
  {"word": "hedghog", "emojis": ["🦔"], "color": "brown", "effect": "", "facing": ""},
  {"word": "heel", "emojis": ["👠"], "color": "red", "effect": "", "facing": ""},
  {"word": "helicopter", "emojis": ["🚁"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "hell", "emojis": ["👿", "😈"], "color": "red", "effect": "up", "facing": ""},
  {"word": "helmet", "emojis": ["👷", "👷‍♂️", "👷‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "helmet", "emojis": ["🪖", "⛑️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "herb", "emojis": ["🌿"], "color": "green", "effect": "", "facing": ""},
  {"word": "hero", "emojis": ["🦸", "🦸‍♂️", "🦸‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "hibiscus", "emojis": ["🌺"], "color": "red", "effect": "", "facing": ""},
  {"word": "hide", "emojis": ["🙈"], "color": "brown", "effect": "", "facing": ""},
  {"word": "hippo", "emojis": ["🦛"], "color": "grey", "effect": "", "facing": ""},
  {"word": "hm", "emoji": "🤨", "color": "", "effect": "", "facing": ""},
  {"word": "hockey", "emojis": ["🏑", "🏒", "🥍"], "color": "grey", "effect": "", "facing": ""},
  {"word": "holdon", "emoji": "🥹", "color": "", "effect": "", "facing": ""},
  {"word": "hole", "emojis": ["🕳️"], "color": "black", "effect": "", "facing": ""},
  {"word": "home", "emojis": ["🏠", "🏡"], "color": "orange", "effect": "", "facing": ""},
  {"word": "honey", "emojis": ["🍯"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "hook", "emojis": ["🪝"], "color": "grey", "effect": "", "facing": ""},
  {"word": "horn", "emojis": ["📯"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "horn", "emojis": ["🎷", "🎺"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "horse", "emojis": ["🐴", "🐎"], "color": "brown", "effect": "cross", "facing": "left"},
  {"word": "hose", "emojis": ["🧯"], "color": "red", "effect": "", "facing": ""},
  {"word": "hospital", "emojis": ["🏥"], "color": "red", "effect": "", "facing": ""},
  {"word": "hotdog", "emojis": ["🌭"], "color": "orange", "effect": "", "facing": ""},
  {"word": "hot", "emoji": "🥵", "color": "", "effect": "", "facing": ""},
  {"word": "hourglass", "emojis": ["⌛", "⏳"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "house", "emojis": ["🛖", "🏘️", "🏚️", "🏠", "🏡"], "color": "orange", "effect": "", "facing": ""},
  {"word": "hug", "emoji": "🤗", "color": "", "effect": "", "facing": ""},
  {"word": "hug", "emojis": ["🫂"], "color": "", "effect": "", "facing": ""},
  {"word": "huh", "emoji": "😕", "color": "", "effect": "", "facing": ""},
  {"word": "hurt", "emoji": "🤕", "color": "", "effect": "", "facing": ""},
  {"word": "hurt", "emojis": ["❤️‍🩹"], "color": "", "effect": "", "facing": ""},
  {"word": "hyacinth", "emojis": ["🪻"], "color": "purple", "effect": "", "facing": ""},

  // === I ===
  {"word": "icecream", "emojis": ["🍦", "🍧", "🍨"], "color": "pink", "effect": "", "facing": ""},
  {"word": "ice", "emojis": ["🧊"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "ily", "emoji": "🤟", "color": "", "effect": "", "facing": ""},
  {"word": "info", "emojis": ["ℹ️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "invader", "emojis": ["👾"], "color": "purple", "effect": "", "facing": ""},
  {"word": "island", "emojis": ["🏝️"], "color": "cyan", "effect": "", "facing": ""},

  // === J ===
  {"word": "japan", "emojis": [" Bento", "🍙", "🍚", "🍛", "🍢", "🍣", "🍤", "🍥", "🍡"], "color": "red", "effect": "", "facing": ""},
  {"word": "jeans", "emojis": ["👖"], "color": "blue", "effect": "", "facing": ""},
  {"word": "jellyfish", "emojis": ["🪼"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "joker", "emojis": ["🃏"], "color": "purple", "effect": "up", "facing": ""},
  {"word": "jockey", "emojis": ["🏇"], "color": "", "effect": "", "facing": ""},
  {"word": "joyful", "emoji": "😃", "color": "", "effect": "", "facing": ""},
  {"word": "joy", "emojis": ["😹"], "color": "orange", "effect": "", "facing": ""},
  {"word": "judge", "emojis": ["🧑‍⚖️", "👨‍⚖️", "👩‍⚖️"], "color": "", "effect": "", "facing": ""},
  {"word": "juggle", "emojis": ["🤹", "🤹‍♂️", "🤹‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "juice", "emojis": ["🧃", "🥤", "🍹"], "color": "orange", "effect": "", "facing": ""},

  // === K ===
  {"word": "kadomatsu", "emojis": ["🎍"], "color": "green", "effect": "", "facing": ""},
  {"word": "kangaroo", "emojis": ["🦘"], "color": "orange", "effect": "cross", "facing": "left"},
  {"word": "karate", "emojis": ["🥋"], "color": "white", "effect": "", "facing": ""},
  {"word": "keyboard", "emojis": ["⌨️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "key", "emojis": ["🔑", "🗝️"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "kimono", "emojis": ["👘"], "color": "red", "effect": "", "facing": ""},
  {"word": "kiss", "emoji": "😘", "color": "", "effect": "", "facing": ""},
  {"word": "kiss", "emojis": ["😽"], "color": "pink", "effect": "", "facing": ""},
  {"word": "kiss", "emojis": ["💋"], "color": "red", "effect": "", "facing": ""},
  {"word": "kiss", "emojis": ["💏", "👩‍❤️‍💋‍👨", "👨‍❤️‍💋‍👨", "👩‍❤️‍💋‍👩"], "color": "", "effect": "", "facing": ""},
  {"word": "kiwi", "emojis": ["🥝"], "color": "green", "effect": "", "facing": ""},
  {"word": "kneel", "emojis": ["🧎", "🧎‍♂️", "🧎‍♀️", "🧎‍➡️", "🧎‍♂️‍➡️", "🧎‍♀️‍➡️"], "color": "", "effect": "", "facing": ""},
  {"word": "knife", "emojis": ["🔪"], "color": "grey", "effect": "", "facing": ""},
  {"word": "koala", "emojis": ["🐨"], "color": "grey", "effect": "", "facing": ""},

  // === L ===
  {"word": "lab", "emojis": ["⚗️", "🧪", "🧫"], "color": "purple", "effect": "", "facing": ""},
  {"word": "lab", "emojis": ["⚗️", "🧪", "🧫"], "color": "purple", "effect": "", "facing": ""}, // 重複維持
  {"word": "ladder", "emojis": ["🪜"], "color": "brown", "effect": "up", "facing": ""},
  {"word": "laugh", "emoji": "😆", "color": "", "effect": "", "facing": ""},
  {"word": "laugh", "emojis": ["😹", "😸"], "color": "orange", "effect": "", "facing": ""},
  {"word": "leaf", "emojis": ["🍁", "🍂", "🍃"], "color": "orange", "effect": "rain", "facing": ""},
  {"word": "left", "emoji": "👈", "color": "", "effect": "", "facing": ""},
  {"word": "left", "emojis": ["⬅️"], "color": "cyan", "effect": "cross", "facing": "left"},
  {"word": "lefthand", "emoji": "🫲", "color": "", "effect": "", "facing": ""},
  {"word": "leg", "emojis": ["🦵", "🦿"], "color": "", "effect": "", "facing": ""},
  {"word": "lemon", "emojis": ["🍋"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "leopard", "emojis": ["🐆"], "color": "yellow", "effect": "cross", "facing": "left"},
  {"word": "letter", "emojis": ["💌"], "color": "", "effect": "", "facing": ""},
  {"word": "levitate", "emojis": ["🕴️"], "color": "", "effect": "", "facing": ""},
  {"word": "liar", "emoji": "🤥", "color": "", "effect": "", "facing": ""},
  {"word": "liberty", "emojis": ["🗽"], "color": "cyan", "effect": "up", "facing": ""},
  {"word": "light", "emojis": ["🚥", "🚦"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "light", "emojis": ["🕯️", "💡", "🔦", "🏮", "🪔"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "lightning", "emojis": ["⚡"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "lime", "emojis": ["🍋‍🟩"], "color": "green", "effect": "", "facing": ""},
  {"word": "link", "emojis": ["🔗"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "lion", "emojis": ["🦁"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "lip", "emojis": ["👄", "🫦"], "color": "red", "effect": "", "facing": ""},
  {"word": "lips", "emojis": ["💋"], "color": "red", "effect": "", "facing": ""},
  {"word": "listen", "emojis": ["👂"], "color": "", "effect": "", "facing": ""},
  {"word": "lipstick", "emojis": ["💄"], "color": "red", "effect": "", "facing": ""},
  {"word": "live", "emojis": ["🎙️", "🎤"], "color": "pink", "effect": "up", "facing": ""},
  {"word": "lizard", "emojis": ["🦎"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "llama", "emojis": ["🦙"], "color": "white", "effect": "", "facing": ""},
  {"word": "lock", "emojis": ["🔒", "🔓", "🔏", "🔐"], "color": "grey", "effect": "", "facing": ""},
  {"word": "lock", "emojis": ["🔒", "🔏", "🔐"], "color": "grey", "effect": "", "facing": ""}, // 重複維持
  {"word": "look", "emojis": ["👀", "👁️"], "color": "", "effect": "", "facing": ""},
  {"word": "loop", "emojis": ["🔃", "🔄"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "lotion", "emojis": ["🧴"], "color": "white", "effect": "", "facing": ""},
  {"word": "love", "emoji": "😍", "color": "", "effect": "", "facing": ""},
  {"word": "love", "emojis": ["😻"], "color": "pink", "effect": "", "facing": ""},
  {"word": "love", "emojis": ["💑", "👩‍❤️‍👨", "👨‍❤️‍👨", "👩‍❤️‍👩"], "color": "", "effect": "", "facing": ""},
  {"word": "lucky", "emojis": ["🍀"], "color": "green", "effect": "", "facing": ""},
  {"word": "luggage", "emojis": ["𧣳"], "color": "brown", "effect": "", "facing": ""},
  {"word": "lung", "emojis": ["🫁"], "color": "red", "effect": "", "facing": ""},

  // === M ===
  {"word": "mad", "emoji": "😤", "color": "", "effect": "", "facing": ""},
  {"word": "mad", "emojis": ["😾"], "color": "red", "effect": "", "facing": ""},
  {"word": "mad", "emojis": ["💢"], "color": "red", "effect": "", "facing": ""},
  {"word": "mage", "emojis": ["🧙", "🧙‍♂️", "🧙‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "magic", "emojis": ["🔮", "🪄"], "color": "purple", "effect": "", "facing": ""},
  {"word": "magnet", "emojis": ["🧲"], "color": "red", "effect": "", "facing": ""},
  {"word": "mail", "emojis": ["✉️", "📧", "📨", "📩", "📤", "📥", "📫", "📪", "📬", "📭", "📮"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "mammoth", "emojis": ["🦣"], "color": "brown", "effect": "cross", "facing": "left"},
  {"word": "mango", "emojis": ["🥭"], "color": "orange", "effect": "", "facing": ""},
  {"word": "map", "emojis": ["🗺️", "🗾"], "color": "brown", "effect": "", "facing": ""},
  {"word": "marker", "emojis": ["🖍️"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "mark", "emojis": ["‼️", "⁉️", "❓", "❔", "❕", "❗", "〰️"], "color": "red", "effect": "up", "facing": ""},
  {"word": "mask", "emoji": "😷", "color": "", "effect": "", "facing": ""},
  {"word": "massage", "emojis": ["💆", "💆‍♂️", "💆‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "material", "emojis": ["🧱", "🪨", "🪵"], "color": "brown", "effect": "", "facing": ""},
  {"word": "math", "emojis": ["✖️", "➕", "➖", "➗", "🟰", "♾️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "mouth", "emojis": ["👄"], "color": "red", "effect": "", "facing": ""},
  {"word": "mecha", "emojis": ["🦾", "🦿"], "color": "grey", "effect": "", "facing": ""},
  {"word": "medal", "emojis": ["🎖️", "🏆", "🏅", "🥇", "🥈", "🥉"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "medical", "emojis": ["💉", "🩸", "💊", "🩹", "🩼", "🩺", "🩻"], "color": "red", "effect": "", "facing": ""},
  {"word": "medicine", "emojis": ["💊", "🩹"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "meh", "emoji": "🫤", "color": "", "effect": "", "facing": ""},
  {"word": "melon", "emojis": ["🍈"], "color": "green", "effect": "", "facing": ""},
  {"word": "melt", "emoji": "🫠", "color": "", "effect": "", "facing": ""},
  {"word": "memo", "emojis": ["📝", "🗒️", "📋"], "color": "white", "effect": "", "facing": ""},
  {"word": "merfolk", "emojis": ["🧜", "🧜‍♂️", "🧜‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "metro", "emojis": ["Ⓜ️"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "mic", "emojis": ["🎤"], "color": "pink", "effect": "", "facing": ""},
  {"word": "microscope", "emojis": ["🔬"], "color": "grey", "effect": "", "facing": ""},
  {"word": "milk", "emojis": ["🍼", "🥛"], "color": "white", "effect": "", "facing": ""},
  {"word": "mirror", "emojis": ["🪞"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "moai", "emojis": ["🗿"], "color": "grey", "effect": "up", "facing": ""},
  {"word": "money", "emoji": "🤑", "color": "", "effect": "", "facing": ""},
  {"word": "money", "emojis": ["🪙", "💰", "💴", "💵", "💶", "💷", "💸"], "color": "yellow", "effect": "rain", "facing": ""},
  {"word": "money", "emojis": ["🪙", "💰", "💴", "💵", "💱", "💲"], "color": "yellow", "effect": "rain", "facing": ""}, // 重複維持
  {"word": "monkey", "emojis": ["🙈", "🙉", "🙊"], "color": "brown", "effect": "", "facing": ""},
  {"word": "monkey", "emojis": ["🐵", "🐒"], "color": "brown", "effect": "", "facing": ""}, // 重複維持
  {"word": "monster", "emojis": ["👹", "👺", "👻", "👽", "👾", "👿"], "color": "purple", "effect": "", "facing": ""},
  {"word": "moon", "emojis": ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘", "🌙", "🌚", "🌛", "🌜", "🌝"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "moon", "emojis": ["🈷️"], "color": "yellow", "effect": "", "facing": ""}, // 重複維持
  {"word": "moose", "emojis": ["🫎"], "color": "brown", "effect": "", "facing": ""},
  {"word": "mosquito", "emojis": ["🦟"], "color": "red", "effect": "", "facing": ""},
  {"word": "mountain", "emojis": ["🏔️", "⛰️", "🗻"], "color": "white", "effect": "up", "facing": ""},
  {"word": "mouse", "emojis": ["🐭", "🐁", "🐀"], "color": "grey", "effect": "", "facing": ""},
  {"word": "mouse", "emojis": ["🖱️", "🖲️"], "color": "grey", "effect": "", "facing": ""}, // 重複維持
  {"word": "mtb", "emojis": ["🚵", "🚵‍♂️", "🚵‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "muah", "emoji": "😚", "color": "", "effect": "", "facing": ""},
  {"word": "muscle", "emojis": ["💪"], "color": "", "effect": "up", "facing": ""},
  {"word": "mushroom", "emojis": ["🍄", "🍄‍🟫"], "color": "red", "effect": "up", "facing": ""},
  {"word": "music", "emojis": ["🎼", "🎵", "🎶"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "music", "emojis": ["🎼", "🎵", "🎶"], "color": "cyan", "effect": "rain", "facing": ""}, // 重複維持
  {"word": "mute", "emojis": ["🙊"], "color": "brown", "effect": "", "facing": ""},
  {"word": "mute", "emojis": ["🔇", "🔕"], "color": "grey", "effect": "", "facing": ""}, // 重複維持
  {"word": "meat", "emojis": ["🍖", "🍗", "🥩", "🥓"], "color": "red", "effect": "", "facing": ""},

  // === N ===
  {"word": "nail", "emojis": ["💅"], "color": "", "effect": "", "facing": ""},
  {"word": "nausea", "emoji": "🤢", "color": "", "effect": "", "facing": ""},
  {"word": "nature", "emojis": ["🌲", "🌳", "🍃", "🌿"], "color": "green", "effect": "", "facing": ""},
  {"word": "nerd", "emoji": "🤓", "color": "", "effect": "", "facing": ""},
  {"word": "nervous", "emojis": ["🫦"], "color": "", "effect": "", "facing": ""},
  {"word": "nest", "emojis": ["🪹", "🪺"], "color": "brown", "effect": "", "facing": ""},
  {"word": "newyear", "emojis": ["🎍", "🧧"], "color": "red", "effect": "", "facing": ""},
  {"word": "news", "emojis": ["📰", "🗞️"], "color": "white", "effect": "", "facing": ""},
  {"word": "nine", "emojis": ["🕘", "🕤"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "nine", "emojis": ["9️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "ninja", "emojis": ["🥷"], "color": "", "effect": "", "facing": ""},
  {"word": "no", "emoji": "🙂‍↔️", "color": "", "effect": "", "facing": ""},
  {"word": "no", "emojis": ["🙅", "🙅‍♂️", "🙅‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "no", "emojis": ["⛔", "🚫", "🚳", "🚭", "🚯", "🚱", "🚷", "📵", "🔞"], "color": "red", "effect": "", "facing": ""},
  {"word": "noodle", "emojis": ["🍜", "🍝"], "color": "orange", "effect": "", "facing": ""},
  {"word": "nose", "emojis": ["👃"], "color": "", "effect": "", "facing": ""},
  {"word": "number", "emojis": ["#️⃣", "*️⃣", "0️⃣", "1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟"], "color": "blue", "effect": "", "facing": ""},
  {"word": "nut", "emojis": ["🥜", "🌰"], "color": "brown", "effect": "", "facing": ""},

  // === O ===
  {"word": "o", "emojis": ["🅾️"], "color": "red", "effect": "", "facing": ""},
  {"word": "octopus", "emojis": ["🐙"], "color": "red", "effect": "", "facing": ""},
  {"word": "oden", "emojis": ["🍢"], "color": "brown", "effect": "", "facing": ""},
  {"word": "office", "emojis": ["🧑‍💼", "👨‍💼", "👩‍💼"], "color": "", "effect": "", "facing": ""},
  {"word": "ogre", "emojis": ["👹"], "color": "red", "effect": "", "facing": ""},
  {"word": "ok", "emoji": "👌", "color": "", "effect": "", "facing": ""},
  {"word": "ok", "emojis": ["🙆", "🙆‍♂️", "🙆‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "olive", "emojis": ["🫒"], "color": "green", "effect": "", "facing": ""},
  {"word": "omg", "emoji": "😲", "color": "", "effect": "", "facing": ""},
  {"word": "on", "emojis": ["🔛"], "color": "grey", "effect": "", "facing": ""},
  {"word": "one", "emojis": ["🕐", "🕜"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "one", "emojis": ["1️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "onion", "emojis": ["🧅"], "color": "white", "effect": "", "facing": ""},
  {"word": "oops", "emoji": "🫢", "color": "", "effect": "", "facing": ""},
  {"word": "open", "emoji": "👐", "color": "", "effect": "", "facing": ""},
  {"word": "orange", "emojis": ["🧡"], "color": "orange", "effect": "", "facing": ""},
  {"word": "orange", "emojis": ["🍊"], "color": "orange", "effect": "", "facing": ""},
  {"word": "orange", "emojis": ["🟠", "🟧", "🔶", "🔸"], "color": "orange", "effect": "", "facing": ""},
  {"word": "orangutan", "emojis": ["🦧"], "color": "orange", "effect": "", "facing": ""},
  {"word": "organ", "emojis": ["🫀", "🫁"], "color": "red", "effect": "", "facing": ""},
  {"word": "otter", "emojis": ["🦦"], "color": "brown", "effect": "", "facing": ""},
  {"word": "owl", "emojis": ["🦉"], "color": "brown", "effect": "", "facing": ""},
  {"word": "ox", "emojis": ["🐂", "🐃"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "oyster", "emojis": ["🦪"], "color": "grey", "effect": "", "facing": ""},

  // === P ===
  {"word": "paint", "emojis": ["🎨", "🖼️"], "color": "pink", "effect": "", "facing": ""},
  {"word": "pain", "emoji": "😖", "color": "", "effect": "", "facing": ""},
  {"word": "palm", "emojis": ["🌴"], "color": "green", "effect": "", "facing": ""},
  {"word": "palmdown", "emoji": "🫳", "color": "", "effect": "", "facing": ""},
  {"word": "palmup", "emoji": "🫴", "color": "", "effect": "", "facing": ""},
  {"word": "pancake", "emojis": ["🥞", "🧇"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "panda", "emojis": ["🐼"], "color": "white", "effect": "", "facing": ""},
  {"word": "paper", "emojis": ["📃", "📜", "📄", "📑"], "color": "white", "effect": "", "facing": ""},
  {"word": "paper", "emojis": ["🧻"], "color": "white", "effect": "", "facing": ""}, // 重複維持
  {"word": "parachute", "emojis": ["𪪾"], "color": "orange", "effect": "rain", "facing": ""},
  {"word": "park", "emojis": ["🏞️", "🎠", "🛝", "🎡", "🎢", "🎪"], "color": "green", "effect": "", "facing": ""},
  {"word": "parking", "emojis": ["🅿️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "parrot", "emojis": ["🦜"], "color": "green", "effect": "", "facing": ""},
  {"word": "party", "emoji": "🥳", "color": "", "effect": "", "facing": ""},
  {"word": "party", "emojis": ["🎉", "🎊"], "color": "pink", "effect": "rain", "facing": ""}, // 重複維持
  {"word": "pasta", "emojis": ["🍝"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "peace", "emoji": "✌️", "color": "", "effect": "", "facing": ""},
  {"word": "peach", "emojis": ["🍑"], "color": "pink", "effect": "", "facing": ""},
  {"word": "peacock", "emojis": ["🦚"], "color": "blue", "effect": "", "facing": ""},
  {"word": "pear", "emojis": ["🍐"], "color": "green", "effect": "", "facing": ""},
  {"word": "peek", "emoji": "🫣", "color": "", "effect": "", "facing": ""},
  {"word": "pen", "emojis": ["✏️", "✒️", "🖋️", "🖊️", "🖌️", "🖍️"], "color": "pink", "effect": "", "facing": ""},
  {"word": "pen", "emojis": ["🖊️"], "color": "blue", "effect": "", "facing": ""}, // 重複維持
  {"word": "penguin", "emojis": ["🐧"], "color": "blue", "effect": "", "facing": ""},
  {"word": "pensive", "emoji": "😔", "color": "", "effect": "", "facing": ""},
  {"word": "people", "emojis": ["🧑", "👨", "👩"], "color": "", "effect": "", "facing": ""},
  {"word": "pepper", "emojis": ["🌶️", "🫑"], "color": "red", "effect": "", "facing": ""},
  {"word": "perfect", "emojis": ["💯"], "color": "red", "effect": "", "facing": ""},
  {"word": "phone", "emojis": ["🤳"], "color": "", "effect": "", "facing": ""},
  {"word": "phone", "emojis": ["📱", "📲", "☎️", "📞"], "color": "cyan", "effect": "", "facing": ""}, // 重複維持
  {"word": "phoenix", "emojis": ["🐦‍🔥"], "color": "red", "effect": "up", "facing": ""},
  {"word": "piano", "emojis": ["🎹"], "color": "white", "effect": "", "facing": ""},
  {"word": "pickaxe", "emojis": ["⛏️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "pig", "emojis": ["🐷", "🐖", "🐽"], "color": "pink", "effect": "", "facing": ""},
  {"word": "pilot", "emojis": ["🧑‍✈️", "👨‍✈️", "👩‍✈️"], "color": "", "effect": "", "facing": ""},
  {"word": "pin", "emojis": ["📌", "📍"], "color": "red", "effect": "", "facing": ""},
  {"word": "pin", "emojis": ["📌", "📍", "🧷"], "color": "red", "effect": "", "facing": ""}, // 重複維持
  {"word": "pineapple", "emojis": ["🍍"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "pingpong", "emojis": ["🏓"], "color": "red", "effect": "", "facing": ""},
  {"word": "pink", "emojis": ["🩷"], "color": "pink", "effect": "", "facing": ""},
  {"word": "pirate", "emojis": ["☠️"], "color": "", "effect": "", "facing": ""},
  {"word": "pirate", "emojis": ["🏴‍☠️"], "color": "black", "effect": "", "facing": ""}, // 重複維持
  {"word": "pita", "emojis": ["🥙", "🧆"], "color": "green", "effect": "", "facing": ""},
  {"word": "pizza", "emojis": ["🍕"], "color": "orange", "effect": "rain", "facing": ""},
  {"word": "plane", "emojis": ["✈️", "🛩️", "🛫", "🛬"], "color": "cyan", "effect": "cross", "facing": "left"},
  {"word": "planet", "emojis": ["🪐"], "color": "brown", "effect": "", "facing": ""},
  {"word": "plant", "emojis": ["🌱", "🪴", "🌿"], "color": "green", "effect": "up", "facing": ""},
  {"word": "plate", "emojis": ["🍽️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "please", "emoji": "🥺", "color": "", "effect": "", "facing": ""},
  {"word": "poker", "emoji": "😐", "color": "", "effect": "", "facing": ""},
  {"word": "police", "emojis": ["👮", "👮‍♂️", "👮‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "police", "emojis": ["拝", "🚔"], "color": "blue", "effect": "cross", "facing": "left"}, // 重複維持
  {"word": "poodle", "emojis": ["🐩"], "color": "white", "effect": "", "facing": ""},
  {"word": "poop", "emojis": ["💩"], "color": "brown", "effect": "up", "facing": ""},
  {"word": "popcorn", "emojis": ["🍿"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "post", "emojis": ["📮", "📬", "📭"], "color": "red", "effect": "", "facing": ""},
  {"word": "potato", "emojis": ["🥔", "🫜"], "color": "brown", "effect": "", "facing": ""},
  {"word": "potato", "emojis": ["🍠"], "color": "purple", "effect": "", "facing": ""}, // 重複維持
  {"word": "pot", "emojis": ["🥘", "🫕"], "color": "grey", "effect": "", "facing": ""},
  {"word": "pout", "emojis": ["Contrast🙎", "🙎‍♂️", "🙎‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "power", "emojis": ["💪"], "color": "", "effect": "up", "facing": ""},
  {"word": "power", "emojis": ["🔋", "🪫", "🔌"], "color": "green", "effect": "", "facing": ""}, // 重複維持
  {"word": "prayhand", "emoji": "🤲", "color": "", "effect": "", "facing": ""},
  {"word": "pray", "emoji": "🙏", "color": "", "effect": "", "facing": ""},
  {"word": "pregnant", "emojis": ["🫄", "🤰", "𫞃"], "color": "", "effect": "", "facing": ""},
  {"word": "present", "emojis": ["🎁"], "color": "red", "effect": "", "facing": ""},
  {"word": "printer", "emojis": ["🖨️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "print", "emojis": ["🫆"], "color": "", "effect": "", "facing": ""},
  {"word": "pudding", "emojis": ["🍮"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "puffer", "emojis": ["🐡"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "punch", "emoji": "👊", "color": "", "effect": "", "facing": ""},
  {"word": "purple", "emojis": ["💜"], "color": "purple", "effect": "", "facing": ""},
  {"word": "purple", "emojis": ["🟣", "🟪", "😈", "🍇"], "color": "purple", "effect": "", "facing": ""}, // 重複維持
  {"word": "pushleft", "emoji": "🫷", "color": "", "effect": "", "facing": ""},
  {"word": "pushright", "emoji": "🫸", "color": "", "effect": "", "facing": ""},
  {"word": "pager", "emojis": ["📟"], "color": "green", "effect": "", "facing": ""},
  {"word": "pointup", "emoji": "☝️", "color": "", "effect": "", "facing": ""},
  {"word": "pill", "emojis": ["💊"], "color": "pink", "effect": "rain", "facing": ""},

  // === Q ===
  {"word": "quiet", "emojis": ["🙊"], "color": "brown", "effect": "", "facing": ""},
  {"word": "quiet", "emojis": ["🔕"], "color": "grey", "effect": "", "facing": ""}, // 重複維持

  // === R ===
  {"word": "rabbit", "emojis": ["🐰", "🐇"], "color": "white", "effect": "", "facing": ""},
  {"word": "raccoon", "emojis": ["🦝"], "color": "grey", "effect": "", "facing": ""},
  {"word": "radio", "emojis": ["📻"], "color": "brown", "effect": "", "facing": ""},
  {"word": "rage", "emoji": "😡", "color": "", "effect": "", "facing": ""},
  {"word": "rain", "emojis": ["⛈️", "🌧️", "☔"], "color": "blue", "effect": "rain", "facing": ""},
  {"word": "rainbow", "emojis": ["🌈"], "color": "pink", "effect": "", "facing": ""},
  {"word": "raise", "emojis": ["🙋", "🙋‍♂️", "🙋‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "ramen", "emojis": ["🍜"], "color": "orange", "effect": "", "facing": ""},
  {"word": "rat", "emojis": ["🐀"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "razor", "emojis": ["🪒"], "color": "grey", "effect": "", "facing": ""},
  {"word": "realheart", "emojis": ["🫀"], "color": "red", "effect": "", "facing": ""},
  {"word": "receipt", "emojis": ["🧾"], "color": "white", "effect": "", "facing": ""},
  {"word": "redhair", "emojis": ["🧑‍🦰", "👨‍🦰", "👩‍🦰"], "color": "", "effect": "", "facing": ""},
  {"word": "red", "emojis": ["♥️", "♦️"], "color": "red", "effect": "", "facing": ""},
  {"word": "red", "emojis": ["🔴", "🟥", "🔺", "‼️", "❣️"], "color": "red", "effect": "", "facing": ""}, // 重複維持
  {"word": "relieved", "emoji": "😌", "color": "", "effect": "", "facing": ""},
  {"word": "relief", "emoji": "😥", "color": "", "effect": "", "facing": ""},
  {"word": "report", "emojis": ["👁️‍🗨️"], "color": "", "effect": "", "facing": ""},
  {"word": "rhino", "emojis": ["🦏"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "ribbon", "emojis": ["💝"], "color": "", "effect": "", "facing": ""},
  {"word": "rice", "emojis": ["🌾"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "rice", "emojis": ["🍘", "🍙", "🍚", "🍛"], "color": "white", "effect": "", "facing": ""}, // 重複維持
  {"word": "rickshaw", "emojis": ["🛺"], "color": "yellow", "effect": "cross", "facing": "left"},
  {"word": "right", "emoji": "👉", "color": "", "effect": "", "facing": ""},
  {"word": "right", "emojis": ["➡️", "🪃", "🏹"], "color": "cyan", "effect": "cross", "facing": "right"}, // 重複維持
  {"word": "righthand", "emoji": "🫱", "color": "", "effect": "", "facing": ""},
  {"word": "ring", "emojis": ["💍"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "ring", "emojis": ["💍"], "color": "cyan", "effect": "up", "facing": ""}, // 重複維持
  {"word": "roach", "emojis": ["🪳"], "color": "brown", "effect": "cross", "facing": "left"},
  {"word": "road", "emojis": ["🛣️", "🛤️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "robot", "emojis": ["🤖"], "color": "grey", "effect": "", "facing": ""},
  {"word": "robot", "emojis": ["🦾", "🦿"], "color": "grey", "effect": "", "facing": ""}, // 重複維持
  {"word": "rocket", "emojis": ["🧑‍🚀", "👨‍🚀", "👩‍🚀"], "color": "", "effect": "", "facing": ""},
  {"word": "rocket", "emojis": ["🚀"], "color": "red", "effect": "up", "facing": ""}, // 重複維持
  {"word": "rofl", "emoji": "🤣", "color": "", "effect": "", "facing": ""},
  {"word": "roll", "emoji": "🙄", "color": "", "effect": "", "facing": ""},
  {"word": "root", "emojis": ["🫜", "🧄", "🧅", "🫚"], "color": "brown", "effect": "", "facing": ""},
  {"word": "rose", "emojis": ["🌹", "🥀"], "color": "red", "effect": "", "facing": ""},
  {"word": "row", "emojis": ["🚣", "🚣‍♂️", "🚣‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "ruler", "emojis": ["📏", "📐"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "run", "emojis": ["🏃", "🏃‍♂️", "🏃‍♀️", "🏃‍➡️", "🏃‍♀️‍➡️", "🏃‍♂️‍➡️"], "color": "", "effect": "", "facing": ""},
  {"word": "run", "emojis": ["👟", "🎽"], "color": "cyan", "effect": "cross", "facing": "left"}, // 重複維持

  // === S ===
  {"word": "sad", "emoji": "☹️", "color": "", "effect": "", "facing": ""},
  {"word": "sad", "emojis": ["💔", "❤️‍🩹"], "color": "", "effect": "", "facing": ""}, // 重複維持
  {"word": "sakura", "emojis": ["🌸"], "color": "pink", "effect": "rain", "facing": ""},
  {"word": "salad", "emojis": ["🥗"], "color": "green", "effect": "", "facing": ""},
  {"word": "sake", "emojis": ["🍶"], "color": "white", "effect": "", "facing": ""},
  {"word": "salt", "emojis": ["🧂"], "color": "white", "effect": "rain", "facing": ""},
  {"word": "salute", "emoji": "🫡", "color": "", "effect": "", "facing": ""},
  {"word": "santa", "emojis": ["🧑‍🎄", "🎅", "🤶"], "color": "", "effect": "", "facing": ""},
  {"word": "sari", "emojis": ["🥻"], "color": "pink", "effect": "", "facing": ""},
  {"word": "sauna", "emojis": ["🧖", "🧖‍♂️", "🧖‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "sauna", "emojis": ["🈂️"], "color": "cyan", "effect": "up", "facing": ""}, // 重複維持
  {"word": "scale", "emojis": ["⚖️"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "scarf", "emojis": ["🧕"], "color": "", "effect": "", "facing": ""},
  {"word": "scared", "emoji": "😨", "color": "", "effect": "", "facing": ""},
  {"word": "scenery", "emojis": ["🌁", "🌃", "🏙️", "🌉"], "color": "blue", "effect": "", "facing": ""},
  {"word": "school", "emojis": ["🏫"], "color": "orange", "effect": "", "facing": ""},
  {"word": "science", "emojis": ["🧑‍🔬", "👨‍🔬", "👩‍🔬"], "color": "", "effect": "", "facing": ""},
  {"word": "scissors", "emojis": ["✂️"], "color": "red", "effect": "", "facing": ""},
  {"word": "scorpion", "emojis": ["🦂"], "color": "brown", "effect": "", "facing": ""},
  {"word": "scream", "emoji": "😱", "color": "", "effect": "", "facing": ""},
  {"word": "screwdriver", "emojis": ["🪛"], "color": "grey", "effect": "", "facing": ""},
  {"word": "sea", "emojis": ["👀", "👁️"], "color": "", "effect": "", "facing": ""},
  {"word": "search", "emojis": ["🔍", "🔎"], "color": "blue", "effect": "", "facing": ""},
  {"word": "seat", "emojis": ["𒒺"], "color": "blue", "effect": "", "facing": ""},
  {"word": "secret", "emojis": ["🙊", "🙈"], "color": "brown", "effect": "", "facing": ""},
  {"word": "secret", "emojis": ["秘！"], "color": "red", "effect": "", "facing": ""}, // 重複維持
  {"word": "security", "emojis": ["🔒", "🔏", "🔐"], "color": "grey", "effect": "", "facing": ""},
  {"word": "see", "emojis": ["👀", "👁️"], "color": "", "effect": "", "facing": ""},
  {"word": "selfie", "emojis": ["💅"], "color": "", "effect": "", "facing": ""},
  {"word": "service", "emojis": ["🈂️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "seven", "emojis": ["🕖", "🕢"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "seven", "emojis": ["7️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "sew", "emojis": ["🧵", "🪡", "🧶", "🪢"], "color": "brown", "effect": "", "facing": ""},
  {"word": "sew", "emojis": ["🪡", "🧵"], "color": "brown", "effect": "", "facing": ""}, // 重複維持
  {"word": "sexy", "emojis": ["🫦", "👄", "💅"], "color": "pink", "effect": "", "facing": ""},
  {"word": "shadow", "emojis": ["👤", "👥"], "color": "", "effect": "", "facing": ""},
  {"word": "shake", "emoji": "🫨", "color": "", "effect": "", "facing": ""},
  {"word": "shakehand", "emoji": "🤝", "color": "", "effect": "", "facing": ""},
  {"word": "shark", "emojis": ["🦈"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "sheep", "emojis": ["🐑", "🐏"], "color": "white", "effect": "", "facing": ""},
  {"word": "shell", "emojis": ["🐚"], "color": "white", "effect": "", "facing": ""},
  {"word": "shield", "emojis": ["🛡️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "shirt", "emojis": ["👔", "👕"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "ship", "emojis": ["🛳️", "⛴️", "🚢"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "shock", "emoji": "😮", "color": "", "effect": "", "facing": ""},
  {"word": "shock", "emojis": ["🙀"], "color": "blue", "effect": "", "facing": ""}, // 重複維持
  {"word": "shoes", "emojis": ["🩴", "👞", "👟", "🥾", "🥿", "👠", "👡", "🩰", "👢"], "color": "brown", "effect": "", "facing": ""},
  {"word": "shop", "emojis": ["🛍️", "👛"], "color": "pink", "effect": "rain", "facing": ""},
  {"word": "shout", "emojis": ["🗯️"], "color": "", "effect": "", "facing": ""},
  {"word": "shovel", "emojis": ["⛏️", "⚒️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "shrimp", "emojis": ["🦐"], "color": "orange", "effect": "cross", "facing": "left"},
  {"word": "shrimp", "emojis": ["🍤"], "color": "orange", "effect": "", "facing": ""}, // 重複維持
  {"word": "shrine", "emojis": ["⛩️", "🛕"], "color": "red", "effect": "", "facing": ""},
  {"word": "shrug", "emojis": ["🤷", "🤷‍♂️", "🤷‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "shush", "emoji": "🤫", "color": "", "effect": "", "facing": ""},
  {"word": "sick", "emoji": "🤒", "color": "", "effect": "", "facing": ""},
  {"word": "sick", "emojis": ["🦠"], "color": "green", "effect": "", "facing": ""}, // 重複維持
  {"word": "sigh", "emoji": "😮‍💨", "color": "", "effect": "", "facing": ""},
  {"word": "sign", "emojis": ["🛐", "⚛️", "🕉️", "✡️", "☸️", "☯️", "✝️", "☦️", "☪️", "☮️", "🕎", "🔯", "🪯", "⚕️", "♻️", "⚜️", "🔱", "📛", "🔰", "➰", "➿", "〽️", "✳️", "✴️", "❇️", "©️", "®️", "™️"], "color": "purple", "effect": "", "facing": ""},
  {"word": "signal", "emojis": ["📶", "🛜", "📳", "📴"], "color": "green", "effect": "", "facing": ""},
  {"word": "silent", "emoji": "😶", "color": "", "effect": "", "facing": ""},
  {"word": "silly", "emoji": "😝", "color": "", "effect": "", "facing": ""},
  {"word": "singer", "emojis": ["🧑‍🎤", "👨‍🎤", "👩‍🎤"], "color": "", "effect": "", "facing": ""},
  {"word": "siren", "emojis": ["🚨"], "color": "red", "effect": "", "facing": ""},
  {"word": "six", "emojis": ["⑥", "🕡"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "six", "emojis": ["6️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "skate", "emojis": ["🛹", "🛼", "⛸️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "skeleton", "emojis": ["🦴"], "color": "white", "effect": "", "facing": ""},
  {"word": "ski", "emojis": ["劇"], "color": "", "effect": "", "facing": ""},
  {"word": "ski", "emojis": ["🎿"], "color": "red", "effect": "cross", "facing": "left"}, // 重複維持
  {"word": "sky", "emojis": ["☀️", "🌤️", "☁️", "🌈", "🌌"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "skull", "emojis": ["💀"], "color": "white", "effect": "", "facing": ""},
  {"word": "sloth", "emojis": ["🦥"], "color": "brown", "effect": "", "facing": ""},
  {"word": "small", "emoji": "🤏", "color": "", "effect": "", "facing": ""},
  {"word": "smell", "emojis": ["👃"], "color": "", "effect": "", "facing": ""},
  {"word": "smirk", "emoji": "😏", "color": "", "effect": "", "facing": ""},
  {"word": "smirk", "emojis": ["😼"], "color": "orange", "effect": "", "facing": ""}, // 重複維持
  {"word": "smoke", "emojis": ["🚬"], "color": "grey", "effect": "up", "facing": ""},
  {"word": "smooch", "emoji": "😙", "color": "", "effect": "", "facing": ""},
  {"word": "snake", "emojis": ["🐍"], "color": "green", "effect": "", "facing": ""},
  {"word": "sneeze", "emoji": "🤧", "color": "", "effect": "", "facing": ""},
  {"word": "snowboard", "emojis": ["🏂"], "color": "", "effect": "", "facing": ""},
  {"word": "snow", "emojis": ["🌨️", "❄️", "☃️", "⛄"], "color": "white", "effect": "rain", "facing": ""},
  {"word": "sob", "emoji": "😢", "color": "", "effect": "", "facing": ""},
  {"word": "soccer", "emojis": ["⚽", "🥅"], "color": "white", "effect": "", "facing": ""},
  {"word": "soap", "emojis": ["🧼"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "song", "emojis": ["🎵", "🎶"], "color": "cyan", "effect": "rain", "facing": ""},
  {"word": "soon", "emojis": ["🔜"], "color": "grey", "effect": "", "facing": ""},
  {"word": "soup", "emojis": ["🍲", "🥣"], "color": "orange", "effect": "", "facing": ""},
  {"word": "spa", "emojis": ["♨️"], "color": "red", "effect": "up", "facing": ""},
  {"word": "space", "emojis": ["🛰️", "🚀", "🛸"], "color": "purple", "effect": "up", "facing": ""},
  {"word": "spade", "emojis": ["♠️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "sparkle", "emojis": ["💖"], "color": "", "effect": "", "facing": ""},
  {"word": "sparkle", "emojis": ["✨"], "color": "yellow", "effect": "rain", "facing": ""}, // 重複維持
  {"word": "speak", "emojis": ["🗣️"], "color": "", "effect": "", "facing": ""},
  {"word": "speaker", "emojis": ["🔇", "🔈", "🔉", "🔊", "📢", "📣"], "color": "grey", "effect": "", "facing": ""},
  {"word": "spend", "emojis": ["💸"], "color": "cyan", "effect": "up", "facing": ""},
  {"word": "spider", "emojis": ["🕷️"], "color": "black", "effect": "rain", "facing": ""},
  {"word": "spicy", "emojis": ["🌶️"], "color": "red", "effect": "", "facing": ""},
  {"word": "spooky", "emojis": ["👻", "💀"], "color": "", "effect": "", "facing": ""},
  {"word": "spoon", "emojis": ["🥄"], "color": "grey", "effect": "", "facing": ""},
  {"word": "sport", "emojis": ["⚽", "⚾", "🏀", "🎾", "🥊", "🎯"], "color": "green", "effect": "", "facing": ""},
  {"word": "splay", "emoji": "🖐️", "color": "", "effect": "", "facing": ""},
  {"word": "sprout", "emojis": ["🌱", "🪴"], "color": "green", "effect": "up", "facing": ""},
  {"word": "spy", "emoji": "🥸", "color": "", "effect": "", "facing": ""},
  {"word": "spy", "emojis": ["🕵️", "🕵️‍♂️", "🕵️‍♀️"], "color": "", "effect": "", "facing": ""}, // 重複維持
  {"word": "square", "emojis": ["🟥", "🟧", "🟨", "🟩", "🟦", "🟪", "🟫", "⬛", "⬜", "◼️", "◻️", "◾", "◽", "▪️", "▫️", "🔳", "🔲"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "squid", "emojis": ["🦑"], "color": "white", "effect": "up", "facing": ""},
  {"word": "squirrel", "emojis": ["🐿️"], "color": "orange", "effect": "cross", "facing": "left"},
  {"word": "stadium", "emojis": ["🏟️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "stand", "emojis": ["🧍", "🧍‍♂️", "🧍‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "star", "emoji": "⭐", "color": "", "effect": "", "facing": ""},
  {"word": "star", "emojis": ["⭐", "🌟", "🌠"], "color": "yellow", "effect": "rain", "facing": ""},
  {"word": "star", "emojis": ["*️⃣"], "color": "blue", "effect": "", "facing": ""}, // 重複維持
  {"word": "stethoscope", "emojis": ["🩺"], "color": "grey", "effect": "", "facing": ""},
  {"word": "stew", "emojis": ["🥘", "🍲", "🫕", "🥣"], "color": "orange", "effect": "", "facing": ""},
  {"word": "stone", "emojis": ["🧱", "🪨", "🪵"], "color": "brown", "effect": "", "facing": ""},
  {"word": "stop", "emoji": "✋", "color": "", "effect": "", "facing": ""},
  {"word": "stop", "emojis": ["🛑"], "color": "red", "effect": "", "facing": ""}, // 重複維持
  {"word": "store", "emojis": ["🏪"], "color": "green", "effect": "", "facing": ""},
  {"word": "straight", "emojis": ["↕️", "↔️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "strawberry", "emojis": ["🍓"], "color": "red", "effect": "", "facing": ""},
  {"word": "stress", "emoji": "😓", "color": "", "effect": "", "facing": ""},
  {"word": "student", "emojis": ["🧑‍🎓", "👨‍🎓", "👩‍🎓"], "color": "", "effect": "", "facing": ""},
  {"word": "subway", "emojis": ["🚇"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "suit", "emojis": ["♠️", "♥️", "♦️", "♣️"], "color": "red", "effect": "rain", "facing": ""},
  {"word": "summer", "emojis": ["🎋", "🎐", "🎆"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "sun", "emojis": ["🌄", "🌅", "🌆", "🌇"], "color": "orange", "effect": "", "facing": ""},
  {"word": "sun", "emojis": ["☀️", "🌞"], "color": "orange", "effect": "", "facing": ""}, // 重複維持
  {"word": "sunflower", "emojis": ["🌻"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "surprised", "emoji": "😯", "color": "", "effect": "", "facing": ""},
  {"word": "surf", "emojis": ["🏄", "🏄‍♂️"], "color": "", "effect": "", "facing": ""},
  {"word": "sushi", "emojis": ["🍣"], "color": "red", "effect": "", "facing": ""},
  {"word": "swan", "emojis": ["🦢"], "color": "white", "effect": "", "facing": ""},
  {"word": "sweat", "emoji": "😅", "color": "", "effect": "", "facing": ""},
  {"word": "sweat", "emojis": ["💦"], "color": "blue", "effect": "", "facing": ""}, // 重複維持
  {"word": "sweet", "emojis": ["🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🥧", "🍫", "🍬", "🍭", "🍮", "🍯"], "color": "pink", "effect": "rain", "facing": ""},
  {"word": "swimwear", "emojis": ["🩱", "🩲", "🩳", "👙"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "swim", "emojis": ["🏊", "🏊‍♂️", "🏊‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "swim", "emojis": ["🥽", "👙", "🦺"], "color": "cyan", "effect": "", "facing": ""}, // 重複維持
  {"word": "swirl", "emojis": ["💞"], "color": "", "effect": "", "facing": ""},
  {"word": "sword", "emojis": ["⚔️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "syringe", "emojis": ["💉"], "color": "red", "effect": "", "facing": ""},

  // === T ===
  {"word": "taco", "emojis": ["🌮", "🌯", "🫔"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "tag", "emojis": ["🏷️"], "color": "orange", "effect": "", "facing": ""},
  {"word": "takeout", "emojis": ["🥡"], "color": "white", "effect": "", "facing": ""},
  {"word": "tabletennis", "emojis": ["🏓"], "color": "red", "effect": "", "facing": ""},
  {"word": "tanabata", "emojis": ["🎋"], "color": "green", "effect": "", "facing": ""},
  {"word": "target", "emojis": ["🎯"], "color": "red", "effect": "", "facing": ""},
  {"word": "taxi", "emojis": ["🚕", "🚖"], "color": "yellow", "effect": "cross", "facing": "left"},
  {"word": "teacher", "emojis": ["🧑‍🏫", "👨‍🏫", "👩‍🏫"], "color": "", "effect": "", "facing": ""},
  {"word": "tea", "emojis": ["🫖", "🍵"], "color": "green", "effect": "", "facing": ""},
  {"word": "tear", "emoji": "😂", "color": "", "effect": "", "facing": ""},
  {"word": "telescope", "emojis": ["🔭"], "color": "blue", "effect": "", "facing": ""},
  {"word": "temple", "emojis": ["⛩️", "🏯", "🛕"], "color": "red", "effect": "", "facing": ""},
  {"word": "ten", "emojis": ["十", "🕥"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "ten", "emojis": ["🔟"], "color": "blue", "effect": "", "facing": ""},
  {"word": "tennis", "emojis": ["🎾"], "color": "green", "effect": "", "facing": ""},
  {"word": "think", "emoji": "🤔", "color": "", "effect": "", "facing": ""},
  {"word": "think", "emojis": ["🧠"], "color": "pink", "effect": "", "facing": ""}, // 重複維持
  {"word": "three", "emojis": ["🕒", "🕞"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "three", "emojis": ["3️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "throb", "emojis": ["💓"], "color": "", "effect": "", "facing": ""},
  {"word": "thunder", "emojis": ["🌩️", "⚡"], "color": "yellow", "effect": "rain", "facing": ""},
  {"word": "ticket", "emojis": ["🎟️", "🎫"], "color": "orange", "effect": "", "facing": ""},
  {"word": "tiger", "emojis": ["🐯", "🐅"], "color": "orange", "effect": "cross", "facing": "left"},
  {"word": "time", "emojis": ["⌚", "⏰", "⏱️", "🕰️", "⌛"], "color": "grey", "effect": "", "facing": ""},
  {"word": "tired", "emoji": "🫩", "color": "", "effect": "", "facing": ""},
  {"word": "toast", "emojis": ["🍞", "🥞"], "color": "orange", "effect": "", "facing": ""},
  {"word": "toilet", "emojis": ["🚽", "🪠", "環境", "🚰", "♿", "🚹", "🚺", "🚻", "🚼", "🚾"], "color": "blue", "effect": "", "facing": ""},
  {"word": "tomato", "emojis": ["🍅"], "color": "red", "effect": "", "facing": ""},
  {"word": "tongue", "emoji": "😛", "color": "", "effect": "", "facing": ""},
  {"word": "tongue", "emojis": ["👅"], "color": "red", "effect": "", "facing": ""}, // 重複維持
  {"word": "tool", "emojis": ["🔨", "🪓", "⛏️", "⚒️", "🛠️", "🪚", "🔧", "🪛", "🔩", "⚙️", "🗜️", "🧰"], "color": "grey", "effect": "", "facing": ""},
  {"word": "toothbrush", "emojis": ["🪥"], "color": "pink", "effect": "", "facing": ""},
  {"word": "toothpaste", "emojis": ["🪥"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "top", "emojis": ["🔝"], "color": "grey", "effect": "up", "facing": ""},
  {"word": "tornado", "emojis": ["🌪️"], "color": "grey", "effect": "up", "facing": ""},
  {"word": "tower", "emojis": ["🗼"], "color": "red", "effect": "up", "facing": ""},
  {"word": "tooth", "emojis": ["🦷"], "color": "white", "effect": "", "facing": ""},
  {"word": "toy", "emojis": ["🪀", "🪁", "🧸", "🪅", "🪆"], "color": "pink", "effect": "", "facing": ""},
  {"word": "tractor", "emojis": ["🚜"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "tracks", "emojis": ["👣", "🐾"], "color": "", "effect": "", "facing": ""},
  {"word": "train", "emojis": ["🚂", "🚃", "🚄", "🚅", "🚆", "🚇", "🚈", "🚊", "🚝", "🚞", "🚋", "🚉", "🚟"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "trap", "emojis": ["🪤"], "color": "brown", "effect": "", "facing": ""},
  {"word": "trash", "emojis": ["🗑️"], "color": "grey", "effect": "", "facing": ""},
  {"word": "travel", "emojis": ["✈️", "🧳", "🗺️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "tree", "emojis": ["🌲", "🌳", "🪾"], "color": "green", "effect": "", "facing": ""},
  {"word": "triangle", "emojis": ["🔺", "🔻"], "color": "red", "effect": "", "facing": ""},
  {"word": "trophy", "emojis": ["🏆"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "troll", "emojis": ["🧌"], "color": "", "effect": "", "facing": ""},
  {"word": "truck", "emojis": ["🚚", "🚛", "🛻"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "tsukimi", "emojis": ["🎑"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "tulip", "emojis": ["🌷"], "color": "pink", "effect": "", "facing": ""},
  {"word": "turban", "emojis": ["👳", "👳‍♂️", "👳‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "turkey", "emojis": ["🦃"], "color": "brown", "effect": "", "facing": ""},
  {"word": "turn", "emojis": ["↩️", "↪️", "⤴️", "⤵️"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "turtle", "emojis": ["🐢"], "color": "green", "effect": "cross", "facing": "left"},
  {"word": "tuxedo", "emojis": ["🤵", "🤵‍♂️", "🤵‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "tv", "emojis": ["📺"], "color": "brown", "effect": "", "facing": ""},
  {"word": "twelve", "emojis": ["🕛", "🛧"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "two", "emojis": ["🕑", "🕝"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "two", "emojis": ["2️⃣"], "color": "blue", "effect": "", "facing": ""}, // 重複維持
  {"word": "typhoon", "emojis": ["🌀", "🌪️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "thought", "emojis": ["💭"], "color": "", "effect": "", "facing": ""},

  // === U ===
  {"word": "ufo", "emojis": ["👽", "👾"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "ufo", "emojis": ["🛸"], "color": "green", "effect": "rain", "facing": ""}, // 重複維持
  {"word": "umbrella", "emojis": ["🌂", "☂️", "⛱️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "unicorn", "emojis": ["🦄"], "color": "pink", "effect": "cross", "facing": "left"},
  {"word": "uniform", "emojis": ["🥼", "🦺", "🎽"], "color": "white", "effect": "", "facing": ""},
  {"word": "unlock", "emojis": ["🔓"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "up", "emoji": "👆", "color": "", "effect": "", "facing": ""},
  {"word": "up", "emojis": ["⬆️", "🛗", "🎈", "🚀"], "color": "cyan", "effect": "up", "facing": ""}, // 重複維持
  {"word": "upside", "emoji": "🙃", "color": "", "effect": "", "facing": ""},
  {"word": "upset", "emoji": "😧", "color": "", "effect": "", "facing": ""},

  // === V ===
  {"word": "vampire", "emojis": ["🧛", "🧛‍♂️", "🧛‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "veggie", "emojis": ["🍅", "🥑", "🍆", "🥔", "🥕", "🌽", "🌶️", "🫑", "🥒", "🥬", "🥦"], "color": "green", "effect": "", "facing": ""},
  {"word": "vegetable", "emojis": ["🍅", "🥑", "🍆", "🥔", "🥕", "🌽", "🌶️", "🫑", "🥒", "🥬", "🥦"], "color": "green", "effect": "", "facing": ""},
  {"word": "vein", "emojis": ["💢"], "color": "red", "effect": "", "facing": ""},
  {"word": "veil", "emojis": ["👰", "👰‍♂️", "👰‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "vhs", "emojis": ["📼"], "color": "black", "effect": "", "facing": ""},
  {"word": "view", "emojis": ["🌁", "🌃", "🏙️", "🌉"], "color": "blue", "effect": "", "facing": ""},
  {"word": "villain", "emojis": ["🦹", "🦹‍♂️", "🦹‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "violin", "emojis": ["🎻"], "color": "brown", "effect": "", "facing": ""},
  {"word": "virus", "emojis": ["🦠"], "color": "green", "effect": "", "facing": ""},
  {"word": "volcano", "emojis": ["🌋"], "color": "red", "effect": "up", "facing": ""},
  {"word": "vote", "emojis": ["🗳️"], "color": "blue", "effect": "", "facing": ""},
  {"word": "vulcan", "emoji": "🖖", "color": "", "effect": "", "facing": ""},

  // === W ===
  {"word": "walk", "emojis": ["🚶", "🚶‍♂️", "🚶‍♀️", "🚶‍➡️", "🚶‍♂️‍➡️", "🚶‍♀️‍➡️"], "color": "", "effect": "", "facing": ""},
  {"word": "walk", "emojis": ["👞", "🥿", "🩴", "👡"], "color": "brown", "effect": "", "facing": ""}, // 重複維持
  {"word": "warning", "emojis": ["⚠️", "🚸", "☢️", "☣️"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "washoku", "emojis": [" Bento", "🍙", "🍚", "🍛", "🍢", "🍣", "🍤", "🍥", "🍡"], "color": "red", "effect": "", "facing": ""},
  {"word": "watch", "emojis": ["👀"], "color": "", "effect": "", "facing": ""},
  {"word": "watch", "emojis": ["⌚"], "color": "grey", "effect": "", "facing": ""}, // 重複維持
  {"word": "watermelon", "emojis": ["🍉"], "color": "red", "effect": "", "facing": ""},
  {"word": "waterpolo", "emojis": ["🤽", "🤽‍♂️", "🤽‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "wave", "emoji": "👋", "color": "", "effect": "", "facing": ""},
  {"word": "wave", "emojis": ["🌊"], "color": "blue", "effect": "", "facing": ""}, // 重複維持
  {"word": "weapon", "emojis": ["🗡️", "⚔️", "💣", "🪃", "🏹", "🛡️"], "color": "red", "effect": "", "facing": ""},
  {"word": "weary", "emoji": "😩", "color": "", "effect": "", "facing": ""},
  {"word": "weather", "emojis": ["☀️", "☁️", "🌧️", "❄️", "⚡"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "web", "emojis": ["🕸️"], "color": "white", "effect": "", "facing": ""},
  {"word": "wedding", "emojis": ["💒"], "color": "pink", "effect": "", "facing": ""},
  {"word": "weight", "emojis": ["🏋️", "🏋️‍♂️", "🏋️‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "whale", "emojis": ["🐳", "🐋"], "color": "blue", "effect": "cross", "facing": "left"},
  {"word": "wheelchair", "emojis": ["🧑‍🦼", "👨‍🦼", "👩‍🦼", "🧑‍🦼‍➡️", "👨‍🦼‍➡️", "👩‍🦼‍➡️", "🧑‍🦽", "🧑‍🦽‍➡️", "👨‍🦽", "👨‍🦽‍➡️", "👩‍🦽", "👩‍🦽‍➡️"], "color": "", "effect": "", "facing": ""},
  {"word": "wheelchair", "emojis": ["🦽", "🦼"], "color": "blue", "effect": "cross", "facing": "left"}, // 重複維持
  {"word": "wheel", "emojis": ["🛞"], "color": "grey", "effect": "", "facing": ""},
  {"word": "white", "emojis": ["🤍"], "color": "white", "effect": "", "facing": ""},
  {"word": "white", "emojis": ["⚪", "⬜", "◻️", "◽", "▫️", "🔲", "🤍"], "color": "white", "effect": "", "facing": ""}, // 重複維持
  {"word": "whitehair", "emojis": ["🧑‍🦳", "👨‍🦳", "👩‍🦳"], "color": "", "effect": "", "facing": ""},
  {"word": "win", "emojis": ["🏆", "🥇", "✨"], "color": "yellow", "effect": "up", "facing": ""},
  {"word": "windinstrument", "emojis": ["🎷", "🎺", "🪗", "🪈"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "window", "emojis": ["🪟"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "wind", "emojis": ["🌬️", "🌀"], "color": "cyan", "effect": "cross", "facing": "left"},
  {"word": "wine", "emojis": ["🍾", "🍷"], "color": "red", "effect": "", "facing": ""},
  {"word": "wink", "emoji": "😉", "color": "", "effect": "", "facing": ""},
  {"word": "winterwear", "emojis": ["🧣", "🧤", "🧦"], "color": "white", "effect": "", "facing": ""},
  {"word": "winter", "emojis": ["❄️", "☃️", "⛄", "🎿", "🛷", "🥌"], "color": "white", "effect": "", "facing": ""},
  {"word": "witness", "emojis": ["👁️‍🗨️"], "color": "", "effect": "", "facing": ""},
  {"word": "wolf", "emojis": ["🐺"], "color": "grey", "effect": "cross", "facing": "left"},
  {"word": "world", "emojis": ["🌍", "🌎", "🌏", "🌐"], "color": "cyan", "effect": "", "facing": ""},
  {"word": "worry", "emoji": "😟", "color": "", "effect": "", "facing": ""},
  {"word": "wrench", "emojis": ["🧑‍🔧", "👨‍🔧", "👩‍🔧"], "color": "", "effect": "", "facing": ""},
  {"word": "wrench", "emojis": ["🔧"], "color": "grey", "effect": "", "facing": ""}, // 重複維持
  {"word": "wrestle", "emojis": ["🤼", "🤼‍♂️", "🤼‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "write", "emoji": "✍️", "color": "", "effect": "", "facing": ""},
  {"word": "worm", "emojis": ["🪱"], "color": "pink", "effect": "", "facing": ""},

  // === X ===
  {"word": "xmas", "emojis": ["🎄"], "color": "green", "effect": "", "facing": ""},
  {"word": "xray", "emojis": ["🩻"], "color": "cyan", "effect": "", "facing": ""},

  // === Y ===
  {"word": "yarn", "emojis": ["🧶"], "color": "pink", "effect": "", "facing": ""},
  {"word": "yawn", "emoji": "🥱", "color": "", "effect": "", "facing": ""},
  {"word": "yellow", "emojis": ["💛"], "color": "yellow", "effect": "", "facing": ""},
  {"word": "yellow", "emojis": ["🟡", "🟨", "🌟", "⚡", "✨"], "color": "yellow", "effect": "", "facing": ""}, // 重複維持
  {"word": "yes", "emoji": "🙂‍↕️", "color": "", "effect": "", "facing": ""},
  {"word": "yoga", "emojis": ["🧘", "🧘‍♂️", "🧘‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "you", "emoji": "🫵", "color": "", "effect": "", "facing": ""},
  {"word": "yummy", "emoji": "😋", "color": "", "effect": "", "facing": ""},
  {"word": "yummy", "emojis": ["🍔", "🍕", "🍦", "🍩", "🍪", "🎂", "🍫", "🍬", "🍭"], "color": "pink", "effect": "rain", "facing": ""}, // 重複維持

  // === Z ===
  {"word": "zany", "emoji": "🤪", "color": "", "effect": "", "facing": ""},
  {"word": "zebra", "emojis": ["🦓"], "color": "white", "effect": "cross", "facing": "left"},
  {"word": "zero", "emojis": ["0️⃣"], "color": "blue", "effect": "", "facing": ""},
  {"word": "zipper", "emoji": "🤐", "color": "", "effect": "", "facing": ""},
  {"word": "zodiac", "emojis": ["♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓", "⛎"], "color": "purple", "effect": "rain", "facing": ""},
  {"word": "zombie", "emojis": ["🧟", "🧟‍♂️", "🧟‍♀️"], "color": "", "effect": "", "facing": ""},
  {"word": "zzz", "emojis": ["💤"], "color": "cyan", "effect": "", "facing": ""},

  // 旧データから消えた分を追加
  // === 表情・感情（打った瞬間にプレイヤーの気分を代弁！） ===
    {"word": "smile", "emojis": ["🙂"], "color": "yellow", "effect": "", "facing": ""}, // ほほえみ
    {"word": "angel", "emojis": ["😇"], "color": "cyan", "effect": "up", "facing": ""}, // 天使・尊い（フワフワ上昇）
    {"word": "star", "emojis": ["🤩"], "color": "yellow", "effect": "", "facing": ""}, // 目が星（既存の星マーク群と合体！）
    {"word": "sleepy", "emojis": ["😪"], "color": "blue", "effect": "", "facing": ""}, // ねむい（鼻ちょうちん）
    {"word": "sleep", "emojis": ["😴"], "color": "blue", "effect": "", "facing": ""}, // おやすみ
    {"word": "puke", "emojis": ["🤮"], "color": "green", "effect": "", "facing": ""}, // ゲロゲロ
    {"word": "dizzy", "emojis": ["😵‍💫"], "color": "purple", "effect": "", "facing": ""}, // 目がまわる・混乱

    // === ハンドサイン・ジェスチャー ===
    {"word": "chef", "emojis": ["🤌"], "color": "white", "effect": "", "facing": ""}, // 指をすぼめる（イタリア人の「なんやねん」やシェフのポーズ）
    {"word": "heart", "emojis": ["🫰"], "color": "pink", "effect": "up", "facing": ""}, // 指ハート（既存のハートと合体！）
    {"word": "rock", "emojis": ["🤘"], "color": "red", "effect": "", "facing": ""}, // ロックンロール！
    {"word": "phone", "emojis": ["🤙"], "color": "cyan", "effect": "", "facing": ""}, // 電話してね（既存のphoneと合体！）

    // === 生き物・サファリ・海・虫（横向きは cross で大暴れ！） ===
    {"word": "ski", "emojis": ["⛷️"], "color": "white", "effect": "cross", "facing": "left"}, // スキーヤー（冬スポーツと合体！）
    {"word": "skunk", "emojis": ["🦨"], "color": "black", "effect": "cross", "facing": "left"}, // スカンク
    {"word": "wing", "emojis": ["🪽"], "color": "white", "effect": "rain", "facing": ""}, // 天使の羽（空から舞い落ちる）
    {"word": "seal", "emojis": ["🦭"], "color": "grey", "effect": "cross", "facing": "left"}, // アザラシ
    {"word": "lobster", "emojis": ["🦞"], "color": "red", "effect": "cross", "facing": "left"}, // ロブスター
    {"word": "snail", "emojis": ["🐌"], "color": "brown", "effect": "cross", "facing": "left"}, // カタツムリ

    // === 植物・お花（ひらひら舞い落ちる rain 演出） ===
    {"word": "flower", "emojis": ["💮", "🏵️", "🌼"], "color": "pink", "effect": "rain", "facing": ""}, // お花（既存のflowerと合体！）
    {"word": "lotus", "emojis": ["🪷"], "color": "pink", "effect": "rain", "facing": ""}, // ハスの花

    // === グルメ・カフェ・食器 ===
    {"word": "sandwich", "emojis": ["🥪"], "color": "orange", "effect": "", "facing": ""}, // サンドイッチ
    {"word": "mooncake", "emojis": ["🥮"], "color": "orange", "effect": "", "facing": ""}, // 月餅
    {"word": "jar", "emojis": ["🫙", "🏺"], "color": "brown", "effect": "", "facing": ""}, // 保存瓶とアンフォラ（壺）

    // === 建物・景色・お天気 ===
    {"word": "hotel", "emojis": ["🏨", "🏩"], "color": "pink", "effect": "", "facing": ""}, // ホテル・ラブホ（既存のhotelと合体！）
    {"word": "thermometer", "emojis": ["🌡️"], "color": "red", "effect": "", "facing": ""}, // 体温計・温度計
    {"word": "drop", "emojis": ["💧"], "color": "cyan", "effect": "rain", "facing": ""}, // 水滴（雨・涙）

    // === シーズンイベント・公共インフラ ===
    {"word": "koinobori", "emojis": ["🎏"], "color": "blue", "effect": "cross", "facing": "left"}, // 鯉のぼり（春イベントと合体！）
    {"word": "badminton", "emojis": ["🏸"], "color": "white", "effect": "", "facing": ""}, // バドミントン（スポーツと合体！）
    {"word": "airport", "emojis": ["🛂"], "color": "blue", "effect": "", "facing": ""}, // パスポートコントロール（空港マークと合体！）
    {"word": "secret", "emojis": ["㊙️"], "color": "red", "effect": "", "facing": ""}, // マル秘（既存のsecretと合体！）
];